version: '3.1'
networks:
  web:
    external:
      name: custom_network
services:
  # NGINX is just here to help with setting up a Proxy
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
      # This is just in case you don't have local.oauth.burningman.org set up in your hosts
      - 34580:34580
      # This is just in case you don't have test.oauth.burningman.org set up in your hosts
      - 14580:14580      
    networks:
      - web

  wordpress:
    image: wordpress
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./:/var/www/html/wp-content/plugins/wp-plugin-bm-oauth-client
    networks:
      - web
      
  wordpress_test:
    image: wordpress
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db_test
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb_test
    volumes:
      - ./:/var/www/html/wp-content/plugins/wp-plugin-bm-oauth-client
    networks:
      - web      

  db_test:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: exampledb_test
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      # Import the dump file into the DB
      - ./tests/_data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - web      

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      # Import the dump file into the DB
      - ./tests/_data/dump2.sql:/docker-entrypoint-initdb.d/dump2.sql
    networks:
      - web      
      
  codecept:
    image: codeception/codeception
    depends_on:
      - chrome
      - wordpress
      - db
    volumes:
      - ./:/project
      - ./wordpress:/project/wordpress/wp-content/plugins/wp-plugin-bm-oauth-client
    networks:
      - web          

  chrome:
    image: selenium/standalone-chrome
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps= 
    networks:
      - web          

volumes:
  wordpress:
  db:
  wordpress_test:
  db_test:
  codecept: