CREATE TABLE IF NOT EXISTS `#__rsform_forms` (
  `FormId` int(11) NOT NULL auto_increment,
  `FormName` text NOT NULL,
  `FormLayout` longtext NOT NULL,
  `GridLayout` mediumtext NOT NULL,
  `FormLayoutName` text NOT NULL,
  `LoadFormLayoutFramework` tinyint(1) NOT NULL default '1',
  `FormLayoutAutogenerate` tinyint(1) NOT NULL default '1',
  `FormLayoutFlow` tinyint(1) NOT NULL default '0',
  `DisableSubmitButton` tinyint(1) NOT NULL default '0',
  `RemoveCaptchaLogged` tinyint(1) NOT NULL default '0',
  `CSS` mediumtext NOT NULL,
  `JS` mediumtext NOT NULL,
  `FormTitle` text NOT NULL,
  `ShowFormTitle` tinyint(1) NOT NULL default '1',
  `Published` tinyint(1) NOT NULL default '1',
  `Lang` varchar(32) NOT NULL default '',
  `ReturnUrl` text NOT NULL,
  `ShowSystemMessage` tinyint(1) NOT NULL default '1',
  `ShowThankyou` tinyint(1) NOT NULL default '1',
  `ScrollToThankYou` tinyint(1) NOT NULL default '0',
  `ThankYouMessagePopUp` tinyint(1) NOT NULL default '0',
  `Thankyou` mediumtext NOT NULL,
  `ShowContinue` tinyint(1) NOT NULL default '1',
  `UserEmailText` mediumtext NOT NULL,
  `UserEmailTo` text NOT NULL,
  `UserEmailCC` text NOT NULL,
  `UserEmailBCC` text NOT NULL,
  `UserEmailFrom` text NOT NULL,
  `UserEmailReplyTo` text NOT NULL,
  `UserEmailReplyToName` text NOT NULL,
  `UserEmailFromName` text NOT NULL,
  `UserEmailSubject` text NOT NULL,
  `UserEmailMode` tinyint(1) NOT NULL default '1',
  `UserEmailAttach` tinyint(1) NOT NULL,
  `UserEmailAttachFile` text NOT NULL,
  `UserEmailGenerate` tinyint(1) NOT NULL default '0',
  `AdminEmailText` mediumtext NOT NULL,
  `AdminEmailTo` text NOT NULL,
  `AdminEmailCC` text NOT NULL,
  `AdminEmailBCC` text NOT NULL,
  `AdminEmailFrom` text NOT NULL,
  `AdminEmailReplyTo` text NOT NULL,
  `AdminEmailReplyToName` text NOT NULL,
  `AdminEmailFromName` text NOT NULL,
  `AdminEmailSubject` text NOT NULL,
  `AdminEmailMode` tinyint(1) NOT NULL default '1',
  `AdminEmailGenerate` tinyint(1) NOT NULL default '0',
  `DeletionEmailText` mediumtext NOT NULL,
  `DeletionEmailTo` text NOT NULL,
  `DeletionEmailCC` text NOT NULL,
  `DeletionEmailBCC` text NOT NULL,
  `DeletionEmailFrom` text NOT NULL,
  `DeletionEmailReplyTo` text NOT NULL,
  `DeletionEmailReplyToName` text NOT NULL,
  `DeletionEmailFromName` text NOT NULL,
  `DeletionEmailSubject` text NOT NULL,
  `DeletionEmailMode` tinyint(1) NOT NULL default '1',
  `ScriptProcess` mediumtext NOT NULL,
  `ScriptProcess2` mediumtext NOT NULL,
  `ScriptBeforeDisplay` mediumtext NOT NULL,
  `ScriptBeforeValidation` mediumtext NOT NULL,
  `ScriptDisplay` mediumtext NOT NULL,
  `UserEmailScript` mediumtext NOT NULL,
  `AdminEmailScript` mediumtext NOT NULL,
  `AdditionalEmailsScript` mediumtext NOT NULL,
  `MetaTitle` tinyint(1) NOT NULL,
  `MetaDesc` text NOT NULL,
  `MetaKeywords` text NOT NULL,
  `Required` varchar(255) NOT NULL default '(*)',
  `ErrorMessage` text NOT NULL,
  `MultipleSeparator` varchar(64) NOT NULL default '\\n',
  `TextareaNewLines` tinyint(1) NOT NULL default '1',
  `CSSClass` varchar(255) NOT NULL,
  `CSSId` varchar(255) NOT NULL default 'userForm',
  `CSSName` varchar(255) NOT NULL,
  `CSSAction` text NOT NULL,
  `CSSAdditionalAttributes` text NOT NULL,
  `AjaxValidation` tinyint(1) NOT NULL,
  `ScrollToError` tinyint(1) NOT NULL,
  `Keepdata` tinyint(1) NOT NULL default '1',
  `KeepIP` tinyint(1) NOT NULL default '1',
  `DeleteSubmissionsAfter` int(11) NOT NULL default '0',
  `Backendmenu` tinyint(1) NOT NULL,
  `ConfirmSubmission` tinyint(1) NOT NULL DEFAULT '0',
  `ConfirmSubmissionDefer` text NOT NULL,
  `ConfirmSubmissionUrl` text NOT NULL,
  `Access` varchar(5) NOT NULL,
  `LimitSubmissions` int(11) NOT NULL default '0',
  PRIMARY KEY  (`FormId`)
) DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;