
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `civicrm_mailing_bounce_pattern`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `civicrm_mailing_bounce_pattern` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `bounce_type_id` int(10) unsigned NOT NULL COMMENT 'Type of bounce',
  `pattern` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'A regexp to match a message to a bounce type',
  PRIMARY KEY (`id`),
  KEY `FK_civicrm_mailing_bounce_pattern_bounce_type_id` (`bounce_type_id`),
  CONSTRAINT `FK_civicrm_mailing_bounce_pattern_bounce_type_id` FOREIGN KEY (`bounce_type_id`) REFERENCES `civicrm_mailing_bounce_type` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=165 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `civicrm_mailing_bounce_pattern` WRITE;
/*!40000 ALTER TABLE `civicrm_mailing_bounce_pattern` DISABLE KEYS */;
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (1,1,'Client TOS Notification');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (2,2,'(be|am)? (out of|away from) (the|my)? (office|computer|town)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (3,2,'i am on vacation');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (4,3,'name(server entry| lookup failure)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (5,3,'no (mail server|matches to nameserver query|dns entries)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (6,3,'reverse dns entry');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (7,3,'Host or domain name not found');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (8,3,'Unable to resolve MX record for');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (9,4,'(unknown|not local) host');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (10,4,'all hosts have been failing');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (11,4,'allowed rcpthosts');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (12,4,'connection (refused|timed out)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (13,4,'not connected');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (14,4,'couldn\'t find any host named');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (15,4,'error involving remote host');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (16,4,'host unknown');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (17,4,'invalid host name');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (18,4,'isn\'t in my control/locals file');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (19,4,'local configuration error');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (20,4,'not a gateway');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (21,4,'server is (down or unreachable|not responding)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (22,4,'too many connections');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (23,4,'unable to connect');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (24,4,'lost connection');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (25,4,'conversation with [^ ]* timed out while');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (26,4,'server requires authentication');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (27,4,'authentication (is )?required');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (28,5,'(my )?e-?mail( address)? has changed');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (29,5,'account (inactive|expired|deactivated)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (30,5,'account is locked');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (31,5,'changed w+( e-?mail)? address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (32,5,'deactivated mailbox');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (33,5,'disabled or discontinued');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (34,5,'inactive user');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (35,5,'is inactive on this domain');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (36,5,'mail receiving disabled');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (37,5,'mail( ?)address is administrative?ly disabled');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (38,5,'mailbox (temporarily disabled|currently suspended)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (39,5,'no longer (accepting mail|on server|in use|with|employed|on staff|works for|using this account)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (40,5,'not accepting (mail|messages)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (41,5,'please use my new e-?mail address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (42,5,'this address no longer accepts mail');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (43,5,'user account suspended');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (44,5,'account that you tried to reach is disabled');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (45,5,'User banned');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (46,6,'(user|recipient( name)?) is not recognized');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (47,6,'554 delivery error');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (48,6,'address does not exist');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (49,6,'address(es)?( you (entered|specified))? (could|was)( not|n.t)( be)? found');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (50,6,'address(ee)? (unknown|invalid)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (51,6,'bad destination');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (52,6,'badly formatted address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (53,6,'can\'t open mailbox for');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (54,6,'cannot deliver');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (55,6,'delivery to the following recipient(s)? failed');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (56,6,'destination addresses were unknown');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (57,6,'did not reach the following recipient');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (58,6,'does not exist');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (59,6,'does not like recipient');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (60,6,'does not specify a valid notes mail file');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (61,6,'illegal alias');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (62,6,'invalid (mailbox|(e-?mail )?address|recipient|final delivery)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (63,6,'invalid( or unknown)?( virtual)? user');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (64,6,'(mail )?delivery (to this user )?is not allowed');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (65,6,'mailbox (not found|unavailable|name not allowed)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (66,6,'message could not be forwarded');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (67,6,'missing or malformed local(-| )part');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (68,6,'no e-?mail address registered');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (69,6,'no such (mail drop|mailbox( \\w+)?|(e-?mail )?address|recipient|(local )?user|person)( here)?');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (70,6,'no mailbox (here )?by that name');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (71,6,'not (listed in|found in directory|known at this site|our customer)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (72,6,'not a valid( (user|mailbox))?');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (73,6,'not present in directory entry');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (74,6,'recipient (does not exist|(is )?unknown|rejected|denied|not found)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (75,6,'this user doesn\'t have a yahoo.com address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (76,6,'unavailable to take delivery of the message');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (77,6,'unavailable mailbox');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (78,6,'unknown (local( |-)part|recipient|address error)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (79,6,'unknown( or illegal)? user( account)?');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (80,6,'unrecognized recipient');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (81,6,'unregistered address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (82,6,'user (unknown|does not exist)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (83,6,'user doesn\'t have an? w+ account');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (84,6,'user(\'s e-?mail name is)? not found');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (85,6,'^Validation failed for:');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (86,6,'5.1.0 Address rejected');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (87,6,'no valid recipients?');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (88,6,'RecipNotFound');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (89,6,'no one at this address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (90,6,'misconfigured forwarding address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (91,6,'account is not allowed');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (92,6,'Address .<[^>]*>. not known here');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (93,6,'Recipient address rejected: ([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (94,6,'Non sono riuscito a trovare l.indirizzo e-mail');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (95,6,'nadie con esta direcci..?n');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (96,6,'ni bilo mogo..?e najti prejemnikovega e-po..?tnega naslova');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (97,6,'Elektronski naslov (je ukinjen|ne obstaja)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (98,6,'nepravilno nastavljen predal');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (99,7,'(mail( forwarding)?|routing).loop');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (100,7,'excessive recursion');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (101,7,'loop detected');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (102,7,'maximum hop count exceeded');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (103,7,'message was forwarded more than the maximum allowed times');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (104,7,'too many (hops|recursive forwards)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (105,8,'(disk(space)?|over the allowed|exceed(ed|s)?|storage) quota');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (106,8,'522_mailbox_full');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (107,8,'exceeds allowed message count');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (108,8,'file too large');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (109,8,'full mailbox');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (110,8,'(mail|in)(box|folder) ((for user \\w+ )?is )?full');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (111,8,'mailbox (has exceeded|is over) the limit');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (112,8,'mailbox( exceeds allowed)? size');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (113,8,'no space left for this user');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (114,8,'over\\s?quota');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (115,8,'quota (for the mailbox )?has been exceeded');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (116,8,'quota ?(usage|violation|exceeded)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (117,8,'recipient storage full');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (118,8,'not able to receive more mail');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (119,8,'doesn.t have enough disk space left');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (120,8,'exceeded storage allocation');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (121,8,'running out of disk space');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (122,9,'cannot find your hostname');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (123,9,'ip name lookup');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (124,9,'not configured to relay mail');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (125,9,'relay(ing)? (not permitted|(access )?denied)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (126,9,'relayed mail to .+? not allowed');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (127,9,'sender ip must resolve');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (128,9,'unable to relay');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (129,9,'No route to host');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (130,9,'Network is unreachable');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (131,9,'unrouteable address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (132,9,'We don.t handle mail for');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (133,9,'we do not relay');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (134,9,'Rejected by next-hop');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (135,9,'not permitted to( *550)? relay through this server');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (136,10,'(bulk( e-?mail)|content|attachment blocking|virus|mail system) filters?');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (137,10,'(hostile|questionable|unacceptable) content');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (138,10,'address .+? has not been verified');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (139,10,'anti-?spam (policw+|software)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (140,10,'anti-?virus gateway has detected');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (141,10,'blacklisted');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (142,10,'blocked message');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (143,10,'content control');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (144,10,'delivery not authorized');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (145,10,'does not conform to our e-?mail policy');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (146,10,'excessive spam content');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (147,10,'message looks suspicious');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (148,10,'open relay');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (149,10,'sender was rejected');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (150,10,'spam(check| reduction software| filters?)');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (151,10,'blocked by a user configured filter');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (152,10,'(detected|rejected) (as|due to) spam');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (153,10,'X-HmXmrOriginalRecipient');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (154,10,'Client host .[^ ]*. blocked');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (155,10,'automatic(ally-generated)? messages are not accepted');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (156,10,'denied by policy');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (157,10,'has no corresponding reverse \\(PTR\\) address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (158,10,'has a policy that( [^ ]*)? prohibited the mail that you sent');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (159,10,'is likely unsolicited mail');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (160,10,'Local Policy Violation');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (161,10,'ni bilo mogo..?e dostaviti zaradi varnostnega pravilnika');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (162,11,'nonstandard smtp line terminator');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (163,11,'syntax error in from address');
INSERT INTO `civicrm_mailing_bounce_pattern` (`id`, `bounce_type_id`, `pattern`) VALUES (164,11,'unknown smtp code');
/*!40000 ALTER TABLE `civicrm_mailing_bounce_pattern` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

