
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `civicrm_mailing`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `civicrm_mailing` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `domain_id` int(10) unsigned DEFAULT NULL COMMENT 'Which site is this mailing for',
  `header_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the header component.',
  `footer_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the footer component.',
  `reply_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the auto-responder component.',
  `unsubscribe_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the unsubscribe component.',
  `resubscribe_id` int(10) unsigned DEFAULT NULL,
  `optout_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the opt-out component.',
  `name` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Mailing Name.',
  `mailing_type` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'differentiate between standalone mailings, A/B tests, and A/B final-winner',
  `from_name` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'From Header of mailing',
  `from_email` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'From Email of mailing',
  `replyto_email` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Reply-To Email of mailing',
  `template_type` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'traditional' COMMENT 'The language/processing system used for email templates.',
  `template_options` longtext COLLATE utf8_unicode_ci COMMENT 'Advanced options used by the email templating system. (JSON encoded)',
  `subject` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Subject of mailing',
  `body_text` longtext COLLATE utf8_unicode_ci COMMENT 'Body of the mailing in text format.',
  `body_html` longtext COLLATE utf8_unicode_ci COMMENT 'Body of the mailing in html format.',
  `url_tracking` tinyint(4) DEFAULT NULL COMMENT 'Should we track URL click-throughs for this mailing?',
  `forward_replies` tinyint(4) DEFAULT NULL COMMENT 'Should we forward replies back to the author?',
  `auto_responder` tinyint(4) DEFAULT NULL COMMENT 'Should we enable the auto-responder?',
  `open_tracking` tinyint(4) DEFAULT NULL COMMENT 'Should we track when recipients open/read this mailing?',
  `is_completed` tinyint(4) DEFAULT NULL COMMENT 'Has at least one job associated with this mailing finished?',
  `msg_template_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the message template.',
  `override_verp` tinyint(4) DEFAULT '0' COMMENT 'Should we overrite VERP address in Reply-To',
  `created_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Contact ID who first created this mailing',
  `created_date` timestamp NULL DEFAULT NULL COMMENT 'Date and time this mailing was created.',
  `modified_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When the mailing (or closely related entity) was created or modified or deleted.',
  `scheduled_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Contact ID who scheduled this mailing',
  `scheduled_date` timestamp NULL DEFAULT NULL COMMENT 'Date and time this mailing was scheduled.',
  `approver_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Contact ID who approved this mailing',
  `approval_date` timestamp NULL DEFAULT NULL COMMENT 'Date and time this mailing was approved.',
  `approval_status_id` int(10) unsigned DEFAULT NULL COMMENT 'The status of this mailing. Values: none, approved, rejected',
  `approval_note` longtext COLLATE utf8_unicode_ci COMMENT 'Note behind the decision.',
  `is_archived` tinyint(4) DEFAULT '0' COMMENT 'Is this mailing archived?',
  `visibility` varchar(40) COLLATE utf8_unicode_ci DEFAULT 'Public Pages' COMMENT 'In what context(s) is the mailing contents visible (online viewing)',
  `campaign_id` int(10) unsigned DEFAULT NULL COMMENT 'The campaign for which this mailing has been initiated.',
  `dedupe_email` tinyint(4) DEFAULT '0' COMMENT 'Remove duplicate emails?',
  `sms_provider_id` int(10) unsigned DEFAULT NULL,
  `hash` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Key for validating requests related to this mailing.',
  `location_type_id` int(10) unsigned DEFAULT NULL COMMENT 'With email_selection_method, determines which email address to use',
  `email_selection_method` varchar(20) COLLATE utf8_unicode_ci DEFAULT 'automatic' COMMENT 'With location_type_id, determine how to choose the email address to use.',
  `language` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Language of the content of the mailing. Useful for tokens.',
  PRIMARY KEY (`id`),
  KEY `index_hash` (`hash`),
  KEY `FK_civicrm_mailing_domain_id` (`domain_id`),
  KEY `FK_civicrm_mailing_header_id` (`header_id`),
  KEY `FK_civicrm_mailing_footer_id` (`footer_id`),
  KEY `FK_civicrm_mailing_reply_id` (`reply_id`),
  KEY `FK_civicrm_mailing_unsubscribe_id` (`unsubscribe_id`),
  KEY `FK_civicrm_mailing_optout_id` (`optout_id`),
  KEY `FK_civicrm_mailing_msg_template_id` (`msg_template_id`),
  KEY `FK_civicrm_mailing_created_id` (`created_id`),
  KEY `FK_civicrm_mailing_scheduled_id` (`scheduled_id`),
  KEY `FK_civicrm_mailing_approver_id` (`approver_id`),
  KEY `FK_civicrm_mailing_campaign_id` (`campaign_id`),
  KEY `FK_civicrm_mailing_sms_provider_id` (`sms_provider_id`),
  KEY `FK_civicrm_mailing_location_type_id` (`location_type_id`),
  CONSTRAINT `FK_civicrm_mailing_approver_id` FOREIGN KEY (`approver_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_campaign_id` FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_created_id` FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_domain_id` FOREIGN KEY (`domain_id`) REFERENCES `civicrm_domain` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_footer_id` FOREIGN KEY (`footer_id`) REFERENCES `civicrm_mailing_component` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_header_id` FOREIGN KEY (`header_id`) REFERENCES `civicrm_mailing_component` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_location_type_id` FOREIGN KEY (`location_type_id`) REFERENCES `civicrm_location_type` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_msg_template_id` FOREIGN KEY (`msg_template_id`) REFERENCES `civicrm_msg_template` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_optout_id` FOREIGN KEY (`optout_id`) REFERENCES `civicrm_mailing_component` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_reply_id` FOREIGN KEY (`reply_id`) REFERENCES `civicrm_mailing_component` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_scheduled_id` FOREIGN KEY (`scheduled_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_sms_provider_id` FOREIGN KEY (`sms_provider_id`) REFERENCES `civicrm_sms_provider` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_unsubscribe_id` FOREIGN KEY (`unsubscribe_id`) REFERENCES `civicrm_mailing_component` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `civicrm_mailing` WRITE;
/*!40000 ALTER TABLE `civicrm_mailing` DISABLE KEYS */;
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (1,1,1,2,8,5,6,7,'Meeting Notes','standalone','FIXME','info@EXAMPLE.ORG','\"FIXME\" <info@EXAMPLE.ORG>','traditional','{\"nonce\":\"1\"}',NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-02-04 20:04:00','2018-02-04 20:04:32',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'b2f440363ad20332',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (2,1,1,2,8,5,6,7,NULL,'standalone','FIXME','info@EXAMPLE.ORG','\"FIXME\" <info@EXAMPLE.ORG>','traditional','{\"nonce\":\"1\"}',NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-02-12 05:01:03','2018-02-12 05:01:13',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'4ee23d7569435bb4',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (3,1,1,2,8,5,6,7,'Test','standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','test',NULL,'<p>test</p>',1,0,0,1,NULL,NULL,1,2,'2018-02-12 06:06:17','2018-02-12 06:06:45',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'e5e9a4bb737e4da2',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (4,1,NULL,NULL,NULL,NULL,NULL,NULL,'Twillio is WORKING',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Hey guys! I just set us up with a Twilio account so our CRM can send text messages to groups of people! If you got this, you are part of the \'Leadership\' group!',NULL,1,0,0,1,1,NULL,1,2,'2018-03-03 02:34:20','2018-03-03 22:20:27',2,'2018-03-03 21:25:47',2,'2018-03-03 21:25:47',1,NULL,0,'Public Pages',NULL,0,1,'19750c1c9e426da6',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (5,1,1,2,8,5,6,7,NULL,'standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}',NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-03-03 22:58:26','2018-03-03 22:58:33',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'61dced78aca03047',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (6,1,1,2,8,5,6,7,'Test','standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Sample CiviMail Newsletter',NULL,'<p>Hi Everyone!</p>\n\n<p>Just testing the message sending capability of CIVI CRM. If you received this message its because you are on the \'Leadership\' list.</p>\n\n<p>&nbsp; &nbsp; &nbsp; -Trailblazer</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-03 22:59:36','2018-03-03 23:03:41',2,'2018-03-03 23:03:41',2,'2018-03-03 23:03:41',1,NULL,0,'Public Pages',NULL,1,NULL,'9dcca3562f0ba2b1',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (7,1,1,2,8,5,6,7,'Test','standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Sample CiviMail Newsletter',NULL,'<p>Hi Everyone!</p>\n\n<p>Just testing the message sending capability of CIVI CRM. If you received this message its because you are on the \'Leadership\' list.</p>\n\n<p>&nbsp; &nbsp; &nbsp; -Trailblazer</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-03 23:19:29','2018-03-04 02:27:38',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'de36255471ce03c5',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (8,1,1,2,8,5,6,7,'Test','standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Sample CiviMail Newsletter',NULL,'<p>Hi Everyone!</p>\n\n<p>Just testing the message sending capability of CIVI CRM. If you received this message its because you are on the \'Leadership\' list.</p>\n\n<p>&nbsp; &nbsp; &nbsp; -Trailblazer</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-03 23:19:46','2018-03-03 23:19:59',2,'2018-03-03 23:19:59',2,'2018-03-03 23:19:59',1,NULL,0,'Public Pages',NULL,1,NULL,'2e30d2d2c85af2b0',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (9,1,NULL,NULL,NULL,NULL,NULL,NULL,'Camp Meeting',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Hi everyone! This is the official Mycodelic Forest SMS number! We will be using this for text notifications about camp meetings and other important things Burning Man related.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-04 05:03:41','2018-03-04 05:13:31',2,'2018-03-04 05:09:32',2,'2018-03-04 05:09:32',1,NULL,0,'Public Pages',NULL,0,1,'0d6edd5738acea8b',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (10,1,NULL,NULL,NULL,NULL,NULL,NULL,'Camp Meeting',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: We are having a camp meeting tomorrow, Sunday the 4th at 2PM. This will be a short meeting, we are just trying to asses the ticket situation and need to have some idea of how many tickets need to be bought in the main sale and who will be participating. Please text back to this number if you can\'t make it! We will send you an email summary of what is discussed! ',NULL,1,0,0,1,1,NULL,1,2,'2018-03-04 05:14:20','2018-03-04 05:21:44',2,'2018-03-04 05:21:24',2,'2018-03-04 05:21:24',1,NULL,0,'Public Pages',NULL,0,1,'2d30d0454f975149',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (11,1,1,2,8,5,6,7,NULL,'standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}',NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-03-04 05:23:59','2018-03-04 05:24:07',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'d5ab6166dc1ac7bd',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (12,1,NULL,NULL,NULL,NULL,NULL,NULL,'Meeting Instructions',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Camp Meeting at 2:00PM today, PST! This meeting will just to be discuss tickets and who is trying to camp with us! We will be using Google Meetups, so please make sure to download the app before hand. To join the video meeting, click this link: https://meet.google.com/gvx-qirk-mce',NULL,1,0,0,1,1,NULL,1,2,'2018-03-04 20:53:38','2018-03-18 19:51:05',2,'2018-03-04 21:03:49',2,'2018-03-04 21:03:49',1,NULL,0,'Public Pages',NULL,0,1,'3c42c07a3361462d',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (13,1,NULL,NULL,NULL,NULL,NULL,NULL,'Wrong link',NULL,'Mycodelic Forest No Reply','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-03-04 21:05:09','2018-03-04 21:05:09',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,0,NULL,'42d73b9b5e78d35f',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (14,1,1,2,8,5,6,7,NULL,'standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}',NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-03-05 05:17:33','2018-03-05 05:17:41',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'80068e0d958738fd',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (15,1,1,2,8,5,6,7,'Test','standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Sample CiviMail Newsletter',NULL,'<p>Hi Everyone!</p>\n\n<p>Just testing the message sending capability of CIVI CRM. If you received this message its because you are on the \'Leadership\' list.</p>\n\n<p>&nbsp; &nbsp; &nbsp; -Trailblazer</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-05 05:17:56','2018-03-05 05:18:18',2,'2018-03-05 05:18:18',2,'2018-03-05 05:18:18',1,NULL,0,'Public Pages',NULL,1,NULL,'25e601f10c2f355c',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (16,1,NULL,NULL,NULL,NULL,NULL,NULL,'Camp Meeting',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Just shooting out a reminder that we are trying to have a camp meeting this Sunday at 3PM! The main sale is coming up fast and we need to figure out everyone who is participating in it. Main Sale Registration starts this Wednesday, the 28th. If you are thinking about a getting at ticket, its now or never so please join us.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-17 03:10:43','2018-03-17 03:18:08',2,'2018-03-17 03:17:46',2,'2018-03-17 03:17:46',1,NULL,0,'Public Pages',NULL,0,1,'04c05e34202273eb',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (17,1,NULL,NULL,NULL,NULL,NULL,NULL,'Meeting Details',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Camp Meeting tomorrow! We will send you a link to join the google hangout. The topic: final camp roster and Main Sale tickets. We need to know who is IN this year for sure.  if you can’t come to the meeting, reply with your name and let us know you will be joining us on playa this year.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-17 22:27:45','2018-03-18 00:01:13',2,'2018-03-18 00:00:31',2,'2018-03-18 00:00:31',1,NULL,0,'Public Pages',NULL,0,1,'6384b2d8f8fd0815',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (18,1,NULL,NULL,NULL,NULL,NULL,NULL,'Camp Meeting Reminder 3/18/2018',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: We use Google Hangouts for our Camp Meetings so please use the link below to join at 3. This hangout is always active so there is no harm in joining early. Make sure to budget enough time to install the app. You can join VIA mobile or if you are running IOS 5 or less join a Desktop PC.\r\n\r\nTo join the video meeting, click this link: https://meet.google.com/gvx-qirk-mce',NULL,1,0,0,1,1,NULL,1,2,'2018-03-18 20:41:15','2018-03-18 21:04:12',2,'2018-03-18 21:03:37',2,'2018-03-18 21:03:37',1,NULL,0,'Public Pages',NULL,0,1,'e3620383319601e6',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (19,1,NULL,NULL,NULL,NULL,NULL,NULL,'Camp Meeting',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Camp meeting https://meet.google.com/gvx-qirk-mce',NULL,1,0,0,1,1,NULL,1,2,'2018-03-18 21:59:00','2018-03-18 22:01:09',2,'2018-03-18 22:00:11',2,'2018-03-18 22:00:11',1,NULL,0,'Public Pages',NULL,0,1,'cfcfe78e181438f4',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (20,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale Registration',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Burning Man Main Sale Info! Step 1: Create a burner profile. https://profiles.burningman.org/participate/register/ Step 2:  Register! Registration opens this Wednesday the 21st of March at Noon and you must register before Friday. If you have any additional questions, feel free to text this number.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-19 19:05:28','2018-03-19 19:33:09',2,'2018-03-19 19:32:23',2,'2018-03-19 19:32:23',1,NULL,0,'Public Pages',NULL,0,1,'9b786a86a5fa708a',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (21,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale Registration Opens',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Registration for the main sale is open! Register now at https://profiles.burningman.org/ through your Burner Profile and let us know when you did!',NULL,1,0,0,1,1,NULL,1,2,'2018-03-20 17:28:07','2018-03-21 19:00:11',2,'2018-03-21 19:00:00',2,'2018-03-20 17:31:42',1,NULL,0,'Public Pages',NULL,0,1,'9bb83e546f8c50ed',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (22,1,NULL,NULL,NULL,NULL,NULL,NULL,'Last Chance Main Sale',NULL,'Mycodelic Forest No Reply','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-03-23 17:43:16','2018-03-23 17:43:16',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,0,NULL,'e55171e2b0b7d293',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (23,1,NULL,NULL,NULL,NULL,NULL,NULL,'Last Chance Main Sale',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Last chance to register for the main sale! Registration closes today at NOON!',NULL,1,0,0,1,1,NULL,1,2,'2018-03-23 18:23:31','2018-03-23 18:24:10',2,'2018-03-23 18:24:00',2,'2018-03-23 18:24:00',1,NULL,0,'Public Pages',NULL,0,1,'3126568a0ef4c084',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (24,1,1,2,8,5,6,7,'Test Mailing','standalone','Mycodelic Forest No Reply','no-reply@mycodelicforest.org','\"Mycodelic Forest No Reply\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Test',NULL,'<p>test</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-27 05:29:20','2018-03-27 05:29:48',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,1,NULL,'86fe759933c7ed1f',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (25,1,1,2,8,5,6,7,'Main Sale Instructions','standalone','Mycodelic Forest','no-reply@mycodelicforest.org','\"Mycodelic Forest\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Burning Man Main Sale',NULL,'<p>Hey Everyone!</p>\n\n<p>The Main Sale is upon us! It will be happening this Wednesday, March 28th at Noon. For some of you, this may be your first ticket sale so I\'ve included some tips we\'ve learned along the way to help everyone. For those of you who know the ropes, feel free to skim! Tickets are VERY hard to get, and the Main Sale is is an entirely unique animal of ticket sale purchasing. We sell roughly 35,000 tickets in about 10 minutes.</p>\n\n<p>If you have registered for the Main Sale, you will get a registration link with instructions on how to buy your ticket on the morning of the sale. Or you can&nbsp;to log into your Burner Profile, and follow a link in the sidebar which should direct you to ticketfly where you can make your sale. After following the link, you will theoretically be put into a que which is basically a holding pen with a little green man that walks. You will sit in this holding pen until 12:00AM until the action happens. You will be able to buy two tickets and one car pass. ALWAYS BUY TWO TICKETS.&nbsp;</p>\n\n<p>1) Be prepared to have the morning off<br />\n2) Have a solid, reliable internet connection NO PHONES<br />\n3) Join our Google Hangout around 10:30AM, Its the same hangout we always use, but I will post the link.<br />\n4) Open your Ticket Invitation link around 11:00AM<br />\n5) Wait patiently<br />\n6) Let everyone know your ticket status as soon as possible<br />\n7) Always buy two tickets<br />\n8) Don\'t buy any more carpasses, we have a ton<br />\n9) Good Luck, and may the force be with you!<br />\n<br />\nIf you have ANY questions please a text at (415) 818-0287 or email me directly at trailblazer@mycodelicforest.org. (That phone number is for texting only, and is specific for our camp)<br />\n<br />\n&nbsp; &nbsp; &nbsp;- Trailblazer<br />\n&nbsp; &nbsp; &nbsp; &nbsp;Trevor Bice</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-27 05:31:49','2018-03-27 05:54:17',2,'2018-03-27 05:54:17',2,'2018-03-27 05:54:17',1,NULL,0,'Public Pages',NULL,1,NULL,'17186cdcc5a2cc43',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (26,1,1,2,8,5,6,7,'Main Sale Instructions','standalone','Mycodelic Forest','no-reply@mycodelicforest.org','\"Mycodelic Forest\" <no-reply@mycodelicforest.org>','traditional','{\"nonce\":\"1\"}','Burning Man Main Sale',NULL,'<p>Hey Everyone!</p>\n\n<p>The Main Sale is upon us! It will be happening this Wednesday, March 28th at Noon. For some of you, this may be your first ticket sale so I\'ve included some tips we\'ve learned along the way to help everyone. For those of you who know the ropes, feel free to skim! Tickets are VERY hard to get, and the Main Sale is is an entirely unique animal of ticket sale purchasing. We sell roughly 35,000 tickets in about 10 minutes.</p>\n\n<p>If you have registered for the Main Sale, you will get a registration link with instructions on how to buy your ticket on the morning of the sale. Or you can&nbsp;to log into your Burner Profile, and follow a link in the sidebar which should direct you to ticketfly where you can make your sale. After following the link, you will theoretically be put into a que which is basically a holding pen with a little green man that walks. You will sit in this holding pen until 12:00AM until the action happens. You will be able to buy two tickets and one car pass. ALWAYS BUY TWO TICKETS.&nbsp;</p>\n\n<p>1) Be prepared to have the morning off<br />\n2) Have a solid, reliable internet connection NO PHONES<br />\n3) Join our Google Hangout around 10:30AM, Its the same hangout we always use, but I will post the link.<br />\n4) Open your Ticket Invitation link around 11:00AM<br />\n5) Wait patiently<br />\n6) Let everyone know your ticket status as soon as possible<br />\n7) Always buy two tickets<br />\n8) Don\'t buy any more carpasses, we have a ton<br />\n9) Good Luck, and may the force be with you!<br />\n<br />\nIf you have ANY questions please a text at (415) 818-0287 or email me directly at trailblazer@mycodelicforest.org. (That phone number is for texting only, and is specific for our camp)<br />\n<br />\n&nbsp; &nbsp; &nbsp;- Trailblazer<br />\n&nbsp; &nbsp; &nbsp; &nbsp;Trevor Bice</p>',1,0,0,1,NULL,NULL,1,2,'2018-03-27 06:18:38','2018-03-27 06:20:29',2,'2018-03-27 06:22:00',2,'2018-03-27 06:20:29',1,NULL,0,'Public Pages',NULL,1,NULL,'13dd56c027d5ade7',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (27,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale Tomorrow',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: The Main Sale is tomorrow at Noon! If you are participating, you will want to be ready by 10:30AM with a reliable internet connection. You MUST have registered to participate in this sale.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-27 20:15:58','2018-03-27 20:20:07',2,'2018-03-27 20:19:06',2,'2018-03-27 20:19:06',1,NULL,0,'Public Pages',NULL,0,1,'fd708be934047342',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (28,1,NULL,NULL,NULL,NULL,NULL,NULL,'Why 1.5 hours before hand?',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Why 1.5 Hours Before Hand? \r\n\r\nWhen you open the purchase link before the sale, you are dropped into a que. Users are supposed to be randomly assigned numbers from this que when the sale opens -- but things have not always worked like that. In 2016 some users who were in that que wound up getting moved to the front of the line instead of getting a random number.\r\n\r\nWe recommend an abundance of caution.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-27 20:57:35','2018-03-27 20:58:04',2,'2018-03-27 20:58:00',2,'2018-03-27 20:58:00',1,NULL,0,'Public Pages',NULL,0,1,'088c32528a44f39a',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (29,1,NULL,NULL,NULL,NULL,NULL,NULL,'Pre Main sale',NULL,'Mycodelic Forest','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,NULL,NULL,1,0,0,1,NULL,NULL,1,2,'2018-03-28 16:09:30','2018-03-28 16:09:30',NULL,NULL,NULL,NULL,NULL,NULL,0,'Public Pages',NULL,0,NULL,'f095ae87d15c3ba3',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (30,1,NULL,NULL,NULL,NULL,NULL,NULL,'Pre Main Sale',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: The main sale is TODAY. Please use the link below to join our Group Chat between 1030 and 1100 so we can coordinate! https://meet.google.com/gvx-qirk-mce',NULL,1,0,0,1,1,NULL,1,2,'2018-03-28 16:59:00','2018-03-28 17:01:09',2,'2018-03-28 17:00:37',2,'2018-03-28 17:00:37',1,NULL,0,'Public Pages',NULL,0,1,'e33c4af58fab24e5',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (31,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale in one hour',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Main Sale in ONE hour.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-28 17:48:38','2018-03-28 17:50:05',2,'2018-03-28 17:49:34',2,'2018-03-28 17:49:34',1,NULL,0,'Public Pages',NULL,0,1,'540baad07e6ecf24',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (32,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale in 30 minutes',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Main Sale in 30 minutes!!!',NULL,1,0,0,1,1,NULL,1,2,'2018-03-28 17:50:08','2018-03-28 18:30:06',2,'2018-03-28 18:30:00',2,'2018-03-28 17:51:17',1,NULL,0,'Public Pages',NULL,0,1,'8d8d4df6bf6217e7',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (33,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale in 10 Minutes',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: 10 MINUTES!!! You should already have your Ticket Purchase link open! This would have been sent to the email listed in your Burner Profile.',NULL,1,0,0,1,1,NULL,1,2,'2018-03-28 17:51:46','2018-03-28 18:50:09',2,'2018-03-28 18:50:00',2,'2018-03-28 17:53:40',1,NULL,0,'Public Pages',NULL,0,1,'e6a818c68639ad85',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (34,1,NULL,NULL,NULL,NULL,NULL,NULL,'Main Sale NOW',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Good Luck! And may the Force be with you!',NULL,1,0,0,1,1,NULL,1,2,'2018-03-28 17:54:13','2018-03-28 19:01:05',2,'2018-03-28 19:00:27',2,'2018-03-28 19:00:27',1,NULL,0,'Public Pages',NULL,0,1,'cf8ddc19ff57901c',NULL,'automatic',NULL);
INSERT INTO `civicrm_mailing` (`id`, `domain_id`, `header_id`, `footer_id`, `reply_id`, `unsubscribe_id`, `resubscribe_id`, `optout_id`, `name`, `mailing_type`, `from_name`, `from_email`, `replyto_email`, `template_type`, `template_options`, `subject`, `body_text`, `body_html`, `url_tracking`, `forward_replies`, `auto_responder`, `open_tracking`, `is_completed`, `msg_template_id`, `override_verp`, `created_id`, `created_date`, `modified_date`, `scheduled_id`, `scheduled_date`, `approver_id`, `approval_date`, `approval_status_id`, `approval_note`, `is_archived`, `visibility`, `campaign_id`, `dedupe_email`, `sms_provider_id`, `hash`, `location_type_id`, `email_selection_method`, `language`) VALUES (35,1,NULL,NULL,NULL,NULL,NULL,NULL,'Leadership tickets',NULL,'AC7dab6b08735f18f6466332f2c5ee9293','no-reply@mycodelicforest.org','no-reply@mycodelicforest.org','traditional',NULL,NULL,'Mycodelic Forest: Camp Meeting in 15! Join link https://meet.google.com/gvx-qirk-mce',NULL,1,0,0,1,1,NULL,1,2,'2018-04-02 01:46:34','2018-04-02 01:50:04',2,'2018-04-02 01:49:16',2,'2018-04-02 01:49:16',1,NULL,0,'Public Pages',NULL,0,1,'29e59169a4c635ae',NULL,'automatic',NULL);
/*!40000 ALTER TABLE `civicrm_mailing` ENABLE KEYS */;
UNLOCK TABLES;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8 */ ;
/*!50003 SET character_set_results = utf8 */ ;
/*!50003 SET collation_connection  = utf8_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`trevorbi_mycode`@`localhost`*/ /*!50003 TRIGGER civicrm_mailing_before_insert before insert ON civicrm_mailing FOR EACH ROW BEGIN  
SET NEW.created_date = CURRENT_TIMESTAMP;
 END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

