
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `civicrm_currency`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `civicrm_currency` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Currency Id',
  `name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Currency Name',
  `symbol` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Currency Symbol',
  `numeric_code` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Numeric currency code',
  `full_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Full currency name',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=186 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `civicrm_currency` WRITE;
/*!40000 ALTER TABLE `civicrm_currency` DISABLE KEYS */;
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (1,'AUD','$','036','Australian Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (2,'CAD','$','124','Canadian Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (3,'EUR','€','978','Euro');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (4,'GBP','£','826','Pound Sterling');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (5,'ILS','₪','826','New Israeli Shekel');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (6,'INR','₨','356','Indian Rupee');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (7,'JPY','¥','392','Japanese Yen');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (8,'KRW','₩','410','South Korean Won');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (9,'LAK','₭','418','Lao Kip');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (10,'MNT','₮','496','Mongolian Tugrik');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (11,'NGN','₦','566','Nigerian Naira');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (12,'PLN','zł','985','Polish Złoty');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (13,'THB','฿','764','Thai Baht');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (14,'USD','$','840','US Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (15,'VND','₫','704','Viet Nam Dong');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (16,'ZAR','R','710','South African Rand');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (17,'AED',NULL,'784','UAE Dirham');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (18,'AFN','؋','971','Afghani');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (19,'ALL','Lek','008','Albanian Lek');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (20,'AMD',NULL,'051','Armenian Dram');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (21,'ANG','ƒ','532','Netherlands Antillian Guilder');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (22,'AOA',NULL,'973','Angola Kwanza');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (23,'ARS','$','032','Argentine Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (24,'AWG','ƒ','533','Aruban Guilder');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (25,'AZN','ман','944','Azerbaijanian Manat');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (26,'BAM','KM','977','Convertible Marks');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (27,'BBD','$','052','Barbados Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (28,'BDT',NULL,'050','Bangladeshi Taka');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (29,'BGN','лв','975','Bulgarian Lev');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (30,'BHD',NULL,'048','Bahraini Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (31,'BIF',NULL,'108','Burundi Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (32,'BMD','$','060','Bermudian Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (33,'BND','$','096','Brunei Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (34,'BOB','$b','068','Boliviano');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (35,'BOV',NULL,'984','Bolivian Mvdol');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (36,'BRL','R$','986','Brazilian Real');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (37,'BSD','$','044','Bahamian Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (38,'BTN',NULL,'064','Bhutan Ngultrum');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (39,'BWP','P','072','Botswana Pula');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (40,'BYR','p.','974','Belarussian Rouble');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (41,'BZD','BZ$','084','Belize Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (42,'CDF',NULL,'976','Franc Congolais');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (43,'CHE',NULL,'947','WIR Euro');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (44,'CHF','CHF','756','Swiss Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (45,'CHW',NULL,'948','WIR Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (46,'CLF',NULL,'990','Unidades de fomento');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (47,'CLP','$','152','Chilean Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (48,'CNY','元','156','Chinese Yuan Renminbi');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (49,'COP','$','170','Colombian Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (50,'COU',NULL,'970','Unidad de Valor Real');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (51,'CRC','₡','188','Costa Rican Colon');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (52,'RSD','Дин.','941','Serbian Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (53,'CUP','₱','192','Cuban Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (54,'CVE',NULL,'132','Cape Verde Escudo');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (55,'CYP','£','196','Cyprus Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (56,'CZK','Kč','203','Czech Koruna');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (57,'DJF',NULL,'262','Djibouti Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (58,'DKK','kr','208','Danish Krone');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (59,'DOP','RD$','214','Dominican Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (60,'DZD',NULL,'012','Algerian Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (62,'EGP','£','818','Egyptian Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (63,'ERN',NULL,'232','Eritrean Nakfa');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (64,'ETB',NULL,'230','Ethiopian Birr');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (65,'FJD','$','242','Fiji Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (66,'FKP','£','238','Falkland Islands Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (67,'GEL',NULL,'981','Georgian Lari');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (68,'GHC','¢','288','Ghanaian Cedi');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (69,'GIP','£','292','Gibraltar Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (70,'GMD',NULL,'270','Gambian Dalasi');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (71,'GNF',NULL,'324','Guinea Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (72,'GTQ','Q','320','Guatemalan Quetzal');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (73,'GWP',NULL,'624','Guinea-Bissau Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (74,'GYD','$','328','Guyana Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (75,'HKD','HK$','344','Hong Kong Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (76,'HNL','L','340','Honduran Lempira');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (77,'HRK','kn','191','Croatian Kuna');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (78,'HTG',NULL,'332','Haitian Gourde');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (79,'HUF','Ft','348','Hungarian Forint');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (80,'IDR','Rp','360','Indonesian Rupiah');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (81,'IQD',NULL,'368','Iraqi Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (82,'IRR','﷼','364','Iranian Rial');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (83,'ISK','kr','352','Iceland Krona');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (84,'JMD','J$','388','Jamaican Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (85,'JOD',NULL,'400','Jordanian Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (86,'KES',NULL,'404','Kenyan Shilling');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (87,'KGS','лв','417','Kyrgyzstan Som');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (88,'KHR','៛','116','Cambodian Riel');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (89,'KMF',NULL,'174','Comoro Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (90,'KPW','₩','408','North Korean Won');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (91,'KWD',NULL,'414','Kuwaiti Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (92,'KYD','$','136','Cayman Islands Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (93,'KZT','лв','398','Kazakhstan Tenge');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (94,'LBP','£','422','Lebanese Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (95,'LKR','₨','144','Sri Lanka Rupee');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (96,'LRD','$','430','Liberian Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (97,'LSL',NULL,'426','Lesotho Loti');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (98,'LTL','Lt','440','Lithuanian Litas');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (99,'LVL','Ls','428','Latvian Lats');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (100,'LYD',NULL,'434','Libyan Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (101,'MAD',NULL,'504','Moroccan Dirham');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (102,'MDL',NULL,'498','Moldovan Leu');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (103,'MGA',NULL,'969','Malagascy Ariary');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (104,'MKD','ден','807','Macedonian Denar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (105,'MMK',NULL,'104','Myanmar Kyat');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (106,'MOP',NULL,'446','Macao Pataca');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (107,'MRO',NULL,'478','Mauritanian Ouguiya');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (108,'MTL','Lm','470','Maltese Lira');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (109,'MUR','₨','480','Mauritius Rupee');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (110,'MVR',NULL,'462','Maldive Rufiyaa');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (111,'MWK',NULL,'454','Malawi Kwacha');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (112,'MXN','$','484','Mexican Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (113,'MXV',NULL,'979','Mexican Unidad de Inversion (UID)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (114,'MYR','RM','458','Malaysian Ringgit');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (115,'MZN','MT','943','Mozambique Metical');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (116,'NAD','N$','516','Namibian Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (117,'NIO','C$','558','Nicaraguan Cordoba Oro');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (118,'NOK','kr','578','Norwegian Krone');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (119,'NPR','₨','524','Nepalese Rupee');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (120,'NZD','$','554','New Zealand Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (121,'OMR','﷼','512','Rial Omani');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (122,'PAB','B/.','590','Panamanian Balboa');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (123,'PEN','S/.','604','Peruvian Nuevo Sol');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (124,'PGK',NULL,'598','Papua New Guinea Kina');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (125,'PHP','Php','608','Philippine Peso');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (126,'PKR','₨','586','Pakistan Rupee');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (127,'PYG','Gs','600','Paraguay Guarani');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (128,'QAR','﷼','634','Qatari Rial');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (129,'ROL',NULL,'642','Romanian Old Leu');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (130,'RON','lei','946','Romanian New Leu');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (131,'RUB','руб','643','Russian Rouble');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (132,'RWF',NULL,'646','Rwanda Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (133,'SAR','﷼','682','Saudi Riyal');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (134,'SBD','$','090','Solomon Islands Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (135,'SCR','₨','690','Seychelles Rupee');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (136,'SDD',NULL,'736','Sudanese Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (137,'SEK','kr','752','Swedish Krona');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (138,'SGD','$','702','Singapore Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (139,'SHP','£','654','Saint Helena Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (140,'SIT',NULL,'705','Slovenian Tolar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (141,'SKK','SIT','703','Slovak Koruna');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (142,'SLL',NULL,'694','Leone');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (143,'SOS','S','706','Somali Shilling');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (144,'SRD','$','968','Surinam Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (145,'STD',NULL,'678','São Tome and Principe Dobra');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (146,'SVC','$','222','El Salvador Colon');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (147,'SYP','£','760','Syrian Pound');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (148,'SZL',NULL,'748','Swaziland Lilangeni');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (149,'TJS',NULL,'972','Tajik Somoni');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (150,'TMM',NULL,'795','Turkmenistan Manat');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (151,'TND',NULL,'788','Tunisian Dinar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (152,'TOP',NULL,'776','Tongan Pa\'anga');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (153,'TRY','YTL','949','New Turkish Lira');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (154,'TTD','TT$','780','Trinidad and Tobago Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (155,'TWD','NT$','901','New Taiwan Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (156,'TZS',NULL,'834','Tanzanian Shilling');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (157,'UAH','₴','980','Ukrainian Hryvnia');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (158,'UGX',NULL,'800','Ugandan Shilling');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (159,'USN',NULL,'997','US Dollar (Next day)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (160,'USS',NULL,'998','US Dollar (Same day)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (161,'UYU','$U','858','Peso Uruguayo');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (162,'UZS','лв','860','Uzbekistan Sum');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (163,'VEF','Bs','937','Venezuela Bolivar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (164,'VUV',NULL,'548','Vanuatu Vatu');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (165,'WST',NULL,'882','Samoan Tala');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (166,'XAF',NULL,'950','CFA Franc BEAC');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (167,'XAG',NULL,'961','Silver');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (168,'XAU',NULL,'959','Gold');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (169,'XBA',NULL,'955','Bond Markets Units European Composite Unit (EURCO)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (170,'XBB',NULL,'956','European Monetary Unit (E.M.U.-6)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (171,'XBC',NULL,'957','European Unit of Account 9 (E.U.A.-9)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (172,'XBD',NULL,'958','European Unit of Account 17 (E.U.A.-17)');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (173,'XCD','$','951','East Caribbean Dollar');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (174,'XDR',NULL,'960','Special Drawing Right');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (175,'XFO',NULL,NULL,'Gold-Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (176,'XFU',NULL,NULL,'UIC-Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (177,'XOF',NULL,'952','CFA Franc BCEAO');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (178,'XPD',NULL,'964','Palladium');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (179,'XPF',NULL,'953','CFP Franc');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (180,'XPT',NULL,'962','Platinum');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (181,'XTS',NULL,'963','Code for testing purposes');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (182,'XXX',NULL,'999','No currency involved');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (183,'YER','﷼','886','Yemeni Rial');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (184,'ZMK',NULL,'894','Zambian Kwacha');
INSERT INTO `civicrm_currency` (`id`, `name`, `symbol`, `numeric_code`, `full_name`) VALUES (185,'ZWD','Z$','716','Zimbabwe Dollar');
/*!40000 ALTER TABLE `civicrm_currency` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

