
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `civicrm_mailing_recipients`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `civicrm_mailing_recipients` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mailing_id` int(10) unsigned NOT NULL COMMENT 'The ID of the mailing this Job will send.',
  `contact_id` int(10) unsigned NOT NULL COMMENT 'FK to Contact',
  `email_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Email',
  `phone_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Phone',
  PRIMARY KEY (`id`),
  KEY `FK_civicrm_mailing_recipients_mailing_id` (`mailing_id`),
  KEY `FK_civicrm_mailing_recipients_contact_id` (`contact_id`),
  KEY `FK_civicrm_mailing_recipients_email_id` (`email_id`),
  KEY `FK_civicrm_mailing_recipients_phone_id` (`phone_id`),
  CONSTRAINT `FK_civicrm_mailing_recipients_contact_id` FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_civicrm_mailing_recipients_email_id` FOREIGN KEY (`email_id`) REFERENCES `civicrm_email` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_mailing_recipients_mailing_id` FOREIGN KEY (`mailing_id`) REFERENCES `civicrm_mailing` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_civicrm_mailing_recipients_phone_id` FOREIGN KEY (`phone_id`) REFERENCES `civicrm_phone` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=1213 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `civicrm_mailing_recipients` WRITE;
/*!40000 ALTER TABLE `civicrm_mailing_recipients` DISABLE KEYS */;
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (52,6,2,2,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (53,6,3,3,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (54,6,4,4,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (55,6,11,11,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (56,6,26,25,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (97,8,2,2,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (98,8,3,3,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (99,8,4,4,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (100,8,11,11,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (101,8,26,25,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (122,4,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (123,4,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (124,4,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (125,4,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (126,4,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (242,9,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (243,9,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (244,9,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (245,9,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (246,9,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (247,9,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (248,9,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (249,9,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (250,9,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (251,9,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (252,9,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (253,9,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (254,9,66,NULL,15);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (255,9,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (256,9,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (257,9,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (258,9,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (259,10,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (260,10,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (261,10,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (262,10,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (263,10,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (264,10,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (265,10,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (266,10,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (267,10,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (268,10,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (269,10,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (270,10,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (271,10,66,NULL,15);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (272,10,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (273,10,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (274,10,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (275,10,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (276,12,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (277,12,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (278,12,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (279,12,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (280,12,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (281,12,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (282,12,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (283,12,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (284,12,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (285,12,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (286,12,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (287,12,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (288,12,66,NULL,15);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (289,12,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (290,12,77,NULL,22);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (291,12,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (292,12,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (293,12,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (294,13,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (295,13,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (296,13,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (297,13,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (298,13,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (299,13,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (300,13,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (301,13,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (302,13,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (303,13,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (304,13,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (305,13,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (306,13,66,NULL,15);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (307,13,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (308,13,77,NULL,22);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (309,13,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (310,13,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (311,13,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (322,15,2,2,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (323,15,3,3,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (324,15,4,4,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (325,15,11,11,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (326,15,26,25,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (352,16,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (353,16,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (354,16,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (355,16,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (356,16,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (357,16,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (358,16,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (359,16,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (360,16,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (361,16,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (362,16,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (363,16,28,NULL,24);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (364,16,43,NULL,26);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (365,16,45,NULL,28);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (366,16,47,NULL,13);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (367,16,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (368,16,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (369,16,66,NULL,15);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (370,16,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (371,16,77,NULL,22);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (372,16,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (373,16,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (374,16,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (375,16,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (376,16,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (429,17,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (430,17,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (431,17,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (432,17,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (433,17,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (434,17,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (435,17,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (436,17,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (437,17,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (438,17,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (439,17,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (440,17,28,NULL,24);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (441,17,43,NULL,26);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (442,17,45,NULL,28);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (443,17,47,NULL,13);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (444,17,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (445,17,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (446,17,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (447,17,64,NULL,31);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (448,17,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (449,17,77,NULL,22);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (450,17,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (451,17,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (452,17,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (453,17,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (454,17,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (523,18,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (524,18,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (525,18,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (526,18,5,NULL,7);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (527,18,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (528,18,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (529,18,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (530,18,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (531,18,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (532,18,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (533,18,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (534,18,28,NULL,24);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (535,18,43,NULL,26);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (536,18,45,NULL,28);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (537,18,47,NULL,13);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (538,18,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (539,18,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (540,18,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (541,18,64,NULL,31);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (542,18,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (543,18,77,NULL,22);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (544,18,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (545,18,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (546,18,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (547,18,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (548,18,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (549,18,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (550,18,98,NULL,33);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (635,20,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (636,20,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (637,20,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (638,20,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (639,20,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (640,20,20,NULL,37);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (641,20,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (642,20,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (643,20,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (644,20,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (645,20,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (646,20,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (647,20,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (648,20,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (649,20,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (665,21,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (666,21,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (667,21,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (668,21,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (669,21,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (670,21,20,NULL,37);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (671,21,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (672,21,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (673,21,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (674,21,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (675,21,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (676,21,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (677,21,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (678,21,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (679,21,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (680,22,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (681,22,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (682,22,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (683,22,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (684,22,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (685,22,20,NULL,37);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (686,22,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (687,22,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (688,22,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (689,22,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (690,22,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (691,22,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (692,22,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (693,22,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (694,22,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (710,23,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (711,23,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (712,23,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (713,23,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (714,23,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (715,23,20,NULL,37);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (716,23,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (717,23,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (718,23,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (719,23,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (720,23,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (721,23,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (722,23,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (723,23,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (724,23,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (725,24,2,2,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (726,24,3,3,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (727,24,4,4,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (728,24,11,11,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (729,24,26,25,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (796,25,2,2,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (797,25,3,3,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (798,25,4,4,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (799,25,11,11,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (800,25,12,12,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (801,25,20,34,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (802,25,26,25,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (803,25,68,31,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (804,25,81,35,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (805,25,86,37,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (806,25,88,40,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (807,25,97,42,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (808,25,99,43,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (809,25,100,45,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (880,26,2,2,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (881,26,3,3,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (882,26,4,4,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (883,26,11,11,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (884,26,12,12,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (885,26,20,34,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (886,26,26,25,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (887,26,68,31,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (888,26,81,35,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (889,26,86,37,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (890,26,88,40,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (891,26,97,42,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (892,26,99,43,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (893,26,100,45,NULL);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (964,27,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (965,27,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (966,27,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (967,27,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (968,27,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (969,27,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (970,27,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (971,27,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (972,27,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (973,27,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (974,27,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (975,27,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (976,27,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (990,28,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (991,28,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (992,28,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (993,28,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (994,28,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (995,28,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (996,28,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (997,28,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (998,28,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (999,28,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1000,28,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1001,28,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1002,28,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1003,29,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1004,29,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1005,29,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1006,29,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1007,29,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1008,29,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1009,29,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1010,29,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1011,29,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1012,29,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1013,29,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1014,29,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1015,29,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1029,30,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1030,30,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1031,30,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1032,30,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1033,30,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1034,30,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1035,30,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1036,30,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1037,30,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1038,30,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1039,30,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1040,30,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1041,30,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1055,31,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1056,31,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1057,31,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1058,31,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1059,31,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1060,31,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1061,31,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1062,31,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1063,31,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1064,31,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1065,31,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1066,31,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1067,31,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1094,32,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1095,32,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1096,32,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1097,32,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1098,32,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1099,32,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1100,32,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1101,32,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1102,32,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1103,32,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1104,32,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1105,32,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1106,32,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1120,33,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1121,33,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1122,33,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1123,33,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1124,33,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1125,33,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1126,33,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1127,33,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1128,33,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1129,33,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1130,33,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1131,33,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1132,33,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1159,34,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1160,34,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1161,34,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1162,34,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1163,34,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1164,34,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1165,34,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1166,34,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1167,34,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1168,34,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1169,34,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1170,34,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1171,34,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1177,19,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1178,19,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1179,19,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1180,19,6,NULL,4);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1181,19,7,NULL,12);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1182,19,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1183,19,12,NULL,29);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1184,19,13,NULL,19);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1185,19,20,NULL,37);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1186,19,23,NULL,20);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1187,19,26,NULL,9);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1188,19,28,NULL,24);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1189,19,43,NULL,26);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1190,19,51,NULL,32);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1191,19,55,NULL,18);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1192,19,56,NULL,11);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1193,19,64,NULL,31);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1194,19,68,NULL,10);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1195,19,77,NULL,22);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1196,19,80,NULL,21);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1197,19,81,NULL,16);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1198,19,85,NULL,17);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1199,19,86,NULL,23);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1200,19,88,NULL,25);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1201,19,95,NULL,36);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1202,19,97,NULL,30);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1203,19,99,NULL,34);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1204,19,100,NULL,38);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1205,19,102,NULL,39);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1206,19,103,NULL,40);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1207,19,104,NULL,41);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1208,35,2,NULL,3);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1209,35,3,NULL,2);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1210,35,4,NULL,1);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1211,35,11,NULL,5);
INSERT INTO `civicrm_mailing_recipients` (`id`, `mailing_id`, `contact_id`, `email_id`, `phone_id`) VALUES (1212,35,26,NULL,9);
/*!40000 ALTER TABLE `civicrm_mailing_recipients` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

