
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `civicrm_group`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `civicrm_group` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Group ID',
  `name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Internal name of Group.',
  `title` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Name of Group.',
  `description` text COLLATE utf8_unicode_ci COMMENT 'Optional verbose description of the group.',
  `source` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Module or process which created this group.',
  `saved_search_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to saved search table.',
  `is_active` tinyint(4) DEFAULT NULL COMMENT 'Is this entry active?',
  `visibility` varchar(24) COLLATE utf8_unicode_ci DEFAULT 'User and User Admin Only' COMMENT 'In what context(s) is this field visible.',
  `where_clause` text COLLATE utf8_unicode_ci COMMENT 'the sql where clause if a saved search acl',
  `select_tables` text COLLATE utf8_unicode_ci COMMENT 'the tables to be included in a select data',
  `where_tables` text COLLATE utf8_unicode_ci COMMENT 'the tables to be included in the count statement',
  `group_type` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'FK to group type',
  `cache_date` timestamp NULL DEFAULT NULL COMMENT 'Date when we created the cache for a smart group',
  `refresh_date` timestamp NULL DEFAULT NULL COMMENT 'Date and time when we need to refresh the cache next.',
  `parents` text COLLATE utf8_unicode_ci COMMENT 'IDs of the parent(s)',
  `children` text COLLATE utf8_unicode_ci COMMENT 'IDs of the child(ren)',
  `is_hidden` tinyint(4) DEFAULT '0' COMMENT 'Is this group hidden?',
  `is_reserved` tinyint(4) DEFAULT '0',
  `created_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to contact table.',
  `modified_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to contact table.',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UI_title` (`title`),
  UNIQUE KEY `UI_name` (`name`),
  KEY `index_group_type` (`group_type`),
  KEY `FK_civicrm_group_saved_search_id` (`saved_search_id`),
  KEY `FK_civicrm_group_created_id` (`created_id`),
  KEY `FK_civicrm_group_modified_id` (`modified_id`),
  CONSTRAINT `FK_civicrm_group_created_id` FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_group_modified_id` FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_civicrm_group_saved_search_id` FOREIGN KEY (`saved_search_id`) REFERENCES `civicrm_saved_search` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `civicrm_group` WRITE;
/*!40000 ALTER TABLE `civicrm_group` DISABLE KEYS */;
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (1,'DGS_1','DGS',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-1`.group_id IN ( 1 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-1`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-1` ON (contact_a.id = `civicrm_group_contact-1`.contact_id AND `civicrm_group_contact-1`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-1`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-1` ON (contact_a.id = `civicrm_group_contact-1`.contact_id AND `civicrm_group_contact-1`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,1,2,2);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (2,'DGS_Maybe_2','DGS Maybe','For contacts who might be interested in participating DGS, but have not yet been confirmed.',NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-2`.group_id IN ( 2 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-2`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-2` ON (contact_a.id = `civicrm_group_contact-2`.contact_id AND `civicrm_group_contact-2`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-2`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-2` ON (contact_a.id = `civicrm_group_contact-2`.contact_id AND `civicrm_group_contact-2`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (3,'Trevor_Bice_Invitations_3','Trevor Bice Invitations',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-3`.group_id IN ( 3 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-3`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-3` ON (contact_a.id = `civicrm_group_contact-3`.contact_id AND `civicrm_group_contact-3`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-3`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-3` ON (contact_a.id = `civicrm_group_contact-3`.contact_id AND `civicrm_group_contact-3`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (4,'Main_Sale_4','Main Sale','Anyone participating in the Mail Sale.',NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-4`.group_id IN ( 4 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-4`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-4` ON (contact_a.id = `civicrm_group_contact-4`.contact_id AND `civicrm_group_contact-4`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-4`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-4` ON (contact_a.id = `civicrm_group_contact-4`.contact_id AND `civicrm_group_contact-4`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (5,'Gift_Tickets_5','Gift Tickets',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-5`.group_id IN ( 5 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-5`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-5` ON (contact_a.id = `civicrm_group_contact-5`.contact_id AND `civicrm_group_contact-5`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-5`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-5` ON (contact_a.id = `civicrm_group_contact-5`.contact_id AND `civicrm_group_contact-5`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (6,'Mycodelic_forest_6','Mycodelic forest',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-6`.group_id IN ( 6 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-6`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-6` ON (contact_a.id = `civicrm_group_contact-6`.contact_id AND `civicrm_group_contact-6`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-6`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-6` ON (contact_a.id = `civicrm_group_contact-6`.contact_id AND `civicrm_group_contact-6`.status IN (\'Added\'))\";}','',NULL,NULL,NULL,NULL,0,0,NULL,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (7,'Newbies_7','Newbies',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-7`.group_id IN ( 7 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-7`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-7` ON (contact_a.id = `civicrm_group_contact-7`.contact_id AND `civicrm_group_contact-7`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-7`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-7` ON (contact_a.id = `civicrm_group_contact-7`.contact_id AND `civicrm_group_contact-7`.status IN (\'Added\'))\";}','',NULL,NULL,NULL,NULL,0,1,3,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (8,'Low_Income_8','Low Income Applicants',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-8`.group_id IN ( 8 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-8`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-8` ON (contact_a.id = `civicrm_group_contact-8`.contact_id AND `civicrm_group_contact-8`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-8`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-8` ON (contact_a.id = `civicrm_group_contact-8`.contact_id AND `civicrm_group_contact-8`.status IN (\'Added\'))\";}','',NULL,NULL,NULL,NULL,0,1,3,2);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (9,'BM_2018_9','BM 2018','I Robot',NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-9`.group_id IN ( 9 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:25:\"`civicrm_group_contact-9`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-9` ON (contact_a.id = `civicrm_group_contact-9`.contact_id AND `civicrm_group_contact-9`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:25:\"`civicrm_group_contact-9`\";s:165:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-9` ON (contact_a.id = `civicrm_group_contact-9`.contact_id AND `civicrm_group_contact-9`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,11,2);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (10,'BM_2018_Maybe_10','BM 2018 Maybe',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-10`.group_id IN ( 10 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:26:\"`civicrm_group_contact-10`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-10` ON (contact_a.id = `civicrm_group_contact-10`.contact_id AND `civicrm_group_contact-10`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:26:\"`civicrm_group_contact-10`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-10` ON (contact_a.id = `civicrm_group_contact-10`.contact_id AND `civicrm_group_contact-10`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,2);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (11,'Leadership_11','Leadership',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-11`.group_id IN ( 11 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:26:\"`civicrm_group_contact-11`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-11` ON (contact_a.id = `civicrm_group_contact-11`.contact_id AND `civicrm_group_contact-11`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:26:\"`civicrm_group_contact-11`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-11` ON (contact_a.id = `civicrm_group_contact-11`.contact_id AND `civicrm_group_contact-11`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,2);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (12,'BME_2018_Maybe_No_12','BME 2018 (Maybe) No',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-12`.group_id IN ( 12 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:26:\"`civicrm_group_contact-12`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-12` ON (contact_a.id = `civicrm_group_contact-12`.contact_id AND `civicrm_group_contact-12`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:26:\"`civicrm_group_contact-12`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-12` ON (contact_a.id = `civicrm_group_contact-12`.contact_id AND `civicrm_group_contact-12`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,NULL);
INSERT INTO `civicrm_group` (`id`, `name`, `title`, `description`, `source`, `saved_search_id`, `is_active`, `visibility`, `where_clause`, `select_tables`, `where_tables`, `group_type`, `cache_date`, `refresh_date`, `parents`, `children`, `is_hidden`, `is_reserved`, `created_id`, `modified_id`) VALUES (13,'Twilio_13','Twilio',NULL,NULL,NULL,1,'User and User Admin Only',' (  ( ( `civicrm_group_contact-13`.group_id IN ( 13 )  ) )  ) ','a:8:{s:15:\"civicrm_contact\";i:1;s:15:\"civicrm_address\";i:1;s:15:\"civicrm_country\";i:1;s:13:\"civicrm_email\";i:1;s:13:\"civicrm_phone\";i:1;s:10:\"civicrm_im\";i:1;s:19:\"civicrm_worldregion\";i:1;s:26:\"`civicrm_group_contact-13`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-13` ON (contact_a.id = `civicrm_group_contact-13`.contact_id AND `civicrm_group_contact-13`.status IN (\'Added\'))\";}','a:2:{s:15:\"civicrm_contact\";i:1;s:26:\"`civicrm_group_contact-13`\";s:168:\" LEFT JOIN civicrm_group_contact `civicrm_group_contact-13` ON (contact_a.id = `civicrm_group_contact-13`.contact_id AND `civicrm_group_contact-13`.status IN (\'Added\'))\";}','2',NULL,NULL,NULL,NULL,0,0,2,NULL);
/*!40000 ALTER TABLE `civicrm_group` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

