
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `civicrm_country`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `civicrm_country` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Country Id',
  `name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Country Name',
  `iso_code` char(2) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'ISO Code',
  `country_code` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'National prefix to be used when dialing TO this country.',
  `address_format_id` int(10) unsigned DEFAULT NULL COMMENT 'Foreign key to civicrm_address_format.id.',
  `idd_prefix` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'International direct dialing prefix from within the country TO another country',
  `ndd_prefix` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Access prefix to call within a country to a different area',
  `region_id` int(10) unsigned NOT NULL COMMENT 'Foreign key to civicrm_worldregion.id.',
  `is_province_abbreviated` tinyint(4) DEFAULT '0' COMMENT 'Should state/province be displayed as abbreviation for contacts from this country?',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UI_name_iso_code` (`name`,`iso_code`),
  KEY `FK_civicrm_country_address_format_id` (`address_format_id`),
  KEY `FK_civicrm_country_region_id` (`region_id`),
  CONSTRAINT `FK_civicrm_country_address_format_id` FOREIGN KEY (`address_format_id`) REFERENCES `civicrm_address_format` (`id`),
  CONSTRAINT `FK_civicrm_country_region_id` FOREIGN KEY (`region_id`) REFERENCES `civicrm_worldregion` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1254 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `civicrm_country` WRITE;
/*!40000 ALTER TABLE `civicrm_country` DISABLE KEYS */;
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1001,'Afghanistan','AF',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1002,'Albania','AL',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1003,'Algeria','DZ',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1004,'American Samoa','AS',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1005,'Andorra','AD',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1006,'Angola','AO',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1007,'Anguilla','AI',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1008,'Antarctica','AQ',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1009,'Antigua and Barbuda','AG',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1010,'Argentina','AR',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1011,'Armenia','AM',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1012,'Aruba','AW',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1013,'Australia','AU',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1014,'Austria','AT',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1015,'Azerbaijan','AZ',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1016,'Bahrain','BH',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1017,'Bangladesh','BD',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1018,'Barbados','BB',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1019,'Belarus','BY',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1020,'Belgium','BE',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1021,'Belize','BZ',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1022,'Benin','BJ',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1023,'Bermuda','BM',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1024,'Bhutan','BT',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1025,'Bolivia','BO',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1026,'Bosnia and Herzegovina','BA',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1027,'Botswana','BW',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1028,'Bouvet Island','BV',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1029,'Brazil','BR',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1030,'British Indian Ocean Territory','IO',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1031,'Virgin Islands, British','VG',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1032,'Brunei Darussalam','BN',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1033,'Bulgaria','BG',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1034,'Burkina Faso','BF',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1035,'Myanmar','MM',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1036,'Burundi','BI',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1037,'Cambodia','KH',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1038,'Cameroon','CM',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1039,'Canada','CA',NULL,NULL,NULL,NULL,2,1);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1040,'Cape Verde','CV',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1041,'Cayman Islands','KY',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1042,'Central African Republic','CF',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1043,'Chad','TD',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1044,'Chile','CL',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1045,'China','CN',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1046,'Christmas Island','CX',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1047,'Cocos (Keeling) Islands','CC',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1048,'Colombia','CO',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1049,'Comoros','KM',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1050,'Congo, The Democratic Republic of the','CD',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1051,'Congo, Republic of the','CG',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1052,'Cook Islands','CK',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1053,'Costa Rica','CR',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1054,'Côte d’Ivoire','CI',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1055,'Croatia','HR',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1056,'Cuba','CU',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1057,'Cyprus','CY',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1058,'Czech Republic','CZ',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1059,'Denmark','DK',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1060,'Djibouti','DJ',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1061,'Dominica','DM',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1062,'Dominican Republic','DO',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1063,'Timor-Leste','TL',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1064,'Ecuador','EC',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1065,'Egypt','EG',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1066,'El Salvador','SV',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1067,'Equatorial Guinea','GQ',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1068,'Eritrea','ER',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1069,'Estonia','EE',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1070,'Ethiopia','ET',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1072,'Falkland Islands (Malvinas)','FK',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1073,'Faroe Islands','FO',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1074,'Fiji','FJ',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1075,'Finland','FI',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1076,'France','FR',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1077,'French Guiana','GF',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1078,'French Polynesia','PF',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1079,'French Southern Territories','TF',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1080,'Gabon','GA',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1081,'Georgia','GE',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1082,'Germany','DE',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1083,'Ghana','GH',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1084,'Gibraltar','GI',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1085,'Greece','GR',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1086,'Greenland','GL',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1087,'Grenada','GD',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1088,'Guadeloupe','GP',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1089,'Guam','GU',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1090,'Guatemala','GT',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1091,'Guinea','GN',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1092,'Guinea-Bissau','GW',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1093,'Guyana','GY',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1094,'Haiti','HT',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1095,'Heard Island and McDonald Islands','HM',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1096,'Holy See (Vatican City State)','VA',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1097,'Honduras','HN',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1098,'Hong Kong','HK',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1099,'Hungary','HU',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1100,'Iceland','IS',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1101,'India','IN',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1102,'Indonesia','ID',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1103,'Iran, Islamic Republic Of','IR',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1104,'Iraq','IQ',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1105,'Ireland','IE',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1106,'Israel','IL',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1107,'Italy','IT',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1108,'Jamaica','JM',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1109,'Japan','JP',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1110,'Jordan','JO',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1111,'Kazakhstan','KZ',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1112,'Kenya','KE',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1113,'Kiribati','KI',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1114,'Korea, Democratic People\'s Republic of','KP',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1115,'Korea, Republic of','KR',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1116,'Kuwait','KW',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1117,'Kyrgyzstan','KG',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1118,'Lao People\'s Democratic Republic','LA',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1119,'Latvia','LV',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1120,'Lebanon','LB',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1121,'Lesotho','LS',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1122,'Liberia','LR',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1123,'Libya','LY',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1124,'Liechtenstein','LI',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1125,'Lithuania','LT',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1126,'Luxembourg','LU',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1127,'Macao','MO',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1128,'Macedonia, Republic Of','MK',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1129,'Madagascar','MG',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1130,'Malawi','MW',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1131,'Malaysia','MY',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1132,'Maldives','MV',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1133,'Mali','ML',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1134,'Malta','MT',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1135,'Marshall Islands','MH',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1136,'Martinique','MQ',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1137,'Mauritania','MR',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1138,'Mauritius','MU',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1139,'Mayotte','YT',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1140,'Mexico','MX',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1141,'Micronesia, Federated States of','FM',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1142,'Moldova','MD',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1143,'Monaco','MC',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1144,'Mongolia','MN',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1145,'Montserrat','MS',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1146,'Morocco','MA',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1147,'Mozambique','MZ',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1148,'Namibia','NA',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1149,'Nauru','NR',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1150,'Nepal','NP',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1152,'Netherlands','NL',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1153,'New Caledonia','NC',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1154,'New Zealand','NZ',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1155,'Nicaragua','NI',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1156,'Niger','NE',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1157,'Nigeria','NG',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1158,'Niue','NU',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1159,'Norfolk Island','NF',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1160,'Northern Mariana Islands','MP',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1161,'Norway','NO',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1162,'Oman','OM',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1163,'Pakistan','PK',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1164,'Palau','PW',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1165,'Palestine, State of','PS',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1166,'Panama','PA',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1167,'Papua New Guinea','PG',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1168,'Paraguay','PY',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1169,'Peru','PE',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1170,'Philippines','PH',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1171,'Pitcairn','PN',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1172,'Poland','PL',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1173,'Portugal','PT',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1174,'Puerto Rico','PR',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1175,'Qatar','QA',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1176,'Romania','RO',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1177,'Russian Federation','RU',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1178,'Rwanda','RW',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1179,'Reunion','RE',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1180,'Saint Helena','SH',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1181,'Saint Kitts and Nevis','KN',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1182,'Saint Lucia','LC',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1183,'Saint Pierre and Miquelon','PM',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1184,'Saint Vincent and the Grenadines','VC',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1185,'Samoa','WS',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1186,'San Marino','SM',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1187,'Saudi Arabia','SA',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1188,'Senegal','SN',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1189,'Seychelles','SC',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1190,'Sierra Leone','SL',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1191,'Singapore','SG',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1192,'Slovakia','SK',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1193,'Slovenia','SI',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1194,'Solomon Islands','SB',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1195,'Somalia','SO',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1196,'South Africa','ZA',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1197,'South Georgia and the South Sandwich Islands','GS',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1198,'Spain','ES',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1199,'Sri Lanka','LK',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1200,'Sudan','SD',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1201,'Suriname','SR',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1202,'Svalbard and Jan Mayen','SJ',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1203,'Swaziland','SZ',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1204,'Sweden','SE',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1205,'Switzerland','CH',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1206,'Syrian Arab Republic','SY',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1207,'Sao Tome and Principe','ST',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1208,'Taiwan','TW',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1209,'Tajikistan','TJ',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1210,'Tanzania, United Republic of','TZ',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1211,'Thailand','TH',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1212,'Bahamas','BS',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1213,'Gambia','GM',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1214,'Togo','TG',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1215,'Tokelau','TK',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1216,'Tonga','TO',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1217,'Trinidad and Tobago','TT',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1218,'Tunisia','TN',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1219,'Turkey','TR',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1220,'Turkmenistan','TM',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1221,'Turks and Caicos Islands','TC',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1222,'Tuvalu','TV',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1223,'Uganda','UG',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1224,'Ukraine','UA',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1225,'United Arab Emirates','AE',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1226,'United Kingdom','GB',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1227,'United States Minor Outlying Islands','UM',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1228,'United States','US',NULL,NULL,NULL,NULL,2,1);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1229,'Uruguay','UY',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1230,'Uzbekistan','UZ',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1231,'Vanuatu','VU',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1232,'Venezuela','VE',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1233,'Viet Nam','VN',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1234,'Virgin Islands, U.S.','VI',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1235,'Wallis and Futuna','WF',NULL,NULL,NULL,NULL,4,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1236,'Western Sahara','EH',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1237,'Yemen','YE',NULL,NULL,NULL,NULL,3,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1238,'Serbia and Montenegro','CS',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1239,'Zambia','ZM',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1240,'Zimbabwe','ZW',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1241,'Åland Islands','AX',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1242,'Serbia','RS',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1243,'Montenegro','ME',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1244,'Jersey','JE',NULL,NULL,NULL,NULL,99,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1245,'Guernsey','GG',NULL,NULL,NULL,NULL,99,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1246,'Isle of Man','IM',NULL,NULL,NULL,NULL,99,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1247,'South Sudan','SS',NULL,NULL,NULL,NULL,5,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1248,'Curaçao','CW',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1249,'Sint Maarten (Dutch Part)','SX',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1250,'Bonaire, Saint Eustatius and Saba','BQ',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1251,'Kosovo','XK',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1252,'Saint Barthélemy','BL',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `civicrm_country` (`id`, `name`, `iso_code`, `country_code`, `address_format_id`, `idd_prefix`, `ndd_prefix`, `region_id`, `is_province_abbreviated`) VALUES (1253,'Saint Martin (French part)','MF',NULL,NULL,NULL,NULL,2,0);
/*!40000 ALTER TABLE `civicrm_country` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

