
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_kunena_categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_kunena_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT '0',
  `name` tinytext,
  `alias` varchar(255) NOT NULL,
  `icon` varchar(60) DEFAULT NULL,
  `icon_id` tinyint(4) NOT NULL DEFAULT '0',
  `locked` tinyint(4) NOT NULL DEFAULT '0',
  `accesstype` varchar(20) NOT NULL DEFAULT 'joomla.level',
  `access` int(11) NOT NULL DEFAULT '0',
  `pub_access` int(11) NOT NULL DEFAULT '1',
  `pub_recurse` tinyint(4) DEFAULT '1',
  `admin_access` int(11) NOT NULL DEFAULT '0',
  `admin_recurse` tinyint(4) DEFAULT '1',
  `ordering` smallint(6) NOT NULL DEFAULT '0',
  `published` tinyint(4) NOT NULL DEFAULT '0',
  `channels` text,
  `checked_out` tinyint(4) NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `review` tinyint(4) NOT NULL DEFAULT '0',
  `allow_anonymous` tinyint(4) NOT NULL DEFAULT '0',
  `post_anonymous` tinyint(4) NOT NULL DEFAULT '0',
  `hits` int(11) NOT NULL DEFAULT '0',
  `description` text NOT NULL,
  `headerdesc` text NOT NULL,
  `class_sfx` varchar(20) NOT NULL,
  `allow_polls` tinyint(4) NOT NULL DEFAULT '0',
  `topic_ordering` varchar(16) NOT NULL DEFAULT 'lastpost',
  `iconset` varchar(255) NOT NULL DEFAULT 'default',
  `numTopics` mediumint(8) NOT NULL DEFAULT '0',
  `numPosts` mediumint(8) NOT NULL DEFAULT '0',
  `last_topic_id` int(11) NOT NULL DEFAULT '0',
  `last_post_id` int(11) NOT NULL DEFAULT '0',
  `last_post_time` int(11) NOT NULL DEFAULT '0',
  `allow_ratings` tinyint(4) NOT NULL DEFAULT '0',
  `params` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`),
  KEY `category_access` (`accesstype`,`access`),
  KEY `published_pubaccess_id` (`published`,`pub_access`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_kunena_categories` WRITE;
/*!40000 ALTER TABLE `jos_kunena_categories` DISABLE KEYS */;
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (1,0,'Main Forum','main-forum','',0,0,'joomla.group',0,1,1,0,1,1,1,NULL,0,'0000-00-00 00:00:00',0,0,0,0,'This is the main forum section. It serves as a container for categories for your topics.','The section header is used to display additional information about the categories of topics that it contains.','',0,'lastpost','default',0,0,0,0,0,0,'');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (2,1,'Open Discussion','open-discussion','',0,0,'joomla.group',1,1,1,0,1,1,1,'THIS',43,'2017-02-23 01:32:17',0,0,0,0,'We encourage new members to introduce themselves here. Get to know one another and share your interests.','','',0,'lastpost','default',7,31,331,398,1491233072,0,'{\"access_post\":[\"6\",\"2\",\"8\"],\"access_reply\":[\"6\",\"2\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (3,1,'Suggestion Box','suggestion-box','',0,0,'joomla.group',1,1,1,0,1,3,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'Have some feedback and input to share? \r\n Don\'t be shy and drop us a note. We want to hear from you and strive to make our site better and more user friendly for our guests and members a like.','This is the optional category header for the Suggestion Box.','',1,'lastpost','default',5,8,31,73,1470793458,0,'{\"access_post\":[\"6\",\"2\",\"8\"],\"access_reply\":[\"6\",\"2\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (4,0,'Evaptron','evaptron','',0,0,'joomla.group',1,11,1,8,1,3,0,'THIS',43,'2016-03-27 02:53:40',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (5,0,'Exodus','exodus','',0,0,'joomla.group',1,11,1,8,1,7,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (6,0,'Website Changers','website-changes','',0,0,'joomla.group',1,11,1,8,1,4,0,'THIS',43,'2016-07-22 01:29:47',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (7,3,'Solutions','solutions','',0,0,'joomla.level',1,1,1,8,1,1,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'Have a solution  to a problem, post it here','','',0,'lastpost','default',2,4,12,23,1458067908,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (8,1,'Website Changes','general-website-changes','',0,0,'joomla.group',1,11,1,8,1,6,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',5,22,22,54,1459977368,0,'{\"access_post\":[\"11\",\"8\"],\"access_reply\":[\"11\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (9,0,'Art','art','',0,0,'joomla.group',1,11,1,8,1,8,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'This is for anything related to art projects.  If it is artsy it goes here ','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (10,9,'Installation','installation','',0,0,'joomla.group',1,11,1,8,1,1,1,'THIS',43,'2016-03-27 03:03:40',0,0,0,0,'For anything related to an art Installation ','','',0,'lastpost','default',1,1,6,10,1443145989,0,'{\"access_post\":[\"6\",\"2\",\"8\"],\"access_reply\":[\"6\",\"2\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (11,9,'Other','other','',0,0,'joomla.group',1,11,1,8,1,2,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'For any decoration ideas','','',0,'lastpost','default',4,7,333,400,1492981268,0,'{\"access_post\":[\"6\",\"2\",\"8\"],\"access_reply\":[\"6\",\"2\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (12,0,'Tickets','tickets','',0,0,'joomla.group',1,11,1,8,1,2,0,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (13,1,'Ticket Questions','ticket-questions','',0,0,'joomla.group',1,11,1,8,1,2,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',3,4,323,379,1488227339,0,'{\"access_post\":[\"6\",\"8\"],\"access_reply\":[\"6\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (15,1,'Playa Stories','playa-stories','',0,0,'joomla.level',1,1,1,8,1,4,0,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (16,0,'Leadership','leadership','',0,1,'joomla.level',7,1,1,8,1,6,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (17,16,'Organization','organization','',0,1,'joomla.level',6,1,1,8,1,1,1,'THIS',43,'2016-03-28 21:24:08',0,0,0,0,'','','',0,'lastpost','default',2,7,329,397,1488940544,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (18,1,'Gear Suggestions','gear-suggestions','',0,0,'joomla.group',1,11,1,8,1,5,1,'THIS',43,'2016-03-27 05:06:38',0,0,0,0,'','','',0,'lastpost','default',5,7,327,375,1488078625,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (19,16,'Budget','budget','',0,1,'joomla.group',1,8,1,8,1,2,1,'THIS',43,'2016-03-28 21:01:11',0,0,0,0,'','','',0,'lastpost','default',2,8,17,67,1467858833,0,'{\"access_post\":[\"6\",\"2\",\"8\"],\"access_reply\":[\"6\",\"2\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (20,1,'Camp Events','camp-events','',0,0,'joomla.group',1,11,1,8,1,7,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'Please post all ideas and plans for Official Burning Man events that will appear in the 2016 Event Book. Submissions for Events happens on June 18th at 12PM noon. ','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (21,20,'2016 Events','2016-events','',0,0,'joomla.group',1,11,1,8,1,1,1,'THIS',43,'2016-04-05 18:51:55',0,0,0,0,'','','',0,'lastpost','default',1,4,20,66,1467314195,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (22,5,'General Discussion','general-discussion','',0,0,'joomla.group',1,11,1,8,1,1,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',1,1,330,394,1488860733,0,'{\"access_post\":[\"6\",\"2\",\"8\"],\"access_reply\":[\"6\",\"2\",\"8\"],\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (23,0,'Enter The Burn','enter-the-burn','',0,0,'joomla.group',1,11,1,8,1,5,0,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
INSERT INTO `jos_kunena_categories` (`id`, `parent_id`, `name`, `alias`, `icon`, `icon_id`, `locked`, `accesstype`, `access`, `pub_access`, `pub_recurse`, `admin_access`, `admin_recurse`, `ordering`, `published`, `channels`, `checked_out`, `checked_out_time`, `review`, `allow_anonymous`, `post_anonymous`, `hits`, `description`, `headerdesc`, `class_sfx`, `allow_polls`, `topic_ordering`, `iconset`, `numTopics`, `numPosts`, `last_topic_id`, `last_post_id`, `last_post_time`, `allow_ratings`, `params`) VALUES (24,20,'2017 Events','2017-events','',0,0,'joomla.level',1,1,1,8,1,2,1,'THIS',0,'0000-00-00 00:00:00',0,0,0,0,'','','',0,'lastpost','default',0,0,0,0,0,0,'{\"display\":{\"index\":{\"parent\":\"3\",\"children\":\"3\"}}}');
/*!40000 ALTER TABLE `jos_kunena_categories` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

