
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_modules_menu`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_modules_menu` (
  `moduleid` int(11) NOT NULL DEFAULT '0',
  `menuid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`moduleid`,`menuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_modules_menu` WRITE;
/*!40000 ALTER TABLE `jos_modules_menu` DISABLE KEYS */;
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (1,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (2,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (3,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (4,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (6,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (7,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (8,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (9,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (10,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (12,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (13,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (14,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (15,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (16,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (17,-523);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (17,-101);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (79,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (86,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (87,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (88,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (89,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (90,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (91,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (92,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (101,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (102,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (115,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (120,101);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (121,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (122,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (123,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (125,147);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (125,148);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (125,186);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (126,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (129,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (130,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (131,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (132,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (133,101);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (134,101);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (134,147);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (134,148);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (134,149);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (134,186);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (134,202);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (135,149);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (136,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (137,147);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (138,209);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (139,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (140,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (141,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (142,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (143,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (149,-101);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (150,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (151,-523);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (151,-101);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (152,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (153,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (154,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (155,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (156,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (157,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (158,-644);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (158,-643);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (158,-434);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (158,-200);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (159,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,102);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,423);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,424);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,425);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,426);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,427);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,428);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,429);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,430);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,431);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,432);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,535);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,536);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,537);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,538);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,539);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,540);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,541);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,542);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,543);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (160,544);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,423);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,424);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,425);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,426);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,427);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,428);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,429);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,430);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,431);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,535);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,536);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,537);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,538);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,539);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,540);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,541);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,542);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (161,543);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (162,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (163,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (164,200);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (164,433);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (164,434);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (164,643);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (164,644);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (165,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (166,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,423);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,424);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,425);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,426);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,427);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,428);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,429);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,430);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,431);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,535);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,536);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,537);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,538);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,539);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,540);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,541);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,542);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (167,543);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (168,0);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,423);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,424);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,425);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,426);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,427);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,428);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,429);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,430);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,431);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (169,432);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,102);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,423);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,424);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,425);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,426);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,427);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,428);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,429);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,430);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,431);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,535);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,536);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,537);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,538);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,539);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,540);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,541);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,542);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,543);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,544);
INSERT INTO `jos_modules_menu` (`moduleid`, `menuid`) VALUES (170,743);
/*!40000 ALTER TABLE `jos_modules_menu` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

