
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_update_sites_extensions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_update_sites_extensions` (
  `update_site_id` int(11) NOT NULL DEFAULT '0',
  `extension_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`update_site_id`,`extension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Links extensions to update sites';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_update_sites_extensions` WRITE;
/*!40000 ALTER TABLE `jos_update_sites_extensions` DISABLE KEYS */;
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (1,700);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (2,700);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (3,600);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (5,10016);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (7,10022);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (8,10027);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (8,10029);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (8,10414);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (9,10030);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (10,10039);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (11,10057);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (12,10058);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (13,10059);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (14,10060);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (15,10061);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (17,10096);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (18,10097);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (19,10098);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (20,10099);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (21,10100);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (22,10101);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (23,10102);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (24,10103);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (25,10104);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (26,10105);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (27,10106);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (28,10107);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (29,10108);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (30,10109);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (31,10110);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (32,10111);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (41,10095);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (41,10440);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (42,10120);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (43,10121);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (43,10156);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (44,10123);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (44,10124);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (44,10125);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (45,10144);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (46,28);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (48,10179);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (49,10182);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (50,10057);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (52,801);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (53,10236);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (54,10237);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (55,10242);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (56,10245);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (57,10000);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (58,10251);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (59,10250);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (60,10274);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (63,10039);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (64,10300);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (65,10303);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (69,10120);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (69,10331);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (70,28);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (71,10340);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (74,10014);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (75,10351);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (76,10000);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (77,10355);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (78,10360);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (79,10382);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (80,10022);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (82,10016);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (83,10390);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (86,10390);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (88,10391);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (89,10418);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (90,10419);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (92,10436);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (93,10427);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (94,10428);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (95,10434);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (96,10431);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (97,10426);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (98,10430);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (99,10437);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (100,10424);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (101,10432);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (102,10439);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (103,10433);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (104,10425);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (106,10429);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (107,10438);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (108,10423);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (109,10422);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (110,10421);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (120,10457);
INSERT INTO `jos_update_sites_extensions` (`update_site_id`, `extension_id`) VALUES (121,0);
/*!40000 ALTER TABLE `jos_update_sites_extensions` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

