
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_finder_terms_common`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_finder_terms_common` (
  `term` varchar(75) NOT NULL,
  `language` varchar(3) NOT NULL,
  KEY `idx_word_lang` (`term`,`language`),
  KEY `idx_lang` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_finder_terms_common` WRITE;
/*!40000 ALTER TABLE `jos_finder_terms_common` DISABLE KEYS */;
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('a','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('about','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('after','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('ago','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('all','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('am','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('an','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('and','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('ani','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('any','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('are','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('aren\'t','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('as','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('at','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('be','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('but','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('by','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('for','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('from','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('get','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('go','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('how','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('if','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('in','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('into','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('is','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('isn\'t','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('it','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('its','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('me','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('more','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('most','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('must','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('my','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('new','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('no','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('none','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('not','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('noth','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('nothing','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('of','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('off','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('often','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('old','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('on','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('onc','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('once','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('onli','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('only','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('or','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('other','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('our','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('ours','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('out','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('over','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('page','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('she','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('should','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('small','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('so','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('some','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('than','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('thank','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('that','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('the','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('their','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('theirs','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('them','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('then','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('there','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('these','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('they','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('this','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('those','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('thus','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('time','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('times','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('to','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('too','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('true','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('under','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('until','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('up','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('upon','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('use','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('user','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('users','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('veri','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('version','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('very','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('via','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('want','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('was','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('way','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('were','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('what','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('when','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('where','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('whi','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('which','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('who','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('whom','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('whose','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('why','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('wide','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('will','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('with','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('within','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('without','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('would','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('yes','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('yet','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('you','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('your','en');
INSERT INTO `jos_finder_terms_common` (`term`, `language`) VALUES ('yours','en');
/*!40000 ALTER TABLE `jos_finder_terms_common` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

