
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_rsfirewall_signatures`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_rsfirewall_signatures` (
  `signature` varchar(255) NOT NULL,
  `type` varchar(16) NOT NULL,
  `reason` varchar(255) NOT NULL,
  PRIMARY KEY (`signature`,`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_rsfirewall_signatures` WRITE;
/*!40000 ALTER TABLE `jos_rsfirewall_signatures` DISABLE KEYS */;
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\'b\'.\'as\'.\'e6\'.\'4_\'.\'en\'.\'co\'.\'de\'','regex','PHP Injection - base64_decode() obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\'bas\'.\'e64_d\'.\'eco\'.\'de\'','regex','PHP Injection - base64_decode() obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\'cre\'.\'ate\'.\'_fun\'.\'ct\'.\'io\'.\'n\'','regex','PHP Injection - create_function() obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(@(\\$[a-z0-9]+\\(){4,})','regexis','PHP Injection - Obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(chr\\(([0-9]+){3,}\\)\\.chr\\(([0-9]+)\\)\\.chr\\(([0-9]+)\\)\\.chr\\(([0-9]+)\\))\\.chr\\(([0-9]+)\\)\\.chr\\(([0-9]+)\\)','regex','Possible PHP injection (obfuscated code)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(include\\_once|require\\_once|include|require)(\\s+)?(\\()?[\'|\"](.*)(\\.png|\\.gif|\\.jpg|\\.jpeg|\\.ini)[\'|\"](\\))?','regex','Highly suspicious inclusion (possible CryptoPHP)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(js/jquery\\.min\\.php.*?\"\\?default_keyword\\=\" \\+ default_keyword)','regex','Search engine referrer hijacking');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(realstatistics\\.(info|pro)|realanalytics\\.pro|siteanalytics\\.pro|webstatistics\\.pro|adobesecurupdate\\.com|microsoft-securety\\.com)','regexis','Realstatistics Malware');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(shell_exec|passthru|system|exec|popen)[\\s+]?\\([\\s+]?\\$(GLOBALS|_SERVER|_GET|_POST|_FILES|_COOKIE|_SESSION|_REQUEST|_ENV)','regex','Possible PHP injection (binary executed from superglobal variable)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(shell_exec|passthru|system|exec|popen)\\s?\\((\'|\")(wget|lynx|links|curl)','regex','Possible PHP injection (file download)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(wget|lynx|links|curl) https?:\\/\\/.*?; chmod .*?; \\.\\/','regex','Possible PHP injection (file download and execution)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(wget|lynx|links|curl) https?:\\/\\/.*?; perl .*?','regex','Possible PHP injection (file download and execution)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('([a-z0-9_]+\\/\\*(.*?)\\*\\/\\()','regex','PHP Injection - Obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(\\$func=(\"[a-z_]+\"[\\.]){4,})','regexis','PHP Injection - Obfuscated function name');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(\\$s\\_func=(\"[a-z_]+\"[\\.]){4,})','regexis','PHP Injection - Obfuscated function name');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(\\$[a-z0-9]+\\s?\\(){3,}','regexi','PHP Injection - Obfuscated function name');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(\\$[a-z0-9]+\\{[0-9]+\\}\\s?\\.?\\s?){10,}','regexis','PHP Injection - Obfuscated function name');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(\\$[a-z]+)\\(\"[a-z]\",\\s?\"\",\\s?\"[a-z0-9_]+\"\\)','regexis','PHP Injection - Obfuscated function name');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('(\\[(SHELL|ZAD)\\ID])','regexs','PHP Injection - Mass mailer');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('<!--checker_start','regex','PHP injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('<input name=\".*?\" type=\"file\">','regex','Possible PHP Shell - File uploader');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('<\\?php[\\s+]{240,}(.*?)\\s','regex','Abnormally long spacing after PHP tag - could be used to hide code from view');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('@\\$[a-zA-Z0-9]+\\(\\$_(POST|GET|REQUEST|COOKIE)\\[.*','regex','Possible PHP Injection - obfuscated code execution from Superglobal variable.');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('act=phpinfo','regex','PHP Shell - c99shell variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('antichat','filename','PHP Shell - c99shell Antichat variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('bash_history','filename','Possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('bitchx','filename','IRC Client - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('brute *force','filename','Bruteforce');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('c99shell','filename','PHP Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('c99shell','regex','PHP Shell - c99shell variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('ccteam\\.ru','regex','PHP Shell - c99shell variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('chr\\(\\([0-9]+\\-[0-9]+\\)\\)','regex','Possible PHP Injection - Obfuscated code');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('create\\_function\\(\\\'\\$\\\'(.*)','regex','Possible PHP injection (create_function() call)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('cwings','filename','PHP Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('CWShellDumper','filename','PHP Shell - c99shell CWShellDumper variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('DALnet','filename','IRC Client - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('die\\(md5\\(\\\'[a-z0-9_]+\\\'\\)\\);','regexis','PHP Injection - Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('directmail','filename','Mailer - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eggdrop','filename','IRC Bot - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('ekin0x','filename','PHP Shell - c99shell ekin0x variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval[\\s]?\\([\\s]?base64_decode\\([\\s]?.*?\\)\\)','regex','Possible PHP injection (encoded code - base64)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\(\"\\?\\>\"\\.base64_decode','regex','Possible PHP injection (encoded code - base64)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\(base64_decode\\((?s).*?\\)\\)','regex','Possible PHP injection (encoded code - base64)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\(stripslashes\\(\\$_(.*?)\\)\\)','regex','Possible PHP injection (code executed from superglobal variable)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\([a-zA-Z0-9]+\\([$a-zA-Z0-9]+','regex','Possible PHP injection (code executed through obfuscated functions)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\(\\$[a-zA-Z0-9]+\\(\\$[a-zA-Z0-9]+\\(\\$[a-zA-Z0-9]+','regex','PHP Injection - Obfuscated code');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\(\\$\\_POST\\[\"[a-z]+\"\\]\\)','regex','PHP Injection - Code executed from $_POST request');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\(\\$_(.*?)\\)','regex','Possible PHP injection (code executed from superglobal variable)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\/\\*(.*)\\*\\/\\(','regexis','Obfuscated eval()');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('eval\\/\\*\\*\\/\\(','regex','Hidden eval()');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('exec\\((.*)\\/bin\\/sh','regex','Possible PHP injection (shell execution)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('guardservices','filename','Possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('h4cker\\.tr','regex','PHP Shell - General variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('hanixavi@msn.com','regex','PHP Shell - File uploader');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('header(\\s+)?\\([\"|\'](l|L)ocation:(\\s+)?http:(.*?)\\)','regex','Possible PHP injection (redirect)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('http\\://fbt\\.yahoo\\.com/counter\\.php','regex','PHP injection (Russian counter)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('if\\(function_exists\\(\'ob_start\'\\)&&!isset\\(\\$GLOBALS\\[(.*?)\\]\\)\\){\\$GLOBALS\\[(.*?)\\]=','regex','PHP injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('if\\(\\$_POST\\[\'golden\'\\]\\=\\=\"Done\"\\)','regex','PHP Injection - File uploader');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('ini\\_set\\(chr\\(','regex','PHP injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('kacak','filename','PHP Shell - c99shell kacak variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('liz0zim','filename','PHP Shell - c99shell liz0zim variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('m0rtix','filename','Backdoor - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('mail(\\s+)?\\((\"|\')(.*@)','regex','Possible PHP injection (mailer)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('mkdir\\(.*?[\\s+]?,[\\s+]?0777','regex','Unsafe directory creation - 0777 permissions.');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('ob_start\\(\"callbck\"\\)','regex','PHP injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('PHPencoder','regex','PHP Encoded file - PHPencoder variant, please review manually');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('PHPJiaMi\\.Com','regexi','PHP Injection - Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('phpremoteview','filename','PHP Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('phpshell','filename','PHP Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('preg_replace\\(\"/\\.\\*/e\"','regex','Possible PHP injection (obfuscated code using /e modifier)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('preg_replace\\([\'|\"]/\\(\\.\\*\\)\\/e','regex','Possible PHP injection (obfuscated code using /e modifier)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('ps -aux','regex','PHP Shell - suspicious code');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('psyBNC','filename','IRC Client - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('r0nin','filename','Exploit - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('r57shell','filename','PHP Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('r57shell','regex','PHP Shell - r57shell variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('r57\\.gen\\.tr','regex','PHP Shell - General variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('raslan58','filename','Possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('safe0ver','filename','PHP Shell - c99shell safe0ver variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('Saudi Sh3ll','filename','PHP Shell - Saudi Sh3ll variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('shellbot','filename','Backdoor - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('sh\\_decrypt\\_phase','regex','PHP Injection - Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('sosyete','filename','PHP Shell - c99shell sosyete variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('spymeta','filename','Possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('strrev\\((\'|\")edoced_46esab(\'|\")\\)','regex','Possible PHP injection (obfuscated code)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('strrev\\(base64_decode\\((?s).*?\\)\\)','regex','Possible PHP injection (encoded code - strrev())');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('str_rot13\\(\'riny\'\\)','regex','PHP Injection - Obfuscated eval');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('str_rot13\\(base64_decode\\((?s).*?\\)\\)','regex','Possible PHP injection (encoded code - str_rot13())');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('tryag','filename','PHP Shell - c99shell tryag variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('undernet','filename','IRC Client - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('Upload Gagal','regex','PHP Shell - File uploader');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('void\\.ru','filename','Possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('vulnscan','filename','Vulnerability Scanner - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('w00t','filename','Exploit - possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('zehir4','filename','PHP Shell - c99shell zehir4 variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('[a-zA-Z0-9]{500,}','regex','Possible PHP injection (abnormally long string - might be base64)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$current \\= htmlentities \\(\\$_SERVER \\[\'PHP_SELF\'\\] \\. \"\\?dir\\=\" \\. \\$dir\\)','regex','PHP Injection - Dark Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$from_name\\=randText\\(\\)','regexi','PHP Mass Mailer - random \"from\" address');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$GLOBALS\\[\'([a-z]+)?([0-9]+)?\']\\(','regex','Possible PHP injection (code executed through superglobal variable)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$GLOBALS\\[\\$GLOBALS\\[\'[a-z0-9]+\'\\]\\[[0-9]+\\]','regex','PHP Injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$QBDB51E25BF9A7F3D2475072803D1C36D','regex','PHP Shell - c99shell variant compressed');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$red_host/\\$fake_script','regex','PHP Injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$ua\\=@\\$_SERVER\\[\"HTTP_USER_AGENT\"\\];\\$row\\=split\\(\"\\=\\=\\=\",\\$ua\\)','regex','PHP Injection - Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$uploadfile \\= \\$_POST\\[\"pt\"\\]\\.\\$_FILES\\[\"file\"\\]\\[\"name\"\\]','regex','PHP Shell - File uploader');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$wp_add_filter\\(','regex','PHP injection (obfuscated code)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$[a-z0-9]+ = \\$\\_POST\\[\'[a-z0-9]+\'\\];.@?passthru\\(\\$[a-z]+\\);','regexis','PHP Injection - Shell');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$[a-z0-9]+=\\$_COOKIE','regex','Possible PHP Injection - superglobal variable obfuscation.');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$[a-z0-9]+\\s?=\\s?\\$[a-z0-9]+\\(\"[a-z0-9]+\",\\s?\"\",\\s?\"[a-z0-9]+\\_[a-z0-9]+\"\\);','regex','PHP Injection - Obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$[^ -~]+\\(.*?\\);','regex','Possible PHP Injection - Characters outside of typing range.');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$\\_(FILES|SERVER|POST|GET)\\[\"([A-Za-z\\_]+)?(\\\\x[0-9A-Fa-f]{1,2}){1,}([A-Za-z\\_]+)?\\\"]','regex','PHP Injection - Obfuscated Superglobal variable.');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$_GET\\[\"ping\"\\] \\=\\= \\(\"ping_host\"\\)','regex','PHP Mass Mailer');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$_GET\\[\'mailzor\'\\]','regex','PHP Injection - Mass mailer');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$_GET\\[\'sws\'\\]\\=\\= \'phpinfo\'','regex','PHP Shell - Saudi Sh3ll variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$_POST\\[\'cmd\'\\]\\=\\=\"php_eval\"','regex','PHP Shell - r57shell variant');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\$_[a-zA-Z]=__FILE__;\\$_[a-zA-Z]=','regex','PHP injection (obfuscated code)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\(\"/[a-zA-Z0-9]+/e\",','regex','Possible PHP injection (obfuscated code using /e modifier)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\(gzinflate\\(base64_decode\\((?s).*\\)','regex','Possible PHP injection (compressed code - gzip)');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\.ru/','filename','Possible hijacked server');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\/etc\\/passwd','regex','PHP Shell - suspicious code');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\/jquery\\.min\\.php','regex','PHP Injection - Search engine hijacker');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\[(\"(\\\\x[0-9A-F]{2}){1,}\",?)+\\]','regexi','Javascript variable obfuscation');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\\\x47\\\\x4c\\\\x4fB\\\\x41\\\\x4c\\\\x53','regex','PHP Injection - GLOBALS obfuscated variable call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\\\x62\\\\141\\\\x73\\\\145\\\\x36\\\\64\\\\x5f\\\\144\\\\x65\\\\143\\\\x6f\\\\144\\\\x65','regex','PHP Injection - base64_decode() obfuscated function call');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('\\_[0-9]+\\([0-9]+\\)','regex','Possible PHP Injection - function name contains only numbers.');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('^GIF89;([^\\n]*\\n+)+(\\<\\?php)','regex','PHP injection - Hidden inside GIF file');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('^\\#[a-z0-9]+\\#$(.*?)^\\#\\/[a-z0-9]+\\#$','regexms','PHP Injection - Page hijacker');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('^\\$password\\=@\\$_REQUEST\\[\'password\'\\];','regexm','Possible PHP Injection');
INSERT INTO `jos_rsfirewall_signatures` (`signature`, `type`, `reason`) VALUES ('_il_exec\\(\\)','regex','Possible risk - ionCube encrypted file');
/*!40000 ALTER TABLE `jos_rsfirewall_signatures` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

