
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_rsform_component_type_fields`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_rsform_component_type_fields` (
  `ComponentTypeId` int(11) NOT NULL DEFAULT '0',
  `FieldName` text NOT NULL,
  `FieldType` varchar(32) NOT NULL DEFAULT 'hidden',
  `FieldValues` text NOT NULL,
  `Properties` text NOT NULL,
  `Ordering` int(11) NOT NULL DEFAULT '0',
  KEY `ComponentTypeId` (`ComponentTypeId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_rsform_component_type_fields` WRITE;
/*!40000 ALTER TABLE `jos_rsform_component_type_fields` DISABLE KEYS */;
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'READONLY','select','NO\r\nYES','',20);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'COMPONENTTYPE','hidden','355','',21);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'KEYBOARD','select','NO\r\nYES','',19);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'TOFIXED','select','NO\r\nYES','',18);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'FROMFIXED','select','NO\r\nYES','',17);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'FORCEEDGES','select','YES\r\nNO','',16);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'GRIDSTEP','textbox','10','numeric',15);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'GRIDSNAP','select','NO\r\nYES','',14);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'VALUES','textarea','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'MINVALUE','textbox','0','numeric',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'MAXVALUE','textbox','100','numeric',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'GRID','select','YES\r\nNO','',13);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'SKIN','select','FLAT\r\nHTML5\r\nMODERN\r\nNICE\r\nSIMPLE','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'USEVALUES','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALUES\"],\"hide\":[\"MINVALUE\", \"MAXVALUE\", \"GRIDSNAP\", \"GRIDSTEP\"]},\"NO\":{\"show\":[\"MINVALUE\", \"MAXVALUE\", \"GRIDSNAP\", \"GRIDSTEP\"],\"hide\":[\"VALUES\"]}}}',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'DEFAULTVALUE','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'DESCRIPTION','textarea','','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'SLIDERTYPE','select','SINGLE\r\nDOUBLE','{\"case\":{\"SINGLE\":{\"show\":[],\"hide\":[\"FROMFIXED\",\"TOFIXED\"]},\"DOUBLE\":{\"show\":[\"FROMFIXED\",\"TOFIXED\"],\"hide\":[]}}}',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (355,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'COMPONENTTYPE','hidden','411','',200);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'MAXTIMEJQ','textarea','','',15);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'ADDITIONALATTRIBUTES','textarea','','',16);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'CALENDARLAYOUT','select','FLAT\r\nPOPUP','{\"case\":{\"POPUP\":{\"show\":[\"READONLY\", \"POPUPLABEL\"],\"hide\":[]},\"FLAT\":{\"show\":[],\"hide\":[\"READONLY\", \"POPUPLABEL\"]}}}',17);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'THEME','select','DEFAULT\r\nDARK','',20);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'POPUPLABEL','textbox','...','',19);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'READONLY','select','NO\r\nYES','',18);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'TIMEPICKERFORMAT','textbox','H:i','',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'TIMESTEP','textbox','30','',13);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'MINTIMEJQ','textarea','','',14);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'MINDATEJQ','textarea','','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'MAXDATEJQ','textarea','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'TIMEPICKER','select','YES\r\nNO','{\"case\":{\"YES\":{\"show\":[\"TIMEPICKERFORMAT\", \"TIMESTEP\",\"MINTIMEJQ\", \"MAXTIMEJQ\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"TIMEPICKERFORMAT\", \"TIMESTEP\",\"MINTIMEJQ\", \"MAXTIMEJQ\"]}}}',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'DATEFORMAT','textbox','d/m/Y H:i','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'VALIDATIONCALENDAR','select','//<code>\nreturn RSFormProHelper::getOtherCalendars(411);\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'DESCRIPTION','textarea','','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'DEFAULTVALUE','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (411,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'GEOLOCATION','select','NO\r\nYES','',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'MAPTYPE','select','ROADMAP\r\nSATELLITE\r\nHYBRID\r\nTERRAIN','',13);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'COMPONENTTYPE','hidden','212','',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'SIZE','textbox','20','numeric',13);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'MAPZOOM','textbox','10','numeric',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'MAPRESULT','select','ADDRESS\r\nCOORDINATES','',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'MAPCENTER','textbox','39.5500507,-105.7820674','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'DEFAULTVALUE','textarea','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'ADDITIONALATTRIBUTES','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'MAPWIDTH','textbox','450px','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'MAPHEIGHT','textbox','300px','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'DESCRIPTION','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (212,'CAPTION','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWYEARPLEASE','textbox','Year','',15);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'STARTYEAR','textbox','1960','',16);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'ENDYEAR','textbox','2013','',17);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'STORELEADINGZERO','select','NO\r\nYES','',18);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'ADDITIONALATTRIBUTES','textarea','','',18);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'COMPONENTTYPE','hidden','211','',19);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'DESCRIPTION','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'REQUIRED','select','NO\r\nYES','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'DATEORDERING','select','DMY\r\nMDY\r\nYMD\r\nYDM\r\nMYD\r\nDYM','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'DATESEPARATOR','textbox',' / ','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWDAY','select','YES\r\nNO','{\"case\":{\"YES\":{\"show\":[\"SHOWDAYPLEASE\" ,\"SHOWDAYTYPE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"SHOWDAYPLEASE\" ,\"SHOWDAYTYPE\"]}}}',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWDAYPLEASE','textbox','Day','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWDAYTYPE','select','DAY_TYPE_01\r\nDAY_TYPE_1','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWMONTH','select','YES\r\nNO','{\"case\":{\"YES\":{\"show\":[\"SHOWMONTHPLEASE\" ,\"SHOWMONTHTYPE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"SHOWMONTHPLEASE\" ,\"SHOWMONTHTYPE\"]}}}',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWMONTHPLEASE','textbox','Month','',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWMONTHTYPE','select','MONTH_TYPE_01\r\nMONTH_TYPE_1\r\nMONTH_TYPE_TEXT_SHORT\r\nMONTH_TYPE_TEXT_LONG','',13);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'SHOWYEAR','select','YES\r\nNO','{\"case\":{\"YES\":{\"show\":[\"SHOWYEARPLEASE\" ,\"STARTYEAR\", \"ENDYEAR\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"SHOWYEARPLEASE\" ,\"STARTYEAR\", \"ENDYEAR\"]}}}',14);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'VALIDATIONRULE_DATE','select','//<code>\r\nreturn RSFormProHelper::getDateValidationRules();\r\n//</code>','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (21,'PRICE','textbox','','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (21,'CAPTION','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (21,'NAME','hiddenparam','rsfp_Product','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (21,'COMPONENTTYPE','hidden','21','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (21,'DESCRIPTION','textarea','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (21,'SHOW','select','YES\r\nNO','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'REQUIRED','select','NO\r\nYES','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'ITEMS','textarea','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'MULTIPLE','select','NO\r\nYES','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'SIZE','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'COMPONENTTYPE','hidden','22','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'CAPTION','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'ADDITIONALATTRIBUTES','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'DESCRIPTION','textarea','','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'VIEW_TYPE','select','DROPDOWN\r\nCHECKBOX\r\nRADIOGROUP','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (22,'FLOW','select','HORIZONTAL\r\nVERTICAL','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (23,'COMPONENTTYPE','hidden','23','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (23,'CAPTION','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (23,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'CAPTION','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'FLOW','select','HORIZONTAL\r\nVERTICAL','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'VIEW_TYPE','select','DROPDOWN\r\nRADIOGROUP','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'ADDITIONALATTRIBUTES','textarea','','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'DESCRIPTION','textarea','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'SHOW','select','YES\r\nNO','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (27,'COMPONENTTYPE','hidden','27','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'REQUIRED','select','NO\r\nYES','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'SIZE','textbox','20','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'MAXSIZE','textbox','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'VALIDATIONRULE','select','//<code>\r\nreturn RSgetValidationRules();\r\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'ADDITIONALATTRIBUTES','textarea','','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'DEFAULTVALUE','textarea','','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'DESCRIPTION','textarea','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'COMPONENTTYPE','hidden','28','',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (28,'VALIDATIONEXTRA','textbox','','',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (500,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (500,'LABEL','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (500,'COMPONENTTYPE','hidden','500','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (500,'LAYOUTHIDDEN','hiddenparam','YES','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (499,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (499,'LABEL','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (499,'WIRE','textarea','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (499,'COMPONENTTYPE','hidden','499','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (499,'LAYOUTHIDDEN','hiddenparam','YES','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (24,'NAME','textbox','','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (24,'CAPTION','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (24,'ADDITIONALATTRIBUTES','textarea','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (24,'DESCRIPTION','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (24,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (24,'COMPONENTTYPE','hidden','24','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'VALIDATION_ALLOW_INCORRECT_DATE','select','NO\r\nYES','',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (211,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'BUTTONTYPE','select','TYPEBUTTON\nTYPEINPUT','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'DISPLAYPROGRESSMSG','textarea','<div>\r\n <p><em>Page <strong>{page}</strong> of {total}</em></p>\r\n <div class=\"rsformProgressContainer\">\r\n  <div class=\"rsformProgressBar\" style=\"width: {percent}%;\"></div>\r\n </div>\r\n</div>','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'VALIDATENEXTPAGE','select','NO\r\nYES','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'DISPLAYPROGRESS','select','NO\r\nAUTO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"DISPLAYPROGRESSMSG\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"DISPLAYPROGRESSMSG\"]}, \"AUTO\":{\"show\":[],\"hide\":[\"DISPLAYPROGRESSMSG\"]}}}',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'ADDITIONALATTRIBUTES','textarea','','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'PREVBUTTON','textbox','< Prev','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'NEXTBUTTON','textbox','Next >','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'COMPONENTTYPE','hidden','41','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (41,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'LEADINGZEROLENGTH','select','0\r\n1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n10','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'TICKETTYPE','select','RANDOM\r\nSEQUENTIAL','{\"case\":{\"RANDOM\":{\"show\":[\"CHARACTERS\", \"LENGTH\"],\"hide\":[\"LEADINGZEROLENGTH\"]},\"SEQUENTIAL\":{\"show\":[\"LEADINGZEROLENGTH\"],\"hide\":[\"CHARACTERS\", \"LENGTH\"]}}}',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'CHARACTERS','select','ALPHANUMERIC\r\nALPHA\r\nNUMERIC','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'COMPONENTTYPE','hidden','15','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'ADDITIONALATTRIBUTES','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'VALIDATIONMULTIPLE','selectmultiple','//<code>\r\nreturn RSFormProHelper::getValidationRules(false, true);\r\n//</code>','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'LENGTH','textbox','8','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'VALIDATIONEXTRA','textbox','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (15,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'PLACEHOLDER','textbox','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'VALIDATIONRULE','select','//<code>\r\nreturn RSFormProHelper::getValidationRules();\r\n//</code>','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'DESCRIPTION','textarea','','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'COMPONENTTYPE','hidden','14','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'ADDITIONALATTRIBUTES','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'DEFAULTVALUE','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'MAXSIZE','textbox','','numeric',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'SIZE','textbox','','numeric',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'REQUIRED','select','NO\r\nYES','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (14,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'DISPLAYPROGRESSMSG','textarea','<div>\r\n <p><em>Page <strong>{page}</strong> of {total}</em></p>\r\n <div class=\"rsformProgressContainer\">\r\n  <div class=\"rsformProgressBar\" style=\"width: {percent}%;\"></div>\r\n </div>\r\n</div>','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'PREVBUTTON','textbox','< Prev','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'DISPLAYPROGRESS','select','NO\r\nAUTO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"DISPLAYPROGRESSMSG\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"DISPLAYPROGRESSMSG\"]}, \"AUTO\":{\"show\":[],\"hide\":[\"DISPLAYPROGRESSMSG\"]}}}',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'BUTTONTYPE','select','TYPEBUTTON\nTYPEINPUT','',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'COMPONENTTYPE','hidden','13','',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'ADDITIONALATTRIBUTES','textarea','','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'RESETLABEL','textbox','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'LABEL','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'RESET','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"RESETLABEL\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"RESETLABEL\"]}}}',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'CAPTION','textbox','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (13,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (11,'COMPONENTTYPE','hidden','11','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (11,'ADDITIONALATTRIBUTES','textarea','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (11,'DEFAULTVALUE','textarea','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (11,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (10,'COMPONENTTYPE','hidden','10','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (10,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (10,'TEXT','textarea','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'EMAILATTACH','emailattach','','',102);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'PREFIX','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'COMPONENTTYPE','hidden','9','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'DESCRIPTION','textarea','','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'ADDITIONALATTRIBUTES','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'DESTINATION','textbox','//<code>\r\nreturn \'components/com_rsform/uploads/\';\r\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'ACCEPTEDFILES','textarea','','oneperline',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (9,'FILESIZE','textbox','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'IMAGETYPE','select','FREETYPE\r\nNOFREETYPE\r\nINVISIBLE','{\"case\":{\"FREETYPE\":{\"show\":[\"BACKGROUNDCOLOR\",\"TEXTCOLOR\",\"TYPE\",\"FLOW\",\"LENGTH\"],\"hide\":[]},\"NOFREETYPE\":{\"show\":[\"BACKGROUNDCOLOR\",\"TEXTCOLOR\",\"TYPE\",\"FLOW\",\"LENGTH\"],\"hide\":[]},\"INVISIBLE\":{\"show\":[],\"hide\":[\"BACKGROUNDCOLOR\",\"TEXTCOLOR\",\"TYPE\",\"FLOW\",\"LENGTH\"]}}}',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'SIZE','textbox','15','numeric',12);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'REFRESHTEXT','textbox','REFRESH','',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'BACKGROUNDCOLOR','textbox','#FFFFFF','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'TEXTCOLOR','textbox','#000000','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'TYPE','select','ALPHA\r\nNUMERIC\r\nALPHANUMERIC','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'SHOWREFRESH','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"REFRESHTEXT\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"REFRESHTEXT\"]}}}',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'FLOW','select','VERTICAL\r\nHORIZONTAL','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'COMPONENTTYPE','hidden','8','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'ADDITIONALATTRIBUTES','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'DESCRIPTION','textarea','','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'LENGTH','textbox','4','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'ADDITIONALATTRIBUTES','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'DESCRIPTION','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'COMPONENTTYPE','hidden','7','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'BUTTONTYPE','select','TYPEBUTTON\nTYPEINPUT','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (8,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'RESETLABEL','textbox','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'RESET','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"RESETLABEL\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"RESETLABEL\"]}}}',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'LABEL','textbox','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (7,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'DEFAULTVALUE','textarea','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'MAXDATE','textarea','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'MINDATE','textarea','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'CALENDARLAYOUT','select','FLAT\r\nPOPUP','{\"case\":{\"POPUP\":{\"show\":[\"READONLY\", \"POPUPLABEL\"],\"hide\":[]},\"FLAT\":{\"show\":[],\"hide\":[\"READONLY\", \"POPUPLABEL\"]}}}',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'POPUPLABEL','textbox','...','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'READONLY','select','NO\r\nYES','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'ADDITIONALATTRIBUTES','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'COMPONENTTYPE','hidden','6','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'DESCRIPTION','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'VALIDATIONCALENDAR','select','//<code>\r\nreturn RSFormProHelper::getOtherCalendars(6);\r\n//</code>','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'DATEFORMAT','textbox','d/m/Y','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (6,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'COMPONENTTYPE','hidden','5','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'DESCRIPTION','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'ADDITIONALATTRIBUTES','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'FLOW','select','HORIZONTAL\r\nVERTICAL\r\nVERTICAL2COLUMNS\r\nVERTICAL3COlUMNS\r\nVERTICAL4COLUMNS\r\nVERTICAL6COLUMNS','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'ITEMS','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (5,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'COMPONENTTYPE','hidden','4','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'DESCRIPTION','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'ADDITIONALATTRIBUTES','textarea','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'FLOW','select','HORIZONTAL\r\nVERTICAL\r\nVERTICAL2COLUMNS\r\nVERTICAL3COlUMNS\r\nVERTICAL4COLUMNS\r\nVERTICAL6COLUMNS','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'ITEMS','textarea','','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (4,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',100);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'COMPONENTTYPE','hidden','3','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'ADDITIONALATTRIBUTES','textarea','','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'DESCRIPTION','textarea','','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'REQUIRED','select','NO\r\nYES','{\"case\":{\"YES\":{\"show\":[\"VALIDATIONMESSAGE\"],\"hide\":[]},\"NO\":{\"show\":[],\"hide\":[\"VALIDATIONMESSAGE\"]}}}',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'ITEMS','textarea','','',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'MULTIPLE','select','NO\r\nYES','',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'SIZE','textbox','','numeric',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'WYSIWYG','select','NO\r\nYES','',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'VALIDATIONEXTRA','textbox','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (3,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'PLACEHOLDER','textbox','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'COMPONENTTYPE','hidden','2','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'DESCRIPTION','textarea','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'DEFAULTVALUE','textarea','','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'ADDITIONALATTRIBUTES','textarea','','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'VALIDATIONMULTIPLE','selectmultiple','//<code>\r\nreturn RSFormProHelper::getValidationRules(false, true);\r\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'VALIDATIONRULE','select','//<code>\r\nreturn RSFormProHelper::getValidationRules();\r\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'ROWS','textbox','5','numeric',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'COLS','textbox','50','numeric',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'REQUIRED','select','NO\r\nYES','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'ATTRMIN','textbox','','float',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'ATTRMAX','textbox','','float',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'ATTRSTEP','textbox','1','float',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'COMPONENTTYPE','hidden','1','',15);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'VALIDATIONEXTRA','textbox','','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (2,'NAME','textbox','','',1);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'VALIDATIONMESSAGE','textarea','INVALIDINPUT','',7);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'ADDITIONALATTRIBUTES','textarea','','',8);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'DEFAULTVALUE','textarea','','',9);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'PLACEHOLDER','textbox','','',10);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'DESCRIPTION','textarea','','',11);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'INPUTTYPE','select','text\r\nemail\r\ntel\r\nnumber\r\nrange\r\nurl','{\"case\":{\"number\":{\"show\":[\"ATTRMIN\",\"ATTRMAX\",\"ATTRSTEP\"],\"hide\":[\"MAXSIZE\"]},\"range\":{\"show\":[\"ATTRMIN\",\"ATTRMAX\",\"ATTRSTEP\"],\"hide\":[\"MAXSIZE\"]},\"text\":{\"show\":[\"MAXSIZE\"],\"hide\":[\"ATTRMIN\",\"ATTRMAX\",\"ATTRSTEP\"]},\"email\":{\"show\":[\"MAXSIZE\"],\"hide\":[\"ATTRMIN\",\"ATTRMAX\",\"ATTRSTEP\"]},\"tel\":{\"show\":[\"MAXSIZE\"],\"hide\":[\"ATTRMIN\",\"ATTRMAX\",\"ATTRSTEP\"]},\"url\":{\"show\":[\"MAXSIZE\"],\"hide\":[\"ATTRMIN\",\"ATTRMAX\",\"ATTRSTEP\"]}}}',0);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'VALIDATIONMULTIPLE','selectmultiple','//<code>\r\nreturn RSFormProHelper::getValidationRules(false, true);\r\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'VALIDATIONRULE','select','//<code>\r\nreturn RSFormProHelper::getValidationRules();\r\n//</code>','',6);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'MAXSIZE','textbox','','numeric',5);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'SIZE','textbox','20','numeric',4);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'REQUIRED','select','NO\r\nYES','',3);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'CAPTION','textbox','','',2);
INSERT INTO `jos_rsform_component_type_fields` (`ComponentTypeId`, `FieldName`, `FieldType`, `FieldValues`, `Properties`, `Ordering`) VALUES (1,'NAME','textbox','','',1);
/*!40000 ALTER TABLE `jos_rsform_component_type_fields` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

