
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_rsform_properties`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_rsform_properties` (
  `PropertyId` int(11) NOT NULL AUTO_INCREMENT,
  `ComponentId` int(11) NOT NULL DEFAULT '0',
  `PropertyName` text NOT NULL,
  `PropertyValue` text NOT NULL,
  UNIQUE KEY `PropertyId` (`PropertyId`),
  KEY `ComponentId` (`ComponentId`)
) ENGINE=MyISAM AUTO_INCREMENT=772 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_rsform_properties` WRITE;
/*!40000 ALTER TABLE `jos_rsform_properties` DISABLE KEYS */;
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (145,23,'NAME','name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (146,23,'CAPTION','Name:');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (147,23,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (148,23,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (149,23,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (150,23,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (151,23,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (152,23,'VALIDATIONMESSAGE','Please enter a name.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (153,23,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (154,23,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (155,23,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (156,23,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (157,24,'NAME','email');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (158,24,'CAPTION','Email:');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (159,24,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (160,24,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (161,24,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (162,24,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (163,24,'VALIDATIONRULE','emaildns');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (164,24,'VALIDATIONMESSAGE','Please enter a valid email address.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (165,24,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (166,24,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (167,24,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (168,24,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (169,25,'NAME','phone');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (170,25,'CAPTION','Phone: ');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (171,25,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (172,25,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (173,25,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (174,25,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (175,25,'VALIDATIONRULE','phonenumber');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (176,25,'VALIDATIONMESSAGE','Please enter a valid phone number.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (177,25,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (178,25,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (179,25,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (180,25,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (367,24,'PLACEHOLDER','Email');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (366,24,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (365,24,'ATTRSTEP','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (205,28,'NAME','message');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (206,28,'CAPTION','Message: ');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (207,28,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (208,28,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (209,28,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (210,28,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (211,28,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (212,28,'VALIDATIONMESSAGE','Please enter a message.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (213,28,'COLS','50');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (214,28,'ROWS','5');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (215,28,'WYSIWYG','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (216,28,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (217,28,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (218,29,'NAME','submit');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (219,29,'LABEL','submit');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (220,29,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (221,29,'RESET','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (222,29,'RESETLABEL','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (223,29,'DISPLAYPROGRESSMSG','<div>\r\n <p><em>Page <strong>{page}</strong> of {total}</em></p>\r\n <div class=\"rsformProgressContainer\">\r\n  <div class=\"rsformProgressBar\" style=\"width: {percent}%;\"></div>\r\n </div>\r\n</div>');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (224,29,'PREVBUTTON','PREV');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (225,29,'DISPLAYPROGRESS','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (226,29,'BUTTONTYPE','TYPEINPUT');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (227,29,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (228,29,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (364,24,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (363,24,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (362,28,'PLACEHOLDER','Message');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (361,25,'PLACEHOLDER','Phone');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (360,25,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (359,25,'ATTRSTEP','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (358,25,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (357,25,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (356,23,'PLACEHOLDER','Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (355,23,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (354,23,'ATTRSTEP','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (353,23,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (352,23,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (368,42,'NAME','First Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (369,42,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (370,42,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (371,42,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (372,42,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (373,42,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (374,42,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (375,42,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (376,42,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (377,42,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (378,42,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (379,42,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (380,42,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (381,42,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (382,42,'PLACEHOLDER','First Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (383,42,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (384,42,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (385,43,'NAME','Last Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (386,43,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (387,43,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (388,43,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (389,43,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (390,43,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (391,43,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (392,43,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (393,43,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (394,43,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (395,43,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (396,43,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (397,43,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (398,43,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (399,43,'PLACEHOLDER','Last Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (400,43,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (401,43,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (402,44,'NAME','attending_burningman');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (403,44,'CAPTION','Are you attending Burning Man this year?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (404,44,'ITEMS','Yes\r\nMaybe\r\nProbably Not\r\nNo\r\n');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (405,44,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (406,44,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (407,44,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (408,44,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (409,44,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (410,44,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (411,45,'NAME','vehicle');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (412,45,'CAPTION','Do you have a vehicle?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (413,45,'ITEMS','Yes\r\nNo');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (414,45,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (415,45,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (416,45,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (417,45,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (418,45,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (419,45,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (420,46,'NAME','early_arrival');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (421,46,'CAPTION','Can you arrive early on Saturday, August 26th?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (422,46,'ITEMS','Yes\r\nNo\r\nMaybe');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (423,46,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (424,46,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (425,46,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (426,46,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (427,46,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (428,46,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (429,47,'NAME','email');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (430,47,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (431,47,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (432,47,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (433,47,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (434,47,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (435,47,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (436,47,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (437,47,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (438,47,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (439,47,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (440,47,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (441,47,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (442,47,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (443,47,'PLACEHOLDER','Email');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (444,47,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (445,47,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (446,48,'NAME','vehicle_intend');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (447,48,'CAPTION','Do you intend to bring a vehicle?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (448,48,'ITEMS','Yes\r\nNo\r\nNot Sure');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (449,48,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (450,48,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (451,48,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (452,48,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (453,48,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (454,48,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (455,49,'NAME','vehicle_tow');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (456,49,'CAPTION','Does your vehicle have towing capability?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (457,49,'ITEMS','Yes\r\nNo\r\nNot Sure');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (458,49,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (459,49,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (460,49,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (461,49,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (462,49,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (463,49,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (478,51,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (477,51,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (476,51,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (475,51,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (474,51,'CAPTION','What is your vehicle towing capacity?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (473,51,'NAME','vehicle_towing_capacity');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (479,51,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (480,51,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (481,51,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (482,51,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (483,51,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (484,51,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (485,51,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (486,51,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (487,51,'PLACEHOLDER','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (488,51,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (489,51,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (490,52,'NAME','departure_time');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (491,52,'CAPTION','Can you stay until the event ends, Monday September 4th? ');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (492,52,'ITEMS','Yes\r\nNo\r\nMaybe');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (493,52,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (494,52,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (495,52,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (496,52,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (497,52,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (498,52,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (499,53,'NAME','contact_phone');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (500,53,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (501,53,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (502,53,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (503,53,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (504,53,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (505,53,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (506,53,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (507,53,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (508,53,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (509,53,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (510,53,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (511,53,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (512,53,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (513,53,'PLACEHOLDER','Cell Phone');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (514,53,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (515,53,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (516,54,'NAME','previously_attended');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (517,54,'CAPTION','Are you a Virgin (Have you gone to Burning Man before)?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (518,54,'ITEMS','Yes\r\nNo');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (519,54,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (520,54,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (521,54,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (522,54,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (523,54,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (524,54,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (525,55,'NAME','years_attended');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (526,55,'CAPTION','What years have you attended?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (527,55,'ITEMS','2016\r\n2014\r\n2013\r\n2012\r\n2011\r\n2010\r\n2009\r\n2008\r\n2007\r\n2006\r\n2005\r\n2004\r\n2003\r\n2002\r\n2001\r\n2000');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (528,55,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (529,55,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (530,55,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (531,55,'SIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (532,55,'MULTIPLE','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (533,55,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (534,55,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (535,56,'NAME','hometown');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (536,56,'CAPTION','What is your Home Town (Where will you be leaving from)');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (537,56,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (538,56,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (539,56,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (540,56,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (541,56,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (542,56,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (543,56,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (544,56,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (545,56,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (546,56,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (547,56,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (548,56,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (549,56,'PLACEHOLDER','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (550,56,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (551,56,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (552,57,'NAME','vehicle_seats_available');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (553,57,'CAPTION','How many seats are available?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (554,57,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (555,57,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (556,57,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (557,57,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (558,57,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (559,57,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (560,57,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (561,57,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (562,57,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (563,57,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (564,57,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (565,57,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (566,57,'PLACEHOLDER','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (567,57,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (568,57,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (569,58,'NAME','low_income_tickets');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (570,58,'CAPTION','Will you be applying for a Low Income ticket?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (571,58,'ITEMS','Yes\r\nNo');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (572,58,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (573,58,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (574,58,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (575,58,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (576,58,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (577,58,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (578,59,'NAME','submit');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (579,59,'LABEL','Submit');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (580,59,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (581,59,'RESET','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (582,59,'RESETLABEL','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (583,59,'PREVBUTTON','< Prev');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (584,59,'DISPLAYPROGRESS','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (585,59,'DISPLAYPROGRESSMSG','<div>\r\n <p><em>Page <strong>{page}</strong> of {total}</em></p>\r\n <div class=\"rsformProgressContainer\">\r\n  <div class=\"rsformProgressBar\" style=\"width: {percent}%;\"></div>\r\n </div>\r\n</div>');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (586,59,'BUTTONTYPE','TYPEBUTTON');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (587,59,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (588,59,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (589,60,'NAME','fname');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (590,60,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (591,60,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (592,60,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (593,60,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (594,60,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (595,60,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (596,60,'VALIDATIONMESSAGE','Please enter your name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (597,60,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (598,60,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (599,60,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (600,60,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (601,60,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (602,60,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (603,60,'PLACEHOLDER','First Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (604,60,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (605,60,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (606,61,'NAME','lname');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (607,61,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (608,61,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (609,61,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (610,61,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (611,61,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (612,61,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (613,61,'VALIDATIONMESSAGE','Please enter your name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (614,61,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (615,61,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (616,61,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (617,61,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (618,61,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (619,61,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (620,61,'PLACEHOLDER','Last Name');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (621,61,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (622,61,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (623,62,'NAME','email');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (624,62,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (625,62,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (626,62,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (627,62,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (628,62,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (629,62,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (630,62,'VALIDATIONMESSAGE','Please enter a valid email.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (631,62,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (632,62,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (633,62,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (634,62,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (635,62,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (636,62,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (637,62,'PLACEHOLDER','Email');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (638,62,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (639,62,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (640,63,'NAME','address_1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (641,63,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (642,63,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (643,63,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (644,63,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (645,63,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (646,63,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (647,63,'VALIDATIONMESSAGE','Please enter an address.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (648,63,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (649,63,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (650,63,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (651,63,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (652,63,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (653,63,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (654,63,'PLACEHOLDER','Address');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (655,63,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (656,63,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (657,64,'NAME','address_2');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (658,64,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (659,64,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (660,64,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (661,64,'REQUIRED','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (662,64,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (663,64,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (664,64,'VALIDATIONMESSAGE','Please enter an address.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (665,64,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (666,64,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (667,64,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (668,64,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (669,64,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (670,64,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (671,64,'PLACEHOLDER','Address');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (672,64,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (673,64,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (674,65,'NAME','city');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (675,65,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (676,65,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (677,65,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (678,65,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (679,65,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (680,65,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (681,65,'VALIDATIONMESSAGE','Please enter a city.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (682,65,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (683,65,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (684,65,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (685,65,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (686,65,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (687,65,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (688,65,'PLACEHOLDER','City');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (689,65,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (690,65,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (691,66,'NAME','country');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (692,66,'CAPTION','Country');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (693,66,'ITEMS','Afghanistan\nAlbania\nAlgeria\nAndorra\nAngola\nAntigua and Barbuda\nArgentina\nArmenia\nAustralia\nAustria\nAzerbaijan\nBahamas\nBahrain\nBangladesh\nBarbados\nBelarus\nBelgium\nBelize\nBenin\nBhutan\nBolivia\nBosnia and Herzegovina\nBotswana\nBrazil\nBrunei\nBulgaria\nBurkina Faso\nBurundi\nCabo Verde\nCambodia\nCameroon\nCanada\nCentral African Republic (CAR)\nChad\nChile\nChina\nColombia\nComoros\nDemocratic Republic of the Congo\nRepublic of the Congo\nCosta Rica\nCote d\'Ivoire\nCroatia\nCuba\nCyprus\nCzech Republic\nDenmark\nDjibouti\nDominica\nDominican Republic\nEcuador\nEgypt\nEl Salvador\nEquatorial Guinea\nEritrea\nEstonia\nEthiopia\nFiji\nFinland\nFrance\nGabon\nGambia\nGeorgia\nGermany\nGhana\nGreece\nGrenada\nGuatemala\nGuinea\nGuinea-Bissau\nGuyana\nHaiti\nHonduras\nHungary\nIceland\nIndia\nIndonesia\nIran\nIraq\nIreland\nIsrael\nItaly\nJamaica\nJapan\nJordan\nKazakhstan\nKenya\nKiribati\nKosovo\nKuwait\nKyrgyzstan\nLaos\nLatvia\nLebanon\nLesotho\nLiberia\nLibya\nLiechtenstein\nLithuania\nLuxembourg\nMacedonia (FYROM)\nMadagascar\nMalawi\nMalaysia\nMaldives\nMali\nMalta\nMarshall Islands\nMauritania\nMauritius\nMexico\nMicronesia\nMoldova\nMonaco\nMongolia\nMontenegro\nMorocco\nMozambique\nMyanmar (Burma)\nNamibia\nNauru\nNepal\nNetherlands\nNew Zealand\nNicaragua\nNiger\nNigeria\nNorth Korea\nNorway\nOman\nPakistan\nPalau\nPalestine\nPanama\nPapua New Guinea\nParaguay\nPeru\nPhilippines\nPoland\nPortugal\nQatar\nRomania\nRussia\nRwanda\nSaint Kitts and Nevis\nSaint Lucia\nSaint Vincent and the Grenadines\nSamoa\nSan Marino\nSao Tome and Principe\nSaudi Arabia\nSenegal\nSerbia\nSeychelles\nSierra Leone\nSingapore\nSlovakia\nSlovenia\nSolomon Islands\nSomalia\nSouth Africa\nSouth Korea\nSouth Sudan\nSpain\nSri Lanka\nSudan\nSuriname\nSwaziland\nSweden\nSwitzerland\nSyria\nTaiwan\nTajikistan\nTanzania\nThailand\nTimor-Leste\nTogo\nTonga\nTrinidad and Tobago\nTunisia\nTurkey\nTurkmenistan\nTuvalu\nUganda\nUkraine\nUnited Arab Emirates (UAE)\nUnited Kingdom (UK)\nUnited States of America (USA)[c]\nUruguay\nUzbekistan\nVanuatu\nVatican City (Holy See)\nVenezuela\nVietnam\nYemen\nZambia\nZimbabwe');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (694,66,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (695,66,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (696,66,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (697,66,'SIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (698,66,'MULTIPLE','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (699,66,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (700,66,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (701,67,'NAME','state');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (702,67,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (703,67,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (704,67,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (705,67,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (706,67,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (707,67,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (708,67,'VALIDATIONMESSAGE','Please enter a state.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (709,67,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (710,67,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (711,67,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (712,67,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (713,67,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (714,67,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (715,67,'PLACEHOLDER','State');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (716,67,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (717,67,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (718,68,'VALIDATIONMESSAGE','Invalid Input');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (719,68,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (720,68,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (721,68,'ITEMS','Yes\nMaybe\nNo');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (722,68,'CAPTION','Are you intending to camp with Mycodelic Forest in 2018?');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (723,68,'NAME','attending');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (724,68,'FLOW','HORIZONTAL');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (725,68,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (726,68,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (727,69,'NAME','Submit');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (728,69,'LABEL','Submit');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (729,69,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (730,69,'RESET','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (731,69,'RESETLABEL','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (732,69,'PREVBUTTON','< Prev');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (733,69,'DISPLAYPROGRESS','NO');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (734,69,'DISPLAYPROGRESSMSG','<div>\n <p><em>Page <strong>{page}</strong> of {total}</em></p>\n <div class=\"rsformProgressContainer\">\n  <div class=\"rsformProgressBar\" style=\"width: {percent}%;\"></div>\n </div>\n</div>');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (735,69,'BUTTONTYPE','TYPEBUTTON');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (736,69,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (737,69,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (738,70,'NAME','zipcode');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (739,70,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (740,70,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (741,70,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (742,70,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (743,70,'VALIDATIONRULE','none');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (744,70,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (745,70,'VALIDATIONMESSAGE','Please enter a zipcode.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (746,70,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (747,70,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (748,70,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (749,70,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (750,70,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (751,70,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (752,70,'PLACEHOLDER','Zipcode');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (753,70,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (754,70,'EMAILATTACH','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (755,71,'NAME','cell_phone');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (756,71,'CAPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (757,71,'DEFAULTVALUE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (758,71,'DESCRIPTION','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (759,71,'REQUIRED','YES');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (760,71,'VALIDATIONRULE','phonenumber');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (761,71,'VALIDATIONEXTRA','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (762,71,'VALIDATIONMESSAGE','Please enter a valid phone number.');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (763,71,'INPUTTYPE','text');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (764,71,'ATTRMIN','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (765,71,'ATTRMAX','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (766,71,'ATTRSTEP','1');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (767,71,'SIZE','20');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (768,71,'MAXSIZE','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (769,71,'PLACEHOLDER','Cell Phone');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (770,71,'ADDITIONALATTRIBUTES','');
INSERT INTO `jos_rsform_properties` (`PropertyId`, `ComponentId`, `PropertyName`, `PropertyValue`) VALUES (771,71,'EMAILATTACH','');
/*!40000 ALTER TABLE `jos_rsform_properties` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

