
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_kunena_topics`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_kunena_topics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_id` int(11) NOT NULL DEFAULT '0',
  `subject` tinytext,
  `icon_id` int(11) NOT NULL DEFAULT '0',
  `label_id` int(11) NOT NULL DEFAULT '0',
  `locked` tinyint(4) NOT NULL DEFAULT '0',
  `hold` tinyint(4) NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL DEFAULT '0',
  `posts` int(11) NOT NULL DEFAULT '0',
  `hits` int(11) NOT NULL DEFAULT '0',
  `attachments` int(11) NOT NULL DEFAULT '0',
  `poll_id` int(11) NOT NULL DEFAULT '0',
  `moved_id` int(11) NOT NULL DEFAULT '0',
  `first_post_id` int(11) NOT NULL DEFAULT '0',
  `first_post_time` int(11) NOT NULL DEFAULT '0',
  `first_post_userid` int(11) NOT NULL DEFAULT '0',
  `first_post_message` text,
  `first_post_guest_name` tinytext,
  `last_post_id` int(11) NOT NULL DEFAULT '0',
  `last_post_time` int(11) NOT NULL DEFAULT '0',
  `last_post_userid` int(11) NOT NULL DEFAULT '0',
  `last_post_message` text,
  `last_post_guest_name` tinytext,
  `rating` tinyint(6) NOT NULL DEFAULT '0',
  `params` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`),
  KEY `locked` (`locked`),
  KEY `hold` (`hold`),
  KEY `posts` (`posts`),
  KEY `hits` (`hits`),
  KEY `first_post_userid` (`first_post_userid`),
  KEY `last_post_userid` (`last_post_userid`),
  KEY `first_post_time` (`first_post_time`),
  KEY `last_post_time` (`last_post_time`),
  KEY `last_post_id` (`last_post_id`)
) ENGINE=InnoDB AUTO_INCREMENT=335 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_kunena_topics` WRITE;
/*!40000 ALTER TABLE `jos_kunena_topics` DISABLE KEYS */;
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (2,2,'Welcome please introduce yourself here.',0,0,0,0,0,1,458,0,0,0,2,1442976531,71,'I am the Wizard.   I have 5 burns under my belt.  My job is to make things happen both on the Playa and back in the default world. I am a moop master, as well as a macgyver 2nd degree.','thewizard',2,1442976531,71,'I am the Wizard.   I have 5 burns under my belt.  My job is to make things happen both on the Playa and back in the default world. I am a moop master, as well as a macgyver 2nd degree.','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (3,3,'Bitch Session',0,0,0,0,0,1,448,0,0,0,3,1442977030,71,'did you have a problem last year?  \r\nPost you mega hangups here so we can try to come up with a solution.\r\nI don\'t want petty bickering or blaming.   lets keep it  focused on how an experience caused you inconvenience.','thewizard',3,1442977030,71,'did you have a problem last year?  \r\nPost you mega hangups here so we can try to come up with a solution.\r\nI don\'t want petty bickering or blaming.   lets keep it  focused on how an experience caused you inconvenience.','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (4,7,'Dancing Mushrooms',0,0,0,0,0,1,316,0,0,0,4,1442977265,71,'We need to make more dancing mushrooms for next year.  Anyone want to help?','thewizard',4,1442977265,71,'We need to make more dancing mushrooms for next year.  Anyone want to help?','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (5,8,'Website Sections',0,0,0,0,0,7,56,0,0,0,5,1442977486,43,'Hey Nobody,\r\n\r\nWe need to figure out what the Main Menu of the site should be. We can use this post to brainstorm the different types of features and menu items we might want on the site. New categories can be created if we need to get more specific. This thread is just for ideas for features.\r\n\r\n     - Trevor','trevorbice',24,1458099904,71,'We need a chat Function  :(','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (6,10,'Should we make an art piece for this year?',0,0,0,0,0,1,72,0,0,0,10,1443145989,71,'The deadline for art proposals is some time in November. If we want to get tickets with an art piece we need a solid proposal by then. Any  Thoughts?','thewizard',10,1443145989,71,'The deadline for art proposals is some time in November. If we want to get tickets with an art piece we need a solid proposal by then. Any  Thoughts?','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (7,8,'Other Theme Camp Websites',0,0,0,0,0,2,56,0,0,0,11,1443149653,43,'Here are a few other big theme camp websites to help us formulate some ideas:\r\n\r\nhttp://www.campquestionmark.com/\r\nhttp://www.slutgarden.net/\r\nhttp://sacredspacesvillage.org/\r\n\r\nPost any more you can find here so we can get an idea of what other camps do!','trevorbice',13,1444145805,71,'polyparadise - http://polyparadise.azcompuguy.com/\r\n\r\nPlaya surfers - http://www.playasurfers.com/\r\n\r\n Lip bomb- http://www.booms-box.com/about.html','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (8,8,'Links',0,0,0,0,0,2,40,0,0,0,12,1444145624,71,'A place to post links related to mushrooms Burning man, and other places that seem relevant\r\namazing mushroom pics\r\n[url=http://all-that-is-interesting.com/coolest-mushrooms]http://all-that-is-interesting.com/coolest-mushrooms [/url]','thewizard',15,1444578828,71,'https://www.minds.com/blog/view/295083011345485824/psychedelic-mushroom-compound-found-to-grow-and-repair-brain-cells','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (9,17,'How do we make decisions',0,0,0,0,0,3,7,0,0,0,14,1444150740,71,'I am of the opinion that we need to have 5 \"elders\" that make the final decisions... And to make any decisions we need consensus of the five. we can use this forum to discuss the pro and cons.  \r\nmy proposal for elders is\r\nTrevor\r\nDavid \r\nAlyea\r\nRachael\r\nSandor \r\n\r\nAny ideas?','thewizard',56,1460171652,43,'5 is a good number I think','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (10,3,'Things we want or need',0,0,0,0,0,2,515,0,0,0,16,1457496262,71,'Post links here to things that would be nice to have. Please be as elaborate as necessary, and what it would be for.','thewizard',17,1457496317,71,'Chauvet DJ SlimPAR 56 \r\n[img size=100]http://www.sweetwater.com/images/items/750/SlimPAR56-large.jpg[/img]\r\nhttp://www.sweetwater.com/store/detail/SlimPAR56\r\n\r\nId like to get 2 for the dj area...','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (11,11,'Mushrooms',0,0,0,0,0,4,20,1,0,0,19,1457498934,71,'Post any links to mushroom related things here','thewizard',34,1459192508,43,'I\'ve attached a quick SketchUp for some possible Mushroom Tower designs out of Plywood.','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (12,7,'Shade Structures',0,0,0,0,0,3,713,0,0,0,21,1458066856,71,'The t shaped shade stuctures \r\n http://wpstore.formandreform.com/blackrock-hardware-2/','thewizard',23,1458067908,71,'Lets look for scaffolding  as well, this might be a solution for the parachute','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (13,2,'Chatter',0,0,0,0,0,3,512,0,0,0,25,1458100169,71,'Talk about random ideas here.  like what to do with all that Playa you have saved in all your stuff that has not been unpacked...or other random shenanigans','thewizard',392,1488660755,80,'Definitely a tower. Theme tent would be nice too, but I think tower is a grander attraction. More fun.','Artemis',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (14,3,'Suggested Products',0,0,0,0,0,2,378,0,0,0,26,1458840260,71,'post products you think need our recommendation here','thewizard',27,1458840289,71,'http://www.amazon.com/dp/B00CAAXWQ2?m=AIUNJRVMY9D6B&ref_=v_sp_widget_detail_page','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (15,8,'Homepage Content',0,0,0,0,0,4,2,0,0,0,28,1459135853,43,'Current Homepage content:\r\n\r\n[quote]We are The Mycodelic Forest, a Burning Man theme camp located around the 3\'oclock sector in Black Rock City. \r\n\r\nWe are a group of dedicated, civic minded burners that believe in the interconnectedness of all organisms. Our group has been attending Burning Man as The Mycodelic Forest for the past 2 years, but spent a year before that as The Enchanted Forest Funki.\r\n\r\nThis website is a place to learn about all things related to the Mycodelic Forest Burning Man theme camp and to organize and coordinate our members. If you would like to contribute, in any form, to the Mycodelic Forest, please proceed to our forum to discuss anything camp related.[/quote]','trevorbice',31,1459137169,43,'test','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (16,3,'Evaptron Turbine',0,0,0,0,0,2,613,0,0,0,32,1459150639,43,'https://www.youtube.com/watch?v=MYYK1aalNE8','experthumanpilot',42,1459524682,71,'thats supper cool... how do we use the energy...','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (17,19,'2016 Budet',0,0,0,0,0,6,22,0,0,0,35,1459198512,43,'Lets get a budget discussion started for 2016!\r\n\r\nHow many camp members do we anticipate this year?','experthumanpilot',67,1467858833,43,'Hey guys, I\'ve set up a google doc to handle this while we work out what we can afford.\r\nhttps://docs.google.com/spreadsheets/d/1PPS6LBz0t_M3-uLPyk26AV8Kk98Ro1bbPHdoysX1Gyg/edit?usp=sharing','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (18,19,'2015 Budet',0,0,0,0,0,2,11,0,0,0,38,1459200865,43,'Just posting this for reference:\r\n\r\n\r\n[table]\r\n  [tr]\r\n    [td]Disinfecting Wipes (for dishes)[/td]\r\n    [td]$36.00[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]30 Gallon Garbage Bags[/td]\r\n    [td]$23.48[/td]\r\n  [/tr]\r\n[tr]\r\n    [td]Bleach 64 Ounces (for Evaptron)[/td]\r\n    [td]$11.12[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]Rubber Gloves (for touching things) [/td]\r\n    [td]$21.90[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]Trailer Transportation Gas (2 trailers)[/td]\r\n    [td]$560.00[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]Music Gas (generator gas, tank a day)[/td]\r\n    [td]$100.00[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]Propane (10 gallons)[/td]\r\n    [td]$40.00[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]30 Gallon Grey water Reservoire[/td]\r\n    [td]$156.83[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]Grey water Disposal Fee[/td]\r\n    [td]$10.00[/td]\r\n  [/tr]\r\n  [tr]\r\n    [td]Trash Disposal Fees[/td]\r\n    [td]$40.00[/td]\r\n  [/tr]\r\n[/table]\r\n\r\nTOTAL: [b]999.65[/b]','experthumanpilot',40,1459201194,75,'Ok I can update this list.','aylea',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (19,2,'2016 Vehicles',0,0,1,0,0,5,401,0,0,0,41,1459451730,43,'Hey everyone I just wanted to start getting a solid plan together of everyone who will be driving this year. That way we can make sure all our stuff, and all our people make it out to the Playa!\r\n\r\nIf you are bringing a vehicle, please just post the make,model, type of vehicle and available seats (if any).','experthumanpilot',74,1470793593,43,'Kate, it sounds like you will be able to make a detour up here to collect our main trailer? We are now expecting to not have access to the Truck that was going to be towing it due to one of our core members being unable to attend!','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (20,21,'READ FIRST - Events Due by June 18th',1,0,0,0,1,4,5,0,0,0,44,1459724130,43,'We have had some bad luck with getting our events published into the Burning Man book every year, but this year we are going to be more organized than ever! Anyone who is planning, or would like to propose an event should post a new thread in this forum category.  Please provide as much information as possible about your idea!\r\n\r\nhttp://playaevents.burningman.org/\r\n[quote]The form to submit your playa events to the Playa Events Directory (part of the Playa Info Directory) will be available for submissions starting on June 18 around 12pm noon PD. Check back then\r\n[/quote]','experthumanpilot',66,1467314195,71,'Purple party, 8 - 9 FRI\r\n 90s party Mon 9-10\r\nstory time Wed 7pm\r\n Beer   Mon: Thurs sun: 3:30- 4:45\r\nAll submitted, We can edit them , we can also make an event url to be posted in the online version for them if we want...','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (21,13,'BUYING / SELLING TICKETS',1,0,1,0,0,1,4,0,0,0,45,1459730178,43,'We do have some extra tickets available this year, but we also want to make sure all our family trying to get tickets gets them! Please post if you have extra tickets, and if you are looking for tickets!','experthumanpilot',45,1459730178,43,'We do have some extra tickets available this year, but we also want to make sure all our family trying to get tickets gets them! Please post if you have extra tickets, and if you are looking for tickets!','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (22,8,'Products to Reccomend',0,0,0,0,0,7,5,0,0,0,46,1459971429,43,'I\'m trying to get a more comprehensive list of some o the really good Burning Man proof gear that our camp has \'tested\'. Many times, stuff is just not up to the challenge of Burning Man! Those Tracer 360\'s are really awesome.\r\n\r\nLets try to get a list of all the that good gear we\'ve used, and then maybe people can take turns writing the actual review articles? I can help organize this but I just want to get a list together.','experthumanpilot',54,1459977368,43,'Fix anything with Q-Bond\r\nhttp://www.amazon.com/Bond-Repair-Small-Bonding-Adhesive/dp/B004KAGKC8/ref=sr_1_2?ie=UTF8&qid=1459977209&sr=8-2&keywords=Q-Bond','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (23,2,'Burning Man Tips',0,0,0,0,0,3,424,0,0,0,52,1459973137,43,'This needs to be a little better thought out, but my idea was to have a bunch of our Burning Man Lifehacks that we\'ve learned over the years. Like why we put our clothing in plastic bags, and putting Vinegar in your hair so you can comb it.\r\n\r\nI just want to get a list of ideas together, and we can work on getting good content together relating to each one. Its will be a list of tips that we\'ve learned and want to pass on to Virgin members...or anyone else who might find them useful!','experthumanpilot',60,1461085428,71,'Keep a clean set of clothes in a plastic bag for after you get  out of line and on the road.  Clean under things are so nice when your are super dirty.  And you will not look so dusty, so you can pass for normal, if you need to. \r\n Also put a 20$ bill in there so you can stop and get food if the ATM\'s are closed. midnight tri tip is one of my favorite post  BM traditions.','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (24,18,'Moop Sticks',0,0,0,0,0,1,3,0,0,0,57,1461084750,71,'I like the folding ones... but the hinge is prone to break. but these can pick up gross cigarette butts without touching\r\nhttp://www.amazon.com/Ontel-Products-GOPMO2-Deluxe-Reaching/dp/B00006K157/ref=sr_1_9_s_it?s=hpc&ie=UTF8&qid=1461084408&sr=1-9','thewizard',57,1461084750,71,'I like the folding ones... but the hinge is prone to break. but these can pick up gross cigarette butts without touching\r\nhttp://www.amazon.com/Ontel-Products-GOPMO2-Deluxe-Reaching/dp/B00006K157/ref=sr_1_9_s_it?s=hpc&ie=UTF8&qid=1461084408&sr=1-9','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (25,18,'Solar Lights',0,0,0,0,0,1,2,0,0,0,58,1461084880,71,'I love the Sun Kings... they are so easy and they have USB chargers on them.\r\nhttp://www.amazon.com/King-Portable-Solar-Lantern-Charger/dp/B00CAAXWQ2/ref=sr_1_1?ie=UTF8&qid=1461084772&sr=8-1&keywords=solar+king','thewizard',58,1461084880,71,'I love the Sun Kings... they are so easy and they have USB chargers on them.\r\nhttp://www.amazon.com/King-Portable-Solar-Lantern-Charger/dp/B00CAAXWQ2/ref=sr_1_1?ie=UTF8&qid=1461084772&sr=8-1&keywords=solar+king','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (26,18,'Dust masks',0,0,0,0,0,1,2,0,0,0,59,1461085076,71,'I love the RZ dustmask when the dust gets too bad.   not great when its hot or you want to drink... but easy to carry \r\n\r\nhttp://www.amazon.com/RZ-Mask-Filters-Black-Regular/dp/B0054LH4W2/ref=sr_1_1?ie=UTF8&qid=1461084978&sr=8-1&keywords=rz+dust+mask','thewizard',59,1461085076,71,'I love the RZ dustmask when the dust gets too bad.   not great when its hot or you want to drink... but easy to carry \r\n\r\nhttp://www.amazon.com/RZ-Mask-Filters-Black-Regular/dp/B0054LH4W2/ref=sr_1_1?ie=UTF8&qid=1461084978&sr=8-1&keywords=rz+dust+mask','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (27,18,'Air Mattress',0,0,0,0,0,2,2,0,0,0,62,1463153270,71,'I have had a few Intex air mattress and they last  about 2 years... with a mattress topper and comforter, I never popped one, even when I\'ve been rambunctious on it.  after 2 years they stop holding air, and have to be refilled throughout the night. \r\n\r\nhttp://www.amazon.com/Intex-Pillow-Raised-Airbed-Electric/dp/B000HBMFRS/ref=sr_1_5?ie=UTF8&qid=1463153115&sr=8-5&keywords=air+mattres','thewizard',65,1463344835,71,'http://www.amazon.com/dp/B007X099EI/ref=twister_dp_update?_encoding=UTF8&psc=1\r\n\r\nhttp://www.amazon.com/ALPS-Mountaineering-7632117-Velocity-Queen/dp/B00HS7IWRQ/ref=sr_1_18?s=sporting-goods&ie=UTF8&qid=1463344732&sr=1-18&keywords=ALPS+Mountaineering','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (28,11,'Mushroom Lamps',0,0,0,0,0,1,1,0,0,0,68,1468040771,43,'https://www.youtube.com/watch?v=D5LjGFkpApw&feature=youtu.be&ab_channel=DIYPerks','experthumanpilot',68,1468040771,43,'https://www.youtube.com/watch?v=D5LjGFkpApw&feature=youtu.be&ab_channel=DIYPerks','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (29,11,'Acryllic 3D Illusion Lamp',0,0,0,0,0,1,1,0,0,0,69,1468040834,43,'https://www.youtube.com/watch?v=c6mKMpPe8xg&ab_channel=techydiy','experthumanpilot',69,1468040834,43,'https://www.youtube.com/watch?v=c6mKMpPe8xg&ab_channel=techydiy','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (30,13,'Who Still Needs Tickets?',0,0,1,0,0,1,2,0,0,0,70,1469151081,43,'Please just reply to this thread if you are a camp member, and you are still looking for a ticket. There are still a few left, but we really want to make sure everyone is set before we start selling them to potential friends/family not camping with us.','experthumanpilot',70,1469151081,43,'Please just reply to this thread if you are a camp member, and you are still looking for a ticket. There are still a few left, but we really want to make sure everyone is set before we start selling them to potential friends/family not camping with us.','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (31,3,'Proposed Group Photo Times',0,0,0,0,0,1,389,0,0,0,73,1470793458,43,'So we\'ve been a little haphazard about this previous years, so this year I want to make sure everyone is on the same page about when and where we will be doing group photos. I am proposing we have a few pre-designated times, that way even if we miss one we can still be on others!\r\n\r\nMonday: 4:00 PM?\r\n??\r\nPre-Man Burn?\r\nPre-Temple Burn?\r\n\r\nAny other suggestions?\r\n\r\nWe also need to make sure we do a good job of documenting the camp this year!','experthumanpilot',73,1470793458,43,'So we\'ve been a little haphazard about this previous years, so this year I want to make sure everyone is on the same page about when and where we will be doing group photos. I am proposing we have a few pre-designated times, that way even if we miss one we can still be on others!\r\n\r\nMonday: 4:00 PM?\r\n??\r\nPre-Man Burn?\r\nPre-Temple Burn?\r\n\r\nAny other suggestions?\r\n\r\nWe also need to make sure we do a good job of documenting the camp this year!','experthumanpilot',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (323,13,'DGS Tickets 2017',0,0,0,0,0,2,11,0,0,0,366,1487585671,43,'Also, just a reminder we need members able to purchase DGS  (Directed Group Sale) tickets for Core Camp members. Please message me if you are willing to help set up / break down / early arrival. We are asking members who are willing to do DGS to buy two tickets to ensure all our Team can get to the Playa. This gives you much better odds of getting a ticket, but comes with some responsibilities!\r\n\r\nWe need to get registered by February 24th!','Trailblazer',379,1488227339,43,'So there were a few glitches with getting our all the DGS ticket invites, but at this point I think we have four people able to purchase tickets. That would be Me, Rachael, Kate, and Malachi. This will get us 8 tickets.\r\n\r\nMy extra ticket will be going to Alex Newman who has said he could be part of the core team.','Trailblazer',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (324,2,'Eclipse Fest 2017',0,0,0,0,0,9,360,0,0,0,367,1487656688,71,'Should we take the Mycodelic forest  Camp to the  Eclipse gathering?','thewizard',391,1488660700,80,'I LOVE the idea of getting a tower','Artemis',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (325,2,'2017 Weekly Camp Meetings',0,0,0,0,0,6,323,0,0,0,369,1487800702,43,'Can people weigh in on when is a good time for Weekly Camp Meetings? We will be doing this over the phone, and most meetings take between 30 min and an hour. If you are part of our core team, you should try to make these regularly! \r\n\r\nMaybe Sunday nights?','Trailblazer',390,1488660596,80,'7pm Sunday totally works for me. Jazzed.','Artemis',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (326,2,'Playa Tips',0,0,0,0,0,2,299,0,0,0,371,1487891427,43,'I\'ve been talking about this for ages! Please post ideas for tips to save here.','Trailblazer',372,1487891556,43,'Tip for keeping cool: dip your Shemahg in ice cold cooler water and wrap around your neck!','Trailblazer',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (327,18,'Things the Camp should consider getting',0,0,0,0,0,2,9,0,0,0,374,1488078540,71,'See some great idea out in the default webs,\r\n Put your ideas that might be fun/ useful  at the event here.','thewizard',375,1488078625,71,'http://www.stagelightingstore.com/Applied-NN-12x12-Heavy-Duty-Tower-Truss-10-ft?sc=41&category=794455','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (328,2,'Wizard Beer 2017',0,0,0,0,0,2,296,0,0,0,380,1488229179,43,'I would still like to bring homebrew beer, and do a beer tasting. Wizard, I am not sure what your schedule would be like but could we give you some money to brew beer again this year?','Trailblazer',383,1488298709,71,'maybe... the brewery is still moving forward. looking at Eureka, and if we open by August I will be able to get cheap beer, same recipe. if no i might have time, to brew','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (329,17,'Mission',0,0,0,0,0,4,7,0,0,0,393,1488814399,71,'The first idea of our mission\r\n\r\nThe mycodellic forest creating a sustainable environment one forest at a time...','thewizard',397,1488940544,71,'I like both \r\nThe mycodellic forest creating a sustainable environment one forest at a time:\r\n         Educating the world about renewable energy and sustainable living.','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (330,22,'a nonprofit.',0,0,0,0,0,1,3,0,0,0,394,1488860733,71,'Lets turn the mycodelic forest into a nonprofit that goes to events and throws events, while educating about sustainability...Ideas?','thewizard',394,1488860733,71,'Lets turn the mycodelic forest into a nonprofit that goes to events and throws events, while educating about sustainability...Ideas?','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (331,2,'GLC - how do we spread the BM ethos.',0,0,0,0,0,1,373,0,0,0,398,1491233072,71,'http://www.burn.life/blog/burning-mans-culture-is-in-danger\r\n\r\n\r\nwhat can we as a camp do to combat consumerist culture. \r\nlast year we talked about random PSA\'s...\r\nI like the idea of assigning bergins to non friends. \r\nMoop competitions,\r\nRewards for good civic duty. ( maybe a call out reward...) who can stop the most bad behavior. \r\notherideas?','thewizard',398,1491233072,71,'http://www.burn.life/blog/burning-mans-culture-is-in-danger\r\n\r\n\r\nwhat can we as a camp do to combat consumerist culture. \r\nlast year we talked about random PSA\'s...\r\nI like the idea of assigning bergins to non friends. \r\nMoop competitions,\r\nRewards for good civic duty. ( maybe a call out reward...) who can stop the most bad behavior. \r\notherideas?','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (333,11,'DJ booth',0,0,0,0,0,1,2,0,0,0,400,1492981268,71,'https://drive.google.com/file/d/0B1jl1hIIBCIaSU1NRVA5VjY3UXFpMGp6TS1VS2xnUUZwZmE0/view?usp=sharing \r\na rough idea for a mushroom dj booth...','thewizard',400,1492981268,71,'https://drive.google.com/file/d/0B1jl1hIIBCIaSU1NRVA5VjY3UXFpMGp6TS1VS2xnUUZwZmE0/view?usp=sharing \r\na rough idea for a mushroom dj booth...','thewizard',0,'');
INSERT INTO `jos_kunena_topics` (`id`, `category_id`, `subject`, `icon_id`, `label_id`, `locked`, `hold`, `ordering`, `posts`, `hits`, `attachments`, `poll_id`, `moved_id`, `first_post_id`, `first_post_time`, `first_post_userid`, `first_post_message`, `first_post_guest_name`, `last_post_id`, `last_post_time`, `last_post_userid`, `last_post_message`, `last_post_guest_name`, `rating`, `params`) VALUES (334,2,'Importance of essay writing in education',0,0,0,3,0,1,17,0,0,0,401,1510557265,810,'Essay writing is the main task in education.  Essay writing is important because it is a reflection of your deepest thoughts and ideas. Many of the students are using the online writing services for their academic activities. Best essay writing service provides writing methods and guidelines for the students This service provide unique and high quality essays. The [url=https://waltessays.com/]best essay writing service[/url] is different from other online writing resources because of these unique services. Students can submit their essay according to their requirements.','Neal Wilson',401,1510557265,810,'Essay writing is the main task in education.  Essay writing is important because it is a reflection of your deepest thoughts and ideas. Many of the students are using the online writing services for their academic activities. Best essay writing service provides writing methods and guidelines for the students This service provide unique and high quality essays. The [url=https://waltessays.com/]best essay writing service[/url] is different from other online writing resources because of these unique services. Students can submit their essay according to their requirements.','Neal Wilson',0,'');
/*!40000 ALTER TABLE `jos_kunena_topics` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

