
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `jos_assets`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jos_assets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `parent_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Nested set parent.',
  `lft` int(11) NOT NULL DEFAULT '0' COMMENT 'Nested set lft.',
  `rgt` int(11) NOT NULL DEFAULT '0' COMMENT 'Nested set rgt.',
  `level` int(10) unsigned NOT NULL COMMENT 'The cached level in the nested tree.',
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The unique name for the asset.\n',
  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The descriptive title for the asset.',
  `rules` varchar(5120) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON encoded access control.',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_asset_name` (`name`),
  KEY `idx_lft_rgt` (`lft`,`rgt`),
  KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=531 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `jos_assets` WRITE;
/*!40000 ALTER TABLE `jos_assets` DISABLE KEYS */;
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (1,0,0,961,0,'root.1','Root Asset','{\"core.login.site\":{\"6\":1,\"2\":1},\"core.login.admin\":{\"6\":1},\"core.login.offline\":{\"6\":1},\"core.admin\":{\"8\":1},\"core.manage\":{\"7\":1},\"core.create\":{\"6\":1,\"3\":1},\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"core.edit.own\":{\"6\":1,\"3\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (2,1,1,2,1,'com_admin','com_admin','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (3,1,3,6,1,'com_banners','com_banners','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (4,1,7,8,1,'com_cache','com_cache','{\"core.admin\":{\"7\":1},\"core.manage\":{\"7\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (5,1,9,10,1,'com_checkin','com_checkin','{\"core.admin\":{\"7\":1},\"core.manage\":{\"7\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (6,1,11,12,1,'com_config','com_config','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (7,1,13,18,1,'com_contact','com_contact','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (8,1,19,90,1,'com_content','com_content','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (9,1,91,92,1,'com_cpanel','com_cpanel','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (10,1,93,94,1,'com_installer','com_installer','{\"core.admin\":[],\"core.manage\":{\"7\":0},\"core.delete\":{\"7\":0},\"core.edit.state\":{\"7\":0}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (11,1,95,96,1,'com_languages','com_languages','{\"core.admin\":{\"7\":1},\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (12,1,97,98,1,'com_login','com_login','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (13,1,99,100,1,'com_mailto','com_mailto','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (14,1,101,102,1,'com_massmail','com_massmail','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (15,1,103,104,1,'com_media','com_media','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":{\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (16,1,105,112,1,'com_menus','com_menus','{\"core.admin\":{\"7\":1},\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (17,1,113,114,1,'com_messages','com_messages','{\"core.admin\":{\"7\":1},\"core.manage\":{\"7\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (18,1,115,306,1,'com_modules','com_modules','{\"core.admin\":{\"7\":1},\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (19,1,307,310,1,'com_newsfeeds','com_newsfeeds','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (20,1,311,312,1,'com_plugins','com_plugins','{\"core.admin\":{\"7\":1},\"core.manage\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (21,1,313,314,1,'com_redirect','com_redirect','{\"core.admin\":{\"7\":1},\"core.manage\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (22,1,315,316,1,'com_search','com_search','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (23,1,317,318,1,'com_templates','com_templates','{\"core.admin\":{\"7\":1},\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (24,1,319,322,1,'com_users','com_users','{\"core.admin\":{\"7\":1},\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (25,1,323,326,1,'com_weblinks','com_weblinks','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (26,1,327,328,1,'com_wrapper','com_wrapper','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (27,8,20,25,2,'com_content.category.2','Uncategorised','{\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (28,3,4,5,2,'com_banners.category.3','Uncategorised','{\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (29,7,14,15,2,'com_contact.category.4','Uncategorised','{\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (30,19,308,309,2,'com_newsfeeds.category.5','Uncategorised','{\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (31,25,324,325,2,'com_weblinks.category.6','Uncategorised','{\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (32,24,320,321,1,'com_users.category.7','Uncategorised','{\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (33,1,329,330,1,'com_finder','com_finder','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (34,1,331,332,1,'com_joomlaupdate','com_joomlaupdate','{\"core.admin\":[],\"core.manage\":[],\"core.delete\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (35,1,333,334,1,'com_tags','com_tags','{\"core.admin\":[],\"core.manage\":[],\"core.manage\":[],\"core.delete\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (36,1,335,336,1,'com_contenthistory','com_contenthistory','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (37,1,337,338,1,'com_ajax','com_ajax','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (38,1,339,340,1,'com_postinstall','com_postinstall','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (39,18,116,117,2,'com_modules.module.1','Main Menu','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (40,18,118,119,2,'com_modules.module.2','Login','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (41,18,120,121,2,'com_modules.module.3','Popular Articles','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (42,18,122,123,2,'com_modules.module.4','Recently Added Articles','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (43,18,124,125,2,'com_modules.module.8','Toolbar','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (44,18,126,127,2,'com_modules.module.9','Quick Icons','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (45,18,128,129,2,'com_modules.module.10','Logged-in Users','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (46,18,130,131,2,'com_modules.module.12','Admin Menu','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (47,18,132,133,2,'com_modules.module.13','Admin Submenu','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (48,18,134,135,2,'com_modules.module.14','User Status','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (49,18,136,137,2,'com_modules.module.15','Title','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (50,18,138,139,2,'com_modules.module.16','Login Form','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (51,18,140,141,2,'com_modules.module.17','Breadcrumbs','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (52,18,142,143,2,'com_modules.module.79','Multilanguage status','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (53,18,144,145,2,'com_modules.module.86','Joomla Version','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (54,18,146,147,2,'com_modules.module.87','Popular Tags','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (55,18,148,149,2,'com_modules.module.88','Site Information','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (56,18,150,151,2,'com_modules.module.89','Release News','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (57,18,152,153,2,'com_modules.module.90','Latest Articles','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (58,18,154,155,2,'com_modules.module.91','User Menu','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (59,18,156,157,2,'com_modules.module.92','Image Module','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (60,18,158,159,2,'com_modules.module.93','Search','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (61,129,47,48,3,'com_content.article.1','Getting Started','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (62,1,341,342,1,'#__ucm_content.1','#__ucm_content.1','[]');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (63,1,343,344,1,'com_sh404sef','sh404sef','{\"core.admin\":[],\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (64,18,160,161,2,'com_modules.module.94','sh404sef control panel icon','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (65,8,26,29,2,'com_content.category.8','sh404SEF custom content','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (66,65,27,28,3,'com_content.article.2','__404__','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (67,1,345,346,1,'com_akeeba','akeeba','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (68,1,347,348,1,'com_rsform','rsform','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (69,1,349,350,1,'com_jce','jce','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (70,1,351,352,1,'com_roksprocket','roksprocket','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (71,18,162,163,2,'com_modules.module.95','RokSprocket Module','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (72,1,353,354,1,'com_xmap','com_xmap','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (73,1,355,356,1,'com_k2','com_k2','{\"core.admin\":[],\"core.manage\":[],\"core.create\":[],\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (74,18,164,165,2,'com_modules.module.96','K2 Comments','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (75,18,166,167,2,'com_modules.module.97','K2 Content','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (76,18,168,169,2,'com_modules.module.98','K2 Tools','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (77,18,170,171,2,'com_modules.module.99','K2 Users','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (78,18,172,173,2,'com_modules.module.100','K2 User','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (79,18,174,175,2,'com_modules.module.101','K2 Quick Icons (admin)','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (80,18,176,177,2,'com_modules.module.102','K2 Stats (admin)','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (81,18,178,179,2,'com_modules.module.103','TBWorks - Accordion','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (82,18,180,181,2,'com_modules.module.104','Grid GK5','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (83,18,182,183,2,'com_modules.module.105','News Show Pro GK5','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (84,18,184,185,2,'com_modules.module.106','Tabs GK5','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (85,18,186,187,2,'com_modules.module.107','Social GK5','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (86,129,49,50,3,'com_content.article.3','Home','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (87,129,51,52,3,'com_content.article.4','About Us','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (88,129,53,54,3,'com_content.article.5','Services','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (89,129,55,56,3,'com_content.article.6','Contact','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (91,1,357,358,1,'com_virtuemart_allinone','virtuemart_allinone','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (99,18,188,189,2,'com_modules.module.115','JoomGallery News','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (100,1,359,818,1,'com_joomgallery','joomgallery','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (101,18,190,191,2,'com_modules.module.116','JoomImages','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (102,18,192,193,2,'com_modules.module.117','JoomCategories','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (103,18,194,195,2,'com_modules.module.118','JoomSearch','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (104,18,196,197,2,'com_modules.module.119','JoomTreeview','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (105,18,198,199,2,'com_modules.module.120','Bottom Tabs','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (106,18,200,201,2,'com_modules.module.121','Latest News','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (107,18,202,203,2,'com_modules.module.122','Tab2','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (108,18,204,205,2,'com_modules.module.123','Donate','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (109,18,206,207,2,'com_modules.module.124','RSForm! Pro Module','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (110,18,208,209,2,'com_modules.module.125','Quick Contact','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (111,18,210,211,2,'com_modules.module.126','Site By','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (112,18,212,213,2,'com_modules.module.127','SP Social','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (113,18,214,215,2,'com_modules.module.128','Unite Revolution Slider 2','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (114,1,819,820,1,'com_uniterevolution2','com_uniterevolution2','{\"revolution2.slidersetting\":{\"7\":1},\"revolution2.slideroperations\":{\"7\":1},\"revolution2.slideoperations\":{\"7\":1},\"revolution2.editslide\":{\"7\":1} }');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (115,18,216,217,2,'com_modules.module.129','Social','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (116,18,218,219,2,'com_modules.module.130','Social','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (117,18,220,221,2,'com_modules.module.131','Contact Us','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (118,18,222,223,2,'com_modules.module.132','Logo','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (119,18,224,225,2,'com_modules.module.133','Home Slideshow','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (120,18,226,227,2,'com_modules.module.134','Sidebar Tabs','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (121,18,228,229,2,'com_modules.module.135','BT Google Maps','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (123,8,30,37,2,'com_content.category.9','Testimonials','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (124,123,31,32,3,'com_content.article.7','Sample Testimonial One','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (125,123,33,34,3,'com_content.article.8','Sample Testimonial Two','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (126,123,35,36,3,'com_content.article.9','Sample Testimonial Three','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (127,18,230,231,2,'com_modules.module.136','Testimonials','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (128,8,38,45,2,'com_content.category.10','Services','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (129,8,46,59,2,'com_content.category.11','Content','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (130,18,232,233,2,'com_modules.module.137','Header - About Us','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (131,18,234,235,2,'com_modules.module.138','Accordion - Services','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (132,128,39,40,3,'com_content.article.10','Sample Service Three','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (133,128,41,42,3,'com_content.article.11','Sample Service Two','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (134,128,43,44,3,'com_content.article.12','Sample Service One','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (135,129,57,58,3,'com_content.article.13','Typography','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (136,18,236,237,2,'com_modules.module.139','Footer Menu','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (137,18,238,239,2,'com_modules.module.140','Bottom Menu','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (138,18,240,241,2,'com_modules.module.141','Top Drawer - Phone','');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (139,18,242,243,2,'com_modules.module.142','Site By SDSBMS','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (146,18,244,245,2,'com_modules.module.143','Mobile Menu','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (147,1,821,822,1,'com_import','com_import','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (148,1,823,824,1,'com_jhackguard','com_jhackguard','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (150,1,825,826,1,'com_jfbconnect','JFBConnect','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (151,18,246,247,2,'com_modules.module.144','SCLogin','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (152,18,248,249,2,'com_modules.module.145','SCSocial Find Us','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (153,18,250,251,2,'com_modules.module.146','SCSocial Stream','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (154,18,252,253,2,'com_modules.module.147','SCSocial Widget','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (155,18,254,255,2,'com_modules.module.148','JFBC Social Share','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (156,1,827,828,1,'com_kunena','com_kunena','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (157,100,360,399,2,'com_joomgallery.category.3','Burning Man 2015','{\"joom.upload\":{\"2\":1},\"joom.upload.inown\":[],\"core.create\":{\"6\":1,\"2\":1,\"3\":1},\"joom.create.inown\":[],\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"core.edit.own\":{\"6\":1,\"2\":1,\"3\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (158,157,361,362,3,'com_joomgallery.image.7','Title_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (159,157,363,364,3,'com_joomgallery.image.8','Title_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (160,157,365,366,3,'com_joomgallery.image.9','Title_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (161,157,367,368,3,'com_joomgallery.image.10','Title_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (162,18,256,257,2,'com_modules.module.149','BT Login','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (163,18,258,259,2,'com_modules.module.150','Login','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (164,157,369,370,3,'com_joomgallery.image.11','Default_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (165,157,371,372,3,'com_joomgallery.image.12','Default_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (166,157,373,374,3,'com_joomgallery.image.13','Default_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (167,157,375,376,3,'com_joomgallery.image.14','Default_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (168,157,377,378,3,'com_joomgallery.image.15','Default_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (169,157,379,380,3,'com_joomgallery.image.16','Default_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (170,1,829,830,1,'com_comprofiler','comprofiler','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (171,18,260,261,2,'com_modules.module.151','Login','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (172,18,262,263,2,'com_modules.module.152','CB Online','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (173,18,264,265,2,'com_modules.module.153','CB Workflows','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (174,18,266,267,2,'com_modules.module.154','CB Admin Dropdown Menu','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (175,18,268,269,2,'com_modules.module.155','Community Builder News','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (176,18,270,271,2,'com_modules.module.156','Community Builder Updates','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (177,18,272,273,2,'com_modules.module.157','CB Admin Version Checker','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (178,157,381,382,3,'com_joomgallery.image.17','the forest_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (179,157,383,384,3,'com_joomgallery.image.18','the forest_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (180,157,385,386,3,'com_joomgallery.image.19','Camp_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (181,157,387,388,3,'com_joomgallery.image.20','Camp_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (182,157,389,390,3,'com_joomgallery.image.21','Camp_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (183,157,391,392,3,'com_joomgallery.image.22','Camp_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (184,157,393,394,3,'com_joomgallery.image.23','Camp_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (185,157,395,396,3,'com_joomgallery.image.24','Mycodelic_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (186,157,397,398,3,'com_joomgallery.image.25','Mycodelic_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (187,18,274,275,2,'com_modules.module.158','Home Logo','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (188,18,276,277,2,'com_modules.module.159','Home Text','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (189,18,278,279,2,'com_modules.module.160','Sidebar','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (190,18,280,281,2,'com_modules.module.161','User Menu','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (191,18,282,283,2,'com_modules.module.162','Burning Man Tips','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (192,1,831,832,1,'com_acymailing','AcyMailing','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (193,18,284,285,2,'com_modules.module.164','Recomended Logo','{\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"6\":1,\"5\":1},\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (194,18,286,287,2,'com_modules.module.165','Sidebar','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (195,1,833,846,1,'com_campinventory','Camp Inventory','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (196,8,60,81,2,'com_content.category.12','The 10 Principles of Burning Man','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (197,196,61,62,3,'com_content.article.14','Radical Inclusion','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (198,196,63,64,3,'com_content.article.15','Gifting','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (199,196,65,66,3,'com_content.article.16','Decommodification','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (200,196,67,68,3,'com_content.article.17','Radical Self-reliance','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (201,196,69,70,3,'com_content.article.18','Radical Self-expression','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (202,196,71,72,3,'com_content.article.19','Communal Effort','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (203,196,73,74,3,'com_content.article.20','Civic Responsibility','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (204,196,75,76,3,'com_content.article.21','Leaving No Trace','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (205,196,77,78,3,'com_content.article.22','Participation','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (206,196,79,80,3,'com_content.article.23','Immediacy','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (207,100,400,817,2,'com_joomgallery.category.4','Burning Man 2016','{\"joom.upload\":{\"12\":1,\"11\":1},\"joom.upload.inown\":{\"12\":1,\"11\":1},\"core.create\":{\"6\":1,\"3\":1},\"joom.create.inown\":[],\"core.delete\":{\"6\":1},\"core.edit\":{\"6\":1,\"4\":1},\"core.edit.state\":{\"11\":1,\"6\":1,\"5\":1},\"core.edit.own\":{\"11\":1,\"6\":1,\"3\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (233,207,401,402,3,'com_joomgallery.image.51','test_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (234,207,403,404,3,'com_joomgallery.image.52','test_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (235,207,405,406,3,'com_joomgallery.image.53','test_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (236,207,407,408,3,'com_joomgallery.image.54','test_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (237,207,409,410,3,'com_joomgallery.image.55','test_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (238,207,411,412,3,'com_joomgallery.image.56','test_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (239,207,413,414,3,'com_joomgallery.image.57','test_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (240,207,415,416,3,'com_joomgallery.image.58','test_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (241,207,417,418,3,'com_joomgallery.image.59','test_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (242,207,419,420,3,'com_joomgallery.image.60','test_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (243,207,421,422,3,'com_joomgallery.image.61','test_11','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (244,207,423,424,3,'com_joomgallery.image.62','test_12','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (245,207,425,426,3,'com_joomgallery.image.63','test_13','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (246,207,427,428,3,'com_joomgallery.image.64','test_14','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (247,207,429,430,3,'com_joomgallery.image.65','test_15','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (248,207,431,432,3,'com_joomgallery.image.66','test_16','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (249,207,433,434,3,'com_joomgallery.image.67','test_17','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (250,207,435,436,3,'com_joomgallery.image.68','test_18','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (251,207,437,438,3,'com_joomgallery.image.69','test_19','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (252,207,439,440,3,'com_joomgallery.image.70','test_20','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (253,207,441,442,3,'com_joomgallery.image.71','test_21','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (254,207,443,444,3,'com_joomgallery.image.72','test_22','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (255,207,445,446,3,'com_joomgallery.image.73','test_23','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (256,207,447,448,3,'com_joomgallery.image.74','Trails Pic\'s_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (257,207,449,450,3,'com_joomgallery.image.75','Trails Pic\'s_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (258,207,451,452,3,'com_joomgallery.image.76','Trails Pic\'s_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (259,207,453,454,3,'com_joomgallery.image.77','Trails Pic\'s_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (260,207,455,456,3,'com_joomgallery.image.78','Trails Pic\'s_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (261,207,457,458,3,'com_joomgallery.image.79','Trails Pic\'s_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (262,207,459,460,3,'com_joomgallery.image.80','Trails Pic\'s_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (263,207,461,462,3,'com_joomgallery.image.81','Trails Pic\'s_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (264,207,463,464,3,'com_joomgallery.image.82','Trails Pic\'s_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (265,207,465,466,3,'com_joomgallery.image.83','Trails Pic\'s_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (266,207,467,468,3,'com_joomgallery.image.84','Trails Pic\'s_11','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (267,207,469,470,3,'com_joomgallery.image.85','Trails Pic\'s_12','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (268,207,471,472,3,'com_joomgallery.image.86','Trails Pic\'s_13','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (269,207,473,474,3,'com_joomgallery.image.87','Trails Pic\'s_14','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (270,207,475,476,3,'com_joomgallery.image.88','Trails Pic\'s_15','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (271,207,477,478,3,'com_joomgallery.image.89','Trails Pic\'s_16','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (272,207,479,480,3,'com_joomgallery.image.90','Trails Pic\'s_17','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (273,207,481,482,3,'com_joomgallery.image.91','Trails Pic\'s_18','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (274,207,483,484,3,'com_joomgallery.image.92','Trails Pic\'s_19','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (275,207,485,486,3,'com_joomgallery.image.93','Trails Pic\'s_20','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (276,207,487,488,3,'com_joomgallery.image.94','Trail\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (277,207,489,490,3,'com_joomgallery.image.95','Trail\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (278,207,491,492,3,'com_joomgallery.image.96','Trail\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (279,207,493,494,3,'com_joomgallery.image.97','Trail\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (280,207,495,496,3,'com_joomgallery.image.98','test 2_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (281,207,497,498,3,'com_joomgallery.image.99','test 2_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (282,207,499,500,3,'com_joomgallery.image.100','test 2_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (283,207,501,502,3,'com_joomgallery.image.101','test 2_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (284,207,503,504,3,'com_joomgallery.image.102','test 2_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (285,207,505,506,3,'com_joomgallery.image.103','test 2_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (286,207,507,508,3,'com_joomgallery.image.104','test 2_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (287,207,509,510,3,'com_joomgallery.image.105','Trail\'s images_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (288,207,511,512,3,'com_joomgallery.image.106','Trail\'s images_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (289,207,513,514,3,'com_joomgallery.image.107','Trail\'s images_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (290,207,515,516,3,'com_joomgallery.image.108','Trail\'s images_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (291,207,517,518,3,'com_joomgallery.image.109','Trail\'s images_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (292,207,519,520,3,'com_joomgallery.image.110','Trail\'s images_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (293,207,521,522,3,'com_joomgallery.image.111','Trail\'s images_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (294,207,523,524,3,'com_joomgallery.image.112','Trail\'s images_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (295,207,525,526,3,'com_joomgallery.image.113','Trail\'s images_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (296,207,527,528,3,'com_joomgallery.image.114','Trail\'s images_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (297,207,529,530,3,'com_joomgallery.image.115','Trail\'s images_11','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (298,207,531,532,3,'com_joomgallery.image.116','Trail\'s images_12','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (299,207,533,534,3,'com_joomgallery.image.117','Trail\'s images_13','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (300,207,535,536,3,'com_joomgallery.image.118','Trail\'s images_14','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (301,207,537,538,3,'com_joomgallery.image.119','Trail\'s images_15','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (302,207,539,540,3,'com_joomgallery.image.120','Trail\'s images_16','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (303,207,541,542,3,'com_joomgallery.image.121','Trail\'s images_17','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (304,207,543,544,3,'com_joomgallery.image.122','Trail\'s images_18','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (305,207,545,546,3,'com_joomgallery.image.123','Trail\'s images_19','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (306,207,547,548,3,'com_joomgallery.image.124','Trail\'s images_20','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (307,207,549,550,3,'com_joomgallery.image.125','Trail\'s images_21','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (308,207,551,552,3,'com_joomgallery.image.126','Trail\'s images_22','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (309,207,553,554,3,'com_joomgallery.image.127','Trail\'s images_23','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (310,207,555,556,3,'com_joomgallery.image.128','Trail\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (311,207,557,558,3,'com_joomgallery.image.129','Trail\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (312,207,559,560,3,'com_joomgallery.image.130','Trail\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (313,207,561,562,3,'com_joomgallery.image.131','Trail\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (314,207,563,564,3,'com_joomgallery.image.132','Trail\'s Pics_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (315,207,565,566,3,'com_joomgallery.image.133','Trail\'s Pics_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (316,207,567,568,3,'com_joomgallery.image.134','Trail\'s Pics_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (317,207,569,570,3,'com_joomgallery.image.135','Trail\'s Pics_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (318,207,571,572,3,'com_joomgallery.image.136','Trail\'s Pics_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (319,207,573,574,3,'com_joomgallery.image.137','Trai\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (320,207,575,576,3,'com_joomgallery.image.138','Trai\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (321,207,577,578,3,'com_joomgallery.image.139','Trai\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (322,207,579,580,3,'com_joomgallery.image.140','Trai\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (323,207,581,582,3,'com_joomgallery.image.141','Trai\'s Pics_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (324,207,583,584,3,'com_joomgallery.image.142','Trai\'s Pics_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (325,207,585,586,3,'com_joomgallery.image.143','Trai\'s Pics_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (326,207,587,588,3,'com_joomgallery.image.144','Trai\'s Pics_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (327,207,589,590,3,'com_joomgallery.image.145','Trai\'s Pics_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (328,207,591,592,3,'com_joomgallery.image.146','Trai\'s Pics_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (329,207,593,594,3,'com_joomgallery.image.147','Trail\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (330,207,595,596,3,'com_joomgallery.image.148','Trail\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (331,207,597,598,3,'com_joomgallery.image.149','Trail\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (332,207,599,600,3,'com_joomgallery.image.150','Trail\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (333,207,601,602,3,'com_joomgallery.image.151','Trail\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (334,207,603,604,3,'com_joomgallery.image.152','Trail\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (335,207,605,606,3,'com_joomgallery.image.153','Trail\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (336,207,607,608,3,'com_joomgallery.image.154','Trail\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (337,207,609,610,3,'com_joomgallery.image.155','Trail\'s Pics_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (338,207,611,612,3,'com_joomgallery.image.156','Trail\'s Pics_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (339,207,613,614,3,'com_joomgallery.image.157','Trail\'s Pics_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (340,207,615,616,3,'com_joomgallery.image.158','Trail\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (341,207,617,618,3,'com_joomgallery.image.159','Trail\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (342,207,619,620,3,'com_joomgallery.image.160','Trail\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (343,207,621,622,3,'com_joomgallery.image.161','Trail\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (344,207,623,624,3,'com_joomgallery.image.162','Trail\'s Pics_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (345,207,625,626,3,'com_joomgallery.image.163','Trail\'s Pics_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (346,207,627,628,3,'com_joomgallery.image.164','Trail\'s Pics_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (347,207,629,630,3,'com_joomgallery.image.165','Trail\'s Pics_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (348,207,631,632,3,'com_joomgallery.image.166','Trail\'s Pics_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (349,207,633,634,3,'com_joomgallery.image.167','Trail\'s Pics_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (350,207,635,636,3,'com_joomgallery.image.168','Trail\'s Pics_11','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (351,207,637,638,3,'com_joomgallery.image.169','Trail\'s Pics_12','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (352,207,639,640,3,'com_joomgallery.image.170','Trail\'s Pics_13','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (353,207,641,642,3,'com_joomgallery.image.171','Trail\'s Pics_14','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (354,207,643,644,3,'com_joomgallery.image.172','Trail\'s Pics_15','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (355,207,645,646,3,'com_joomgallery.image.173','Trail\'s Pics_16','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (356,207,647,648,3,'com_joomgallery.image.174','Trail\'s Pics_17','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (357,207,649,650,3,'com_joomgallery.image.175','Trail\'s Pics_18','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (358,207,651,652,3,'com_joomgallery.image.176','Trail\'s Pics_19','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (359,207,653,654,3,'com_joomgallery.image.177','Trail\'s Pics_20','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (360,207,655,656,3,'com_joomgallery.image.178','Trail\'s Pics_21','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (361,207,657,658,3,'com_joomgallery.image.179','Trail\'s Pics_22','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (362,207,659,660,3,'com_joomgallery.image.180','Trail\'s Pics_23','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (363,207,661,662,3,'com_joomgallery.image.181','Trail\'s Pics_24','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (364,207,663,664,3,'com_joomgallery.image.182','Trail\'s Pics_25','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (365,207,665,666,3,'com_joomgallery.image.183','Trail\'s Pics_26','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (366,207,667,668,3,'com_joomgallery.image.184','Trail\'s Pics_27','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (367,207,669,670,3,'com_joomgallery.image.185','Trail\'s Pics_28','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (368,207,671,672,3,'com_joomgallery.image.186','Trail\'s Pics_29','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (369,207,673,674,3,'com_joomgallery.image.187','Trail\'s Pics_30','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (370,207,675,676,3,'com_joomgallery.image.188','Trail\'s Pics_31','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (371,207,677,678,3,'com_joomgallery.image.189','Trail\'s Pics_32','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (372,207,679,680,3,'com_joomgallery.image.190','Trail\'s Pics_33','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (373,207,681,682,3,'com_joomgallery.image.191','Trail\'s Pics_34','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (374,207,683,684,3,'com_joomgallery.image.192','Trail\'s Pics_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (375,207,685,686,3,'com_joomgallery.image.193','Trail\'s Pics_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (376,207,687,688,3,'com_joomgallery.image.194','Trail\'s Pics_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (377,207,689,690,3,'com_joomgallery.image.195','Trail\'s Pics_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (378,207,691,692,3,'com_joomgallery.image.196','Trail\'s Pics_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (379,207,693,694,3,'com_joomgallery.image.197','Trail\'s Pics_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (380,207,695,696,3,'com_joomgallery.image.198','Trail\'s Pics_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (381,207,697,698,3,'com_joomgallery.image.199','Trail\'s Pics_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (382,207,699,700,3,'com_joomgallery.image.200','Trail\'s Pics_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (383,207,701,702,3,'com_joomgallery.image.201','Trail\'s Pics_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (384,207,703,704,3,'com_joomgallery.image.202','Trail\'s Pics_11','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (385,207,705,706,3,'com_joomgallery.image.203','Trail\'s Pics_12','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (386,207,707,708,3,'com_joomgallery.image.204','Trail\'s Pics_13','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (387,207,709,710,3,'com_joomgallery.image.205','Trail\'s Pics_14','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (388,207,711,712,3,'com_joomgallery.image.206','Trail\'s Pics_15','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (389,207,713,714,3,'com_joomgallery.image.207','Trail\'s Pics_16','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (390,207,715,716,3,'com_joomgallery.image.208','Trail\'s Pics_17','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (391,207,717,718,3,'com_joomgallery.image.209','Trail\'s Pics_18','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (392,207,719,720,3,'com_joomgallery.image.210','Trail\'s Pics_19','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (393,207,721,722,3,'com_joomgallery.image.211','Trail\'s Pics_20','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (394,207,723,724,3,'com_joomgallery.image.212','Trail\'s Pics_21','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (395,207,725,726,3,'com_joomgallery.image.213','Trail\'s Pics_22','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (396,207,727,728,3,'com_joomgallery.image.214','Trail\'s Pics_23','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (397,207,729,730,3,'com_joomgallery.image.215','Trail\'s Pics_24','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (398,207,731,732,3,'com_joomgallery.image.216','Playa Time_1','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (399,207,733,734,3,'com_joomgallery.image.217','Playa Time_2','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (400,207,735,736,3,'com_joomgallery.image.218','Playa Time_3','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (401,207,737,738,3,'com_joomgallery.image.219','Playa Time_4','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (402,207,739,740,3,'com_joomgallery.image.220','Playa Time_5','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (403,207,741,742,3,'com_joomgallery.image.221','Playa Time_6','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (404,207,743,744,3,'com_joomgallery.image.222','Playa Time_7','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (405,207,745,746,3,'com_joomgallery.image.223','Playa Time_8','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (406,207,747,748,3,'com_joomgallery.image.224','Playa Time_9','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (407,207,749,750,3,'com_joomgallery.image.225','Playa Time_10','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (408,207,751,752,3,'com_joomgallery.image.226','Playa Time_11','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (409,207,753,754,3,'com_joomgallery.image.227','Playa Time_12','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (410,207,755,756,3,'com_joomgallery.image.228','Playa Time_13','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (411,207,757,758,3,'com_joomgallery.image.229','Playa Time_14','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (412,207,759,760,3,'com_joomgallery.image.230','Playa Time_15','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (413,207,761,762,3,'com_joomgallery.image.231','Playa Time_16','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (414,207,763,764,3,'com_joomgallery.image.232','Playa Time_17','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (415,207,765,766,3,'com_joomgallery.image.233','Playa Time_18','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (416,207,767,768,3,'com_joomgallery.image.234','Playa Time_19','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (417,207,769,770,3,'com_joomgallery.image.235','Playa Time_20','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (418,207,771,772,3,'com_joomgallery.image.236','Playa Time_21','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (419,207,773,774,3,'com_joomgallery.image.237','Playa Time_22','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (420,207,775,776,3,'com_joomgallery.image.238','Playa Time_23','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (421,207,777,778,3,'com_joomgallery.image.239','Playa Time_24','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (422,207,779,780,3,'com_joomgallery.image.240','Playa Time_25','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (423,207,781,782,3,'com_joomgallery.image.241','Playa Time_26','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (424,207,783,784,3,'com_joomgallery.image.242','Playa Time_27','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (425,207,785,786,3,'com_joomgallery.image.243','Playa Time_28','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (426,207,787,788,3,'com_joomgallery.image.244','Playa Time_29','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (427,207,789,790,3,'com_joomgallery.image.245','Playa Time_30','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (428,207,791,792,3,'com_joomgallery.image.246','Playa Time_31','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (429,207,793,794,3,'com_joomgallery.image.247','Playa Time_32','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (430,207,795,796,3,'com_joomgallery.image.248','Playa Time_33','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (431,207,797,798,3,'com_joomgallery.image.249','Playa Time_34','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (432,207,799,800,3,'com_joomgallery.image.250','Playa Time_35','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (433,207,801,802,3,'com_joomgallery.image.251','Playa Time_36','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (434,207,803,804,3,'com_joomgallery.image.252','Playa Time_37','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (435,207,805,806,3,'com_joomgallery.image.253','Playa Time_38','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (436,207,807,808,3,'com_joomgallery.image.254','Playa Time_39','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (437,207,809,810,3,'com_joomgallery.image.255','Playa Time_40','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (438,207,811,812,3,'com_joomgallery.image.256','Playa Time_41','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (439,207,813,814,3,'com_joomgallery.image.257','Playa Time_42','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (440,207,815,816,3,'com_joomgallery.image.258','Playa Time_43','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (441,1,847,848,1,'com_rsfirewall','RSFirewall!','{\"core.admin\":[],\"core.manage\":[],\"check.run\":[],\"dbcheck.run\":[],\"logs.view\":[],\"lists.manage\":[],\"exceptions.manage\":[],\"feeds.manage\":[],\"updates.view\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (442,18,288,289,2,'com_modules.module.166','RSFirewall! Control Panel Module','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (443,8,82,83,2,'com_content.category.13','Form Submissions','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (444,8,84,89,2,'com_content.category.14','Form Success','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (445,16,106,107,2,'com_menus.menu.10','Form Success','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (446,444,85,86,3,'com_content.article.24','Contact Form Success','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (447,7,16,17,2,'com_contact.category.15','Roster 2017','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (448,1,849,850,1,'#__ucm_content.2','#__ucm_content.2','[]');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (449,1,851,852,1,'com_mycodelic_roster','Mycodelic Camp Roster','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (450,18,290,291,2,'com_modules.module.167','Latest Posts','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (451,18,292,293,2,'com_modules.module.168','Breadcrumbs','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (452,18,294,295,2,'com_modules.module.169','Who\'s Online','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (453,27,21,22,3,'com_content.article.25','2017 Roster','{\"core.admin\":{\"7\":1},\"core.manage\":{\"6\":1},\"core.create\":{\"3\":1},\"core.delete\":[],\"core.edit\":{\"4\":1},\"core.edit.state\":{\"5\":1},\"core.edit.own\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (454,16,108,109,2,'com_menus.menu.11','Camp Menu','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (455,18,296,297,2,'com_modules.module.170','Camp Menu','{\"core.delete\":[],\"core.edit\":[],\"core.edit.state\":[],\"module.edit.frontend\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (456,16,110,111,2,'com_menus.menu.12','Projectfork','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (457,18,298,299,2,'com_modules.module.171','Projectfork','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (458,1,853,854,1,'com_projectfork','com_projectfork','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (459,1,855,864,1,'com_pfprojects','com_pfprojects','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (460,1,865,878,1,'com_pfmilestones','com_pfmilestones','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (461,1,879,900,1,'com_pftasks','com_pftasks','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (462,1,901,908,1,'com_pftime','com_pftime','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (463,1,909,922,1,'com_pfrepo','com_pfrepo','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (464,1,923,930,1,'com_pfforum','com_pfforum','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (465,1,931,932,1,'com_pfusers','com_pfusers','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (466,1,933,940,1,'com_pfcomments','com_pfcomments','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (467,18,300,301,2,'com_modules.module.172','Dashboard Buttons','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (468,18,302,303,2,'com_modules.module.173','Projectfork Tasks','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (469,18,304,305,2,'com_modules.module.174','Projectfork Time Tracking','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (470,459,856,859,2,'com_pfprojects.category.16','Burning Man 2017','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (471,470,857,858,3,'com_pfprojects.project.1','Evaptron','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (472,460,866,867,2,'com_pfmilestones.project.1','Evaptron','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (473,461,880,881,2,'com_pftasks.project.1','Evaptron','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (474,462,902,903,2,'com_pftime.project.1','Evaptron','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (475,463,910,913,2,'com_pfrepo.project.1','Evaptron','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (476,464,924,925,2,'com_pfforum.project.1','Evaptron','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (477,466,934,935,2,'com_pfcomments.project.1','Evaptron','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (478,475,911,912,3,'com_pfrepo.directory.2','Evaptron','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (479,459,860,861,2,'com_pfprojects.project.2','Burning Man 2017','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (480,460,868,875,2,'com_pfmilestones.project.2','Burning Man 2017','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (481,461,882,893,2,'com_pftasks.project.2','Burning Man 2017','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (482,462,904,905,2,'com_pftime.project.2','Burning Man 2017','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (483,463,914,917,2,'com_pfrepo.project.2','Burning Man 2017','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (484,464,926,927,2,'com_pfforum.project.2','Burning Man 2017','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (485,466,936,937,2,'com_pfcomments.project.2','Burning Man 2017','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (486,483,915,916,3,'com_pfrepo.directory.3','Burning Man 2017','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (487,459,862,863,2,'com_pfprojects.project.3','Mycodelic Website','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (488,460,876,877,2,'com_pfmilestones.project.3','Mycodelic Website','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (489,461,894,899,2,'com_pftasks.project.3','Mycodelic Website','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (490,462,906,907,2,'com_pftime.project.3','Mycodelic Website','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (491,463,918,921,2,'com_pfrepo.project.3','Mycodelic Website','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (492,464,928,929,2,'com_pfforum.project.3','Mycodelic Website','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (493,466,938,939,2,'com_pfcomments.project.3','Mycodelic Website','{\"core.create\":[],\"core.edit\":[],\"core.edit.state\":[],\"core.edit.own\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (494,491,919,920,3,'com_pfrepo.directory.4','Mycodelic Website','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (495,489,895,896,3,'com_pftasks.task.1','Change Photo Gallery Pagination','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (496,481,883,884,3,'com_pftasks.task.2','Submit Placement Questionare','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (497,480,869,870,3,'com_pfmilestones.milestone.1','Placement Questionare','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (498,481,885,886,3,'com_pftasks.task.3','Draft the Camp Layout','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (499,481,887,888,3,'com_pftasks.task.4','Prepare Questionare Information','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (500,481,889,890,3,'com_pftasks.task.5','Draft the Camp Description','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (501,480,871,872,3,'com_pfmilestones.milestone.2','Directed Group Sale','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (502,480,873,874,3,'com_pfmilestones.milestone.3','Main Sale','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (503,481,891,892,3,'com_pftasks.task.6','Register for Mail Sale','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (504,489,897,898,3,'com_pftasks.task.7','Smaller screen Sizes sidebar is behaving strangely','{\"core.edit\":[],\"core.edit.state\":[],\"core.delete\":[]}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (505,1,941,952,1,'com_campbudget','Camp Budget','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (506,505,942,943,2,'com_campbudget.category.17','Fuel','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (507,505,944,945,2,'com_campbudget.category.18','Consumables','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (508,505,946,947,2,'com_campbudget.category.19','Infrastructure','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (509,505,948,949,2,'com_campbudget.category.20','Decorations','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (510,505,950,951,2,'com_campbudget.category.21','Transportation','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (511,1,953,954,1,'com_fields','com_fields','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (512,1,955,956,1,'com_associations','com_associations','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (513,195,834,835,2,'com_campinventory.category.22','Playa Tech','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (514,195,836,837,2,'com_campinventory.category.23','Decorations','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (515,195,838,839,2,'com_campinventory.category.24','Lights','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (516,195,840,841,2,'com_campinventory.category.25','Electrical','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (517,195,842,843,2,'com_campinventory.category.26','Camp Tents','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (518,195,844,845,2,'com_campinventory.category.27','Power','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (519,1,957,958,1,'com_jch_optimize','JCH Optimize Pro','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (520,1,959,960,1,'com_civicrm','CiviCRM','{\"civicrm.access_civimail_subscribe_unsubscribe_pages\":{\"1\":1,\"2\":1},\"civicrm.access_all_custom_data\":{\"1\":1,\"2\":1},\"civicrm.access_uploaded_files\":{\"1\":1,\"2\":1},\"civicrm.make_online_contributions\":{\"1\":1,\"2\":1},\"civicrm.profile_listings_and_forms\":{\"1\":1,\"2\":1},\"civicrm.register_for_events\":{\"1\":1,\"2\":1},\"civicrm.view_event_info\":{\"1\":1,\"2\":1},\"civicrm.view_event_participants\":{\"1\":1,\"2\":1}}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (529,27,23,24,3,'com_content.article.26','2018 RSVP','{}');
INSERT INTO `jos_assets` (`id`, `parent_id`, `lft`, `rgt`, `level`, `name`, `title`, `rules`) VALUES (530,444,87,88,3,'com_content.article.27','RSVP Form Success','{}');
/*!40000 ALTER TABLE `jos_assets` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

