<?php /* Smarty version 2.6.30, created on 2018-03-02 18:08:47
         compiled from CRM/Admin/Page/Extensions/AddNew.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'crmScope', 'CRM/Admin/Page/Extensions/AddNew.tpl', 1, false),array('block', 'ts', 'CRM/Admin/Page/Extensions/AddNew.tpl', 12, false),array('modifier', 'capitalize', 'CRM/Admin/Page/Extensions/AddNew.tpl', 28, false),array('modifier', 'replace', 'CRM/Admin/Page/Extensions/AddNew.tpl', 29, false),)), $this); ?>
<?php $this->_tag_stack[] = array('crmScope', array('extensionKey' => "")); $_block_repeat=true;smarty_block_crmScope($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php if ($this->_tpl_vars['remoteExtensionRows']): ?>
  <div id="extensions-addnew">
    <?php echo '<table id="extensions-addnew-table" class="display"><thead><tr><th>'; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'Extension name (key)'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo '</th><th>'; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'Version'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo '</th><th>'; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'Type'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo '</th><th></th></tr></thead><tbody>'; ?><?php $_from = $this->_tpl_vars['remoteExtensionRows']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['extKey'] => $this->_tpl_vars['row']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['localExtensionRows'][$this->_tpl_vars['extKey']]): ?><?php echo ''; ?><?php continue; ?><?php echo ''; ?><?php endif; ?><?php echo '<tr id="addnew-row_'; ?><?php echo $this->_tpl_vars['row']['id']; ?><?php echo '" class="crm-extensions crm-extensions_'; ?><?php echo $this->_tpl_vars['row']['id']; ?><?php echo '"><td class="crm-extensions-label"><a class="collapsed" href="#"></a>&nbsp;<strong>'; ?><?php echo $this->_tpl_vars['row']['label']; ?><?php echo '</strong><br/>('; ?><?php echo $this->_tpl_vars['row']['key']; ?><?php echo ')</td><td class="crm-extensions-label">'; ?><?php echo $this->_tpl_vars['row']['version']; ?><?php echo ' '; ?><?php if ($this->_tpl_vars['row']['upgradable']): ?><?php echo '<br/>('; ?><?php echo $this->_tpl_vars['row']['upgradeVersion']; ?><?php echo ')'; ?><?php endif; ?><?php echo '</td><td class="crm-extensions-description">'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['row']['type'])) ? $this->_run_mod_handler('capitalize', true, $_tmp) : smarty_modifier_capitalize($_tmp)); ?><?php echo '</td><td>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['row']['action'])) ? $this->_run_mod_handler('replace', true, $_tmp, 'xx', $this->_tpl_vars['row']['id']) : smarty_modifier_replace($_tmp, 'xx', $this->_tpl_vars['row']['id'])); ?><?php echo '</td></tr><tr class="hiddenElement" id="crm-extensions-details-addnew-'; ?><?php echo $this->_tpl_vars['row']['id']; ?><?php echo '"><td>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "CRM/Admin/Page/ExtensionDetails.tpl", 'smarty_include_vars' => array('extension' => $this->_tpl_vars['row'])));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</td><td></td><td></td><td></td></tr>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</tbody></table>'; ?>

  </div>
<?php else: ?>
  <div class="messages status no-popup">
       <div class="icon inform-icon"></div>
      <?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>There are no extensions to display. Please click "Refresh" to update information about available extensions.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
  </div>
<?php endif; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_crmScope($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>